/// Walmart Category UPC Sales (Shopper Behavior) view provides information about store and eComm sales at UPC, store and Energy Category level (All Brands).
/// The UPC Store Sales endpoint will contain Store & Ecomm sales, aggregated weekly. Ecomm sales are reported under the store number “-999”. 
/// The sales number under the UPC Store Sales endpoint may not match with the sales number under our Store Sales endpoint.
/// This model is refreshed weekly on Mondays, resulting in a 9 to 15-day delay.
/// 
/// Recommend usage along with:
/// - WM Master: Calendar Week
/// - WM Master: Store
/// - WM Master: UPC
/// - WM Master: Service Channel
/// - WM Master: Mod Trait
/// 
/// Source: WM_UPC_SALES_VIEW
table '05. Metrics - Category Sales Weekly'
	lineageTag: 2639810b-7931-4cdc-8104-9b6b87a54afc

	/// This Year Weekly Sales Amount.
	measure 'TY $ Sales - WMCA Weekly' = SUM(WM_UPC_SALES[TY_SALES_AMT])
		formatString: $#,##0;$(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 1129f175-647a-4d1a-b53e-b0afc439c72b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Sales Units.
	measure 'TY Unit Sales - WMCA Weekly' = SUM(WM_UPC_SALES[TY_SALES_UNIT_QTY])
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: 5aa8c014-9acb-4f57-90a2-a51114d12c3b

		changedProperty = IsHidden

	measure 'TY Basket Count - WMCA Weekly' = SUM(WM_UPC_SALES[TY_BASKET_CNT])
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: 7552adb1-edc5-4004-97ae-e114ac8e53b3

		changedProperty = IsHidden

	measure 'LY $ Sales - WMCA Weekly' = SUM(WM_UPC_SALES[LY_SALES_AMT])
		formatString: $#,##0;$(#,##0)
		displayFolder: Last Year Metrics
		lineageTag: 9a38485b-53e7-4c67-9e73-a39bc60e5ea2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Basket Count - WMCA Weekly' = SUM(WM_UPC_SALES[LY_BASKET_CNT])
		formatString: #,0
		displayFolder: Last Year Metrics
		lineageTag: f7a5853f-bfcc-42f4-9718-4c18e01a24e3

		changedProperty = IsHidden

	measure 'LY Unit Sales - WMCA Weekly' = SUM(WM_UPC_SALES[LY_SALES_UNIT_QTY])
		formatString: #,0
		displayFolder: Last Year Metrics
		lineageTag: dc09cbb6-d849-4393-be17-f46f3113d723

		changedProperty = IsHidden

	/// This Year Avg Week Price.
	measure 'TY Price - WMCA Weekly' = DIVIDE([TY $ Sales - WMCA Weekly], [TY Unit Sales - WMCA Weekly], 0)
		displayFolder: This Year Metrics
		lineageTag: 23566979-6689-4267-b209-f29fd0641eed

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $ Sales YoY - WMCA Weekly' = ```
			DIVIDE(([# Diff $ Sales YoY - WMCA Weekly]),[LY $ Sales - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 6eaf1f7f-e121-47f5-9480-c588e5fd61d6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Unit Sales - WMCA Weekly' = ```
			DIVIDE(([# Diff Unit Sales YoY - WMCA Weekly]),[LY Unit Sales - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 73776359-5469-4d81-979f-3bf7c43d5d88

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Last Year Avg Week Price.
	measure 'LY Price - WMCA Weekly' = DIVIDE([LY $ Sales - WMCA Weekly], [LY Unit Sales - WMCA Weekly], 0)
		displayFolder: Last Year Metrics
		lineageTag: 1b822c92-eb3f-4413-a42b-5575fa4b61d2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Price YoY - WMCA Weekly' = DIVIDE(([TY Price - WMCA Weekly]-[LY Price - WMCA Weekly]),[LY Price - WMCA Weekly], Blank())
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: cfa0534a-5606-4763-b160-3d905796ac98

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Week Count - WMCA Weekly' = CALCULATE(DISTINCTCOUNT(WM_UPC_SALES[WM_YR_WK_NBR]), ALL('WM Master - Calendar Week Pre Relay') )
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: f5ce0f36-2d89-4c8e-899a-180e53977ed6

		changedProperty = IsHidden

	measure 'Store Count - WMCA Weekly' = CALCULATE(DISTINCTCOUNT(WM_UPC_SALES[STORE_NBR]), ALL('WM Master - Calendar Week Pre Relay') )
		displayFolder: This Year Metrics
		lineageTag: 4fcb784b-ee90-41b5-b1d8-5b06940144f5

		changedProperty = IsHidden

	measure 'Stores/Week - WMCA Weekly' = CALCULATE(DISTINCTCOUNT(WM_UPC_SALES[STORE_WEEK_ID]), ALL('WM Master - Calendar Week Pre Relay') )
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: dac202f5-3a60-4f96-b953-a54be73277d1

		changedProperty = IsHidden

	/// This Year Average Weekly Sales Amount.
	measure 'TY Avg Wkly $ Sales - WMCA Weekly' = DIVIDE([TY $ Sales - WMCA Weekly], [Week Count - WMCA Weekly], 0)
		formatString: $#,##0;$(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 86601fd8-7731-4b0f-bb99-fd91f09c8dbe

		changedProperty = IsHidden

	/// Last Year Average Weekly Sales Amount.
	measure 'LY Avg Wkly $ Sales - WMCA Weekly' = DIVIDE([LY $ Sales - WMCA Weekly], [Week Count - WMCA Weekly], 0)
		formatString: $#,##0;$(#,##0)
		displayFolder: Last Year Metrics
		lineageTag: 7e9a3192-11ca-4eab-88bf-3c38cac38611

		changedProperty = IsHidden

	/// This Year Average Weekly Sales Units.
	measure 'TY Avg Wkly Unit Sales - WMCA Weekly' = DIVIDE([TY Unit Sales - WMCA Weekly], [Week Count - WMCA Weekly], 0)
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: 8ab52816-82b3-4333-b8ef-1b5415d72b31

		changedProperty = IsHidden

	/// Last Year Average Weekly Sales Units.
	measure 'LY Avg Wkly Unit Sales - WMCA Weekly' = DIVIDE([LY Unit Sales - WMCA Weekly], [Week Count - WMCA Weekly], 0)
		formatString: #,0
		displayFolder: Last Year Metrics
		lineageTag: b572cfaa-0f69-4bc2-9e91-a6373a790706

		changedProperty = IsHidden

	/// This Year $ Sales Velocity: $ per Store per Week.
	measure 'TY $/S/W - WMCA Weekly' = DIVIDE([TY $ Sales - WMCA Weekly], [Stores/Week - WMCA Weekly], 0)
		formatString: $#,##0;$(#,##0)
		displayFolder: This Year Metrics
		lineageTag: fa99ffe3-803b-4284-b431-69e40911c3af

		changedProperty = IsHidden

	/// Last Year $ Sales Velocity: $ per Store per Week.
	measure 'LY $/S/W - WMCA Weekly' = DIVIDE([LY $ Sales - WMCA Weekly], [Stores/Week - WMCA Weekly], 0)
		formatString: $#,##0;$(#,##0)
		displayFolder: Last Year Metrics
		lineageTag: 1e08549b-74e4-4a86-9c23-4acdca1510f1

		changedProperty = IsHidden

	/// This Year Unit Sales Velocity: Units per Store per Week.
	measure 'TY U/S/W - WMCA Weekly' = DIVIDE([TY Unit Sales - WMCA Weekly], [Stores/Week - WMCA Weekly], 0)
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: c27e79cc-54da-44a7-b608-9b37bd28cc9e

		changedProperty = IsHidden

	/// Last Year Unit Sales Velocity: Units per Store per Week.
	measure 'LY U/S/W - WMCA Weekly' = DIVIDE([LY Unit Sales - WMCA Weekly], [Stores/Week - WMCA Weekly], 0)
		formatString: #,0
		displayFolder: Last Year Metrics
		lineageTag: 12b17371-c790-42f6-9b8e-74831224e01d

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff $ Sales YoY - WMCA Weekly' = [TY $ Sales - WMCA Weekly] - [LY $ Sales - WMCA Weekly]
		formatString: $#,##0;$(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 62709040-8e89-4d67-8163-954f10ed9cab

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Unit Sales YoY - WMCA Weekly' = [TY Unit Sales - WMCA Weekly] - [LY Unit Sales - WMCA Weekly]
		formatString: #,##0;(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: aca56981-6314-47ac-8e68-2195f4413051

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff $/S/W YoY - WMCA Weekly' = [TY $/S/W - WMCA Weekly] - [LY $/S/W - WMCA Weekly]
		formatString: $#,##0;$(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 49daf4a6-9500-4022-96f5-1a3d70f8ced7

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff U/S/W YoY - WMCA Weekly' = [TY U/S/W - WMCA Weekly] - [LY U/S/W - WMCA Weekly]
		formatString: #,##0;(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: d94b3bbb-6477-4b5f-9419-d4ff33955edc

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Avg Wkly $ Sales YoY - WMCA Weekly' = [TY Avg Wkly $ Sales - WMCA Weekly] - [LY Avg Wkly $ Sales - WMCA Weekly]
		formatString: $#,##0;$(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 3cf0fc4d-876e-4170-ad39-39aa8a0013de

		changedProperty = IsHidden

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Avg Wkly Unit Sales YoY - WMCA Weekly' = [TY Avg Wkly Unit Sales - WMCA Weekly] - [LY Avg Wkly Unit Sales - WMCA Weekly]
		formatString: #,##0;(#,##0)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 2b09d359-3c69-44db-a102-aeb4834c5362

		changedProperty = IsHidden

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly $ Sales YoY - WMCA Weekly' = ```
			DIVIDE(([# Diff Avg Wkly $ Sales YoY - WMCA Weekly]),[LY $ Sales - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 887ef56a-9a74-4537-be6d-cbf5df3bd071

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly Unit Sales YoY - WMCA Weekly' = ```
			DIVIDE(([# Diff Avg Wkly Unit Sales YoY - WMCA Weekly]),[LY Unit Sales - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: f2e12b18-0de9-486f-8517-36e135812b84

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $/S/W YoY - WMCA Weekly' = ```
			DIVIDE(([# Diff $/S/W YoY - WMCA Weekly]),[LY $/S/W - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 37126808-d136-4a6e-b327-dae5506a1d06

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg U/S/W YoY - WMCA Weekly' = ```
			DIVIDE(([# Diff U/S/W YoY - WMCA Weekly]),[LY U/S/W - WMCA Weekly])
			
			```
		formatString: +0.0%;(0.0%)
		displayFolder: Year over Year (YoY) Metrics
		lineageTag: 403d9a7c-271d-4dcb-a77a-a7935acca6e7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure '$ Share - WMCA Weekly' =
			DIVIDE(
			    [TY $ Sales - WMCA Weekly],
			    CALCULATE(
			        [TY $ Sales - WMCA Weekly],
			        ALLEXCEPT(WM_UPC_SALES, WM_UPC_SALES[WM_YR_WK_NBR] ),
			        REMOVEFILTERS(WM_UPC_SALES),
			        'WM Master - Mod Trait'[TRAIT_NBR] <> BLANK(),
			        'WM Master - Mod Trait'[TRAIT_NBR] <> 0,
			        'WM Master - UPC'[CA_PACK_TYPE] <> Blank(),
			        'WM Master - UPC'[CA_PACK_TYPE] <> "Not Applicable",
			        VALUES(WM_UPC_SALES[WM_YR_WK_NBR])
			    )
			) * 100
		formatString: 0.0
		displayFolder: This Year Metrics
		lineageTag: 5dd1426e-cb29-43dc-bd6c-2ce4fec5e64e

		changedProperty = IsHidden

	measure 'Unit Share - WMCA Weekly' =
			DIVIDE(
			    [TY Unit Sales - WMCA Weekly],
			    CALCULATE(
			        [TY Unit Sales - WMCA Weekly],
			        ALLEXCEPT(WM_UPC_SALES, WM_UPC_SALES[WM_YR_WK_NBR] ),
			        REMOVEFILTERS(WM_UPC_SALES),
			        'WM Master - Mod Trait'[TRAIT_NBR] <> BLANK(),
			        'WM Master - Mod Trait'[TRAIT_NBR] <> 0,
			        'WM Master - UPC'[CA_PACK_TYPE] <> Blank(),
			        'WM Master - UPC'[CA_PACK_TYPE] <> "Not Applicable",
			        VALUES(WM_UPC_SALES[WM_YR_WK_NBR])
			    )
			) * 100
		formatString: 0.0
		displayFolder: This Year Metrics
		lineageTag: a6705556-b439-45ab-90f9-f22cf7b740f5

		changedProperty = IsHidden

	measure 'TY C/S/W - WMCA Weekly' = DIVIDE([TY $/S/W - WMCA Weekly]+[TY U/S/W - WMCA Weekly], 2, 0)
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: e5df3334-7d4c-4822-b146-06f6e53d71a5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY C/S/W - WMCA Weekly' = DIVIDE([LY $/S/W - WMCA Weekly]+[LY U/S/W - WMCA Weekly], 2, 0)
		formatString: #,##0;(#,##0)
		displayFolder: Last Year Metrics
		lineageTag: 26e3fab1-99ca-45c5-8933-0b9b2822d3b6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Red Bull $ Share - WMCA Weekly' =
			
			DIVIDE(
			    CALCULATE( [TY $ Sales - WMCA Weekly], 'WM Master - UPC'[CA_BRAND] = "Red Bull" ),
			    [TY $ Sales - WMCA Weekly]
			)*100
		formatString: 0.0
		displayFolder: This Year Metrics
		lineageTag: 13e90c91-8146-4860-bc7d-139f6a9a5c0d

		changedProperty = IsHidden

	measure 'Monster $ Share - WMCA Weekly' =
			
			DIVIDE(
			    CALCULATE( [TY $ Sales - WMCA Weekly], 'WM Master - UPC'[CA_BRAND] = "Monster" ),
			    [TY $ Sales - WMCA Weekly]
			)*100
		formatString: 0.0
		displayFolder: This Year Metrics
		lineageTag: 62a39b08-f960-48aa-979f-26a56578e2fc

		changedProperty = IsHidden

	measure 'All Others $ Share - WMCA Weekly' =
			
			DIVIDE(
			    CALCULATE( [TY $ Sales - WMCA Weekly], 'WM Master - UPC'[CA_BRAND] <> "Monster", 'WM Master - UPC'[CA_BRAND] <> "Red Bull" ),
			    [TY $ Sales - WMCA Weekly]
			)*100
		formatString: 0.0
		displayFolder: This Year Metrics
		lineageTag: 918a9ede-cb44-4dc9-a646-e98d9bd4a6e2

		changedProperty = IsHidden

	measure 'Red Bull $ Rank - WMCA Weekly' =
			
			VAR _total =
			    CALCULATE( [TY $ Sales - WMCA Weekly] )
			VAR _redBull = CALCULATE( [Red Bull $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _monster = CALCULATE( [Monster $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _others  = CALCULATE( [All Others $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			RETURN
			    IF(
			        ISBLANK( _total ) || _total = 0, -- Don't display filtered Stores
			        BLANK(), -- Don't display filtered Stores
			        1 +
			        IF( _monster > _redBull, 1, 0 ) +
			        IF( _others  > _redBull, 1, 0 )
			    )
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: dabc59ae-d0e8-41f5-974e-5f3c4a5d46f2

		changedProperty = IsHidden

	measure 'Monster $ Rank - WMCA Weekly' =
			
			VAR _total =
			    CALCULATE( [TY $ Sales - WMCA Weekly] )
			VAR _redBull = CALCULATE( [Red Bull $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _monster = CALCULATE( [Monster $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _others  = CALCULATE( [All Others $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			RETURN
			    IF(
			        ISBLANK( _total ) || _total = 0, -- Don't display filtered Stores
			        BLANK(), -- Don't display filtered Stores
			        1 +
			        IF( _redBull > _monster, 1, 0 ) +
			        IF( _others  > _monster, 1, 0 )
			    )
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: 877e3fb1-24f0-4d62-84ba-7a6b0e7ecc12

		changedProperty = IsHidden

	measure 'All Others $ Rank - WMCA Weekly' =
			
			VAR _total =
			    CALCULATE( [TY $ Sales - WMCA Weekly] )
			VAR _redBull = CALCULATE( [Red Bull $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _monster = CALCULATE( [Monster $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			VAR _others  = CALCULATE( [All Others $ Share - WMCA Weekly], ALL( 'WM Master - UPC'[CA_BRAND] ) )
			RETURN
			    IF(
			        ISBLANK( _total ) || _total = 0, -- Don't display filtered Stores
			        BLANK(), -- Don't display filtered Stores
			        1 +
			        IF( _redBull > _others, 1, 0 ) +
			        IF( _monster  > _others, 1, 0 )
			    )
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: 5e56234c-41c2-4050-98c1-38747b8b2818

		changedProperty = IsHidden

	partition '05. Metrics - Category Sales Weekly' = m
		mode: import
		queryGroup: 'Reporting - Metrics'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

