table '09.  Metrics - Hourly Store Inventory'
	lineageTag: bb748b46-6e15-46a2-9187-9703054c0be4

	measure 'Hourly Inventory' =
			
			SUMX(
			    TOPN(
			        1,
			        WM_HOURLY_STORE_INVENTORY,
			        WM_HOURLY_STORE_INVENTORY[BUS_DT],  DESC,
			        WM_HOURLY_STORE_INVENTORY[HOUR], DESC
			    ),
			    WM_HOURLY_STORE_INVENTORY[QUANTITY]
			)
		formatString: #,0
		lineageTag: b206a66c-c865-4cd2-8f58-c3195a4597b3

	measure 'Inventory End of Day' =
			
			SUMX(
			    TOPN(
			        1,
			        WM_HOURLY_STORE_INVENTORY,
			        WM_HOURLY_STORE_INVENTORY[BUS_DT],  DESC,
			        WM_HOURLY_STORE_INVENTORY[HOUR], DESC
			    ),
			    WM_HOURLY_STORE_INVENTORY[QUANTITY]
			)
		formatString: #,0
		lineageTag: 545e7dfa-d581-4e6e-aba2-445c0391b524

	measure 'Inventory Beginning of the Day' =
			
			SUMX(
			    TOPN(
			        1,
			        WM_HOURLY_STORE_INVENTORY,
			        WM_HOURLY_STORE_INVENTORY[BUS_DT],  DESC,
			        WM_HOURLY_STORE_INVENTORY[HOUR], ASC
			    ),
			    WM_HOURLY_STORE_INVENTORY[QUANTITY]
			)
		formatString: #,0
		lineageTag: 2f66fa91-592b-42c3-80cb-80fc79f65d25

	partition '09.  Metrics - Hourly Store Inventory' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

