/// The Store Dimensions model provides attribute information for the given Walmart store number, including information such as location, manager details, and related codes. 
/// 
/// Source: WM_STORE_DIMENSIONS_VIEW
table 'WM Master - Store'
	lineageTag: c3ef04a7-3e5f-4554-aeb4-91cfcced9f3d

	/// Store Number
	column STORE_NBR
		dataType: int64
		formatString: 0
		lineageTag: 4f93b9c3-4e46-4847-97ec-359eb0027eea
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Name
	column STORE_NM
		dataType: string
		lineageTag: af8fb983-3d23-479c-894c-731b42bab15d
		summarizeBy: none
		sourceColumn: STORE_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Banner Code: A code which represents the sign or banner on the outside of the store.
	column BANNER_CD
		dataType: string
		lineageTag: 70302891-0dd3-4a1e-b18c-37812f7977bd
		summarizeBy: none
		sourceColumn: BANNER_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Banner Description: The description of the sign or banner on the outside of the store.
	column BANNER_DESC
		dataType: string
		lineageTag: ea411884-b389-4c4f-aced-1215beabd5cb
		summarizeBy: none
		sourceColumn: BANNER_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Base Division Number
	column BASE_DIV_NBR
		dataType: int64
		formatString: 0
		lineageTag: 54454b05-275b-4139-9b57-ed1e6c9beaa0
		summarizeBy: sum
		sourceColumn: BASE_DIV_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// City Name
	column CITY_NM
		dataType: string
		lineageTag: fa66797a-9e15-4a0e-88e2-9daf18c7c35b
		summarizeBy: none
		sourceColumn: CITY_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// County Name
	column CNTY_NM
		dataType: string
		lineageTag: 0fad62c1-b874-4dee-b836-c200967e712d
		summarizeBy: none
		sourceColumn: CNTY_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Close Date: The date the store closed for business.
	column FIN_CLOSE_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 45b83ad5-0976-4279-b039-1baf7ad35903
		summarizeBy: none
		sourceColumn: FIN_CLOSE_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Financial Open Date: This is the date that the store opened for business.
	column FIN_OPEN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8dd01aad-af43-416c-b48b-3775083bba9d
		summarizeBy: none
		sourceColumn: FIN_OPEN_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Latitude Degree
	column LAT_DGR
		dataType: double
		lineageTag: 4b037a5c-05c0-43c5-82ee-913f87914928
		summarizeBy: sum
		sourceColumn: LAT_DGR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Longitude Degree
	column LONG_DGR
		dataType: double
		lineageTag: 6944fba4-1b87-4ce7-adba-33b22c6ccac0
		summarizeBy: sum
		sourceColumn: LONG_DGR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Walmart Market Number
	column MARKET_NBR
		dataType: int64
		formatString: 0
		lineageTag: 9835fd76-9650-4da9-9d15-70fb8a6993c0
		summarizeBy: sum
		sourceColumn: MARKET_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Market Name
	column MARKET_NM
		dataType: string
		lineageTag: c6cefc24-d5a8-49fd-a657-2ea8dba1d6c2
		summarizeBy: none
		sourceColumn: MARKET_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Open 24 HR Indicator
	column OPEN_24_HR_IND
		dataType: double
		lineageTag: 1a9858f3-b24b-4253-b68b-767015fb8d8f
		summarizeBy: sum
		sourceColumn: OPEN_24_HR_IND

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Open Status Code
	column OPEN_STATUS_CD
		dataType: int64
		formatString: 0
		lineageTag: 4db6f8b9-5e90-4849-91cc-a9f03d3b2946
		summarizeBy: sum
		sourceColumn: OPEN_STATUS_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Open Status Description
	column OPEN_STATUS_DESC
		dataType: string
		lineageTag: 89b07ed5-631e-4e3f-8b31-f60696edfa44
		summarizeBy: none
		sourceColumn: OPEN_STATUS_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Open Sunday Indicator
	column OPEN_SUN_IND
		dataType: double
		lineageTag: 39ac2282-d5c0-4b97-9611-66510cf3902f
		summarizeBy: sum
		sourceColumn: OPEN_SUN_IND

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Operation Close Date
	column OP_CLOSE_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a448162-0d5e-4ca9-a555-10c34ee8ac01
		summarizeBy: none
		sourceColumn: OP_CLOSE_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Walmart Region Number
	column REGION_NBR
		dataType: int64
		formatString: 0
		lineageTag: 693d8895-19d2-41fb-81f1-8f61e664fc2b
		summarizeBy: sum
		sourceColumn: REGION_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Region Name
	column REGION_NM
		dataType: string
		lineageTag: ee7150ec-f6e3-4671-b065-8bb5a9f7e907
		summarizeBy: none
		sourceColumn: REGION_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Relocation Flip Date
	column RELO_FLIP_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: d84c878e-71da-4a0e-a5b1-f50b3065332a
		summarizeBy: none
		sourceColumn: RELO_FLIP_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Segment Number
	column SEG_NBR
		dataType: double
		lineageTag: 6077158d-e55b-4b91-852c-cb87748aac03
		summarizeBy: sum
		sourceColumn: SEG_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Segment Name
	column SEG_NM
		dataType: string
		lineageTag: a6e4677d-95d1-4a7b-9c71-c9facfd8c3cf
		summarizeBy: none
		sourceColumn: SEG_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// State or Province Code	
	column STATE_PROV_CD
		dataType: string
		lineageTag: 8e5e51de-3e21-46fd-b58a-07a88803718a
		summarizeBy: none
		sourceColumn: STATE_PROV_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Manager Name
	column STORE_MGR_NM
		dataType: string
		lineageTag: dc67af10-2af2-4aa2-b623-41189c33cfee
		summarizeBy: none
		sourceColumn: STORE_MGR_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Type Code
	column STORE_TYPE_CD
		dataType: string
		lineageTag: c27b7b2e-ee81-43e1-9ac9-23359f3069e2
		summarizeBy: none
		sourceColumn: STORE_TYPE_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Type Description	
	column STORE_TYPE_DESC
		dataType: string
		lineageTag: 9d08864f-1786-4574-9475-c23ae93388ba
		summarizeBy: none
		sourceColumn: STORE_TYPE_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// State Province Name
	column ST_PROV_NM
		dataType: string
		lineageTag: 5ffcc482-14e7-42dc-9fb9-d99953501b51
		summarizeBy: none
		sourceColumn: ST_PROV_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Subdivision Number
	column SUBDIVISION_NBR
		dataType: string
		lineageTag: 96c37015-2391-4d27-af40-2c2b37efae90
		summarizeBy: none
		sourceColumn: SUBDIVISION_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Subdivision Name
	column SUBDIVISION_NM
		dataType: string
		lineageTag: 124c21c4-cbac-4d07-bc91-14b6d5d5a973
		summarizeBy: none
		sourceColumn: SUBDIVISION_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Number - Text Format
	column STORE_NBR_TXT
		dataType: int64
		formatString: 0
		lineageTag: 23936142-bb55-4edf-9db4-0065609ac1a1
		summarizeBy: sum
		sourceColumn: STORE_NBR_TXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Region Number - Text Format
	column STORE_REGION_NBR_TXT
		dataType: int64
		formatString: 0
		lineageTag: 2c4beb33-beb6-4ffc-8cc1-1c2a7a0d2c94
		summarizeBy: sum
		sourceColumn: STORE_REGION_NBR_TXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Market Number - Text Format
	column MARKET_NBR_TXT
		dataType: int64
		formatString: 0
		lineageTag: 1289ea94-3d4a-4033-9684-765262ae8c7f
		summarizeBy: sum
		sourceColumn: MARKET_NBR_TXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STORE_NBR_NAME
		dataType: string
		lineageTag: 419864a1-019f-49b8-acaa-35b5a672b6e3
		summarizeBy: none
		sourceColumn: STORE_NBR_NAME
		sortByColumn: STORE_NBR

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Red Bull Business Unit
	column RB_BU
		dataType: string
		lineageTag: 93c2f821-30cc-409d-bebd-5f92488ab9e1
		summarizeBy: none
		sourceColumn: RB_BU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Red Bull Business Unit Description
	column RB_BU_DESC
		dataType: string
		lineageTag: 52570517-a9ac-4f06-8fd0-4631423c2ea0
		summarizeBy: none
		sourceColumn: RB_BU_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Red Bull Region
	column RB_REGION
		dataType: string
		lineageTag: 4c27837d-53b5-4bca-ac16-95d4d91d0dd4
		summarizeBy: none
		sourceColumn: RB_REGION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Red Bull Region Description
	column RB_REGION_DESC
		dataType: string
		lineageTag: 2aa4b9c8-3b8a-4eba-9026-a1608b8aba50
		summarizeBy: none
		sourceColumn: RB_REGION_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Red Bull Business Unit
	column 'RB BU'
		dataType: string
		lineageTag: e734d1e1-c8db-4305-950d-0ef4c5663bf8
		summarizeBy: none
		sourceColumn: RB BU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Distribution Partner Number
	column DP
		dataType: string
		lineageTag: 97359f8b-76ef-4a09-9752-32c975b2b6ad
		summarizeBy: none
		sourceColumn: DP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Distribution Partner Description
	column DP_DESC
		dataType: string
		lineageTag: 19fc43a9-868b-4bfa-9d15-3b3f70e00ad9
		summarizeBy: none
		sourceColumn: DP_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Trait (As Is): This is the Main Placement or Combo Mod Trait Number currently assigned to the Store.
	column TRAIT_AS_IS
		dataType: int64
		lineageTag: a3b20d9b-6ab1-4f57-a9ce-070fb4a26946
		summarizeBy: none
		sourceColumn: TRAIT_AS_IS

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DPM
		dataType: string
		lineageTag: 8ddbb328-74ec-4853-a6bc-3e0bc28761b6
		summarizeBy: none
		sourceColumn: DPM

		annotation SummarizationSetBy = Automatic

	column DSM
		dataType: int64
		formatString: 0
		lineageTag: a46fb4b1-6d1a-4f67-85b3-b80e74facea0
		summarizeBy: sum
		sourceColumn: DSM

		annotation SummarizationSetBy = Automatic

	column RAM
		dataType: int64
		formatString: 0
		lineageTag: 6ad28150-f8a9-4880-9595-0439aaabb950
		summarizeBy: sum
		sourceColumn: RAM

		annotation SummarizationSetBy = Automatic

	column DOD
		dataType: string
		lineageTag: d47e5260-5a65-4634-a6fe-27d9da3adab0
		summarizeBy: none
		sourceColumn: DOD

		annotation SummarizationSetBy = Automatic

	column RBDC_VS_3RD_PARTY
		dataType: string
		lineageTag: e0f98ba9-1b17-4483-96e5-5377e7a32e0c
		summarizeBy: none
		sourceColumn: RBDC_VS_3RD_PARTY

		annotation SummarizationSetBy = Automatic

	column LOCATION_SENDER
		dataType: string
		lineageTag: 288a8597-8b92-45d6-ba42-3678b728ca52
		summarizeBy: none
		sourceColumn: LOCATION_SENDER

		annotation SummarizationSetBy = Automatic

	column DP_BRANCH
		dataType: string
		lineageTag: 81a5dc07-5bfa-4410-8606-95e7fcdbc304
		summarizeBy: none
		sourceColumn: DP_BRANCH

		annotation SummarizationSetBy = Automatic

	column LS_LOCATION
		dataType: string
		lineageTag: e9d1a223-c9f9-491f-9760-50b93afe2fbb
		summarizeBy: none
		sourceColumn: LS_LOCATION

		annotation SummarizationSetBy = Automatic

	column LS_STREET
		dataType: string
		lineageTag: 111e2130-25ed-422c-b727-58433698a7ae
		summarizeBy: none
		sourceColumn: LS_STREET

		annotation SummarizationSetBy = Automatic

	column LS_POSTAL_CODE
		dataType: int64
		formatString: 0
		lineageTag: 679e220f-c364-4b46-935b-72388a78daef
		summarizeBy: sum
		sourceColumn: LS_POSTAL_CODE

		annotation SummarizationSetBy = Automatic

	column ST_ADDR_LINE_2
		dataType: string
		lineageTag: f9a44dcd-93f6-42cc-958e-6931d86208b5
		summarizeBy: none
		sourceColumn: ST_ADDR_LINE_2

		annotation SummarizationSetBy = Automatic

	column ST_ADDR_LINE_3
		dataType: string
		lineageTag: 5cf8011e-e89a-42cd-a69b-7b915d0b9c32
		summarizeBy: none
		sourceColumn: ST_ADDR_LINE_3

		annotation SummarizationSetBy = Automatic

	column ST_ADDR_LINE_4
		dataType: string
		lineageTag: 5fb80146-f657-4844-b5d7-62d74add5a6d
		summarizeBy: none
		sourceColumn: ST_ADDR_LINE_4

		annotation SummarizationSetBy = Automatic

	column ST_ADDR_LINE_1
		dataType: string
		lineageTag: ef9e3e86-c4d2-4392-b0a6-bab09ff7ad2b
		summarizeBy: none
		sourceColumn: ST_ADDR_LINE_1

		annotation SummarizationSetBy = Automatic

	column POSTAL_CD
		dataType: string
		lineageTag: 7d1c7d28-da19-498c-9d71-4f04916a291e
		summarizeBy: none
		sourceColumn: POSTAL_CD

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_RECEIVER
		dataType: string
		lineageTag: 57ed52b7-eab9-42c5-b1d9-733238ec3de1
		summarizeBy: none
		sourceColumn: CUSTOMER_RECEIVER

		annotation SummarizationSetBy = Automatic

	column SOFT_OPEN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 46bd9975-3f4a-4d35-8237-ccef018ad930
		summarizeBy: none
		sourceColumn: SOFT_OPEN_DT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TEMP_CLOSE_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e398eb6-4808-4643-a3e3-c72e36fa3418
		summarizeBy: none
		sourceColumn: TEMP_CLOSE_DT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TEMP_REOPN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: ecfbcb6c-b66c-4169-b931-07cb4036a583
		summarizeBy: none
		sourceColumn: TEMP_REOPN_DT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GRAND_OPEN_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: d92f2a29-0253-4d7d-9c93-fc905c8451cc
		summarizeBy: none
		sourceColumn: GRAND_OPEN_DT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PUBLIC_CLOSE_DT
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2dd6e26d-4161-43bc-9902-a053159badb3
		summarizeBy: none
		sourceColumn: PUBLIC_CLOSE_DT

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'WM Master - Store' = m
		mode: import
		queryGroup: 'Reporting - Master Data'
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    LUMINATE_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = LUMINATE_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    STORE_DIMENSIONS_VIEW_View = GOLD_Schema{[Name="WM_STORE_DIMENSIONS_VIEW",Kind="View"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(STORE_DIMENSIONS_VIEW_View,{"ADDR_CNTRY_CD", "BUO_AREA_NM", "BU_COMP_CD", "BU_COMP_DESC", "BU_GROSS_SIZE_QTY", "BU_PUBLIC_CLOSE_TM", "BU_PUBLIC_OPEN_TM", "BU_SIZE_UOM_CD", "DAYLIGHT_SAV_TZ_IND", "DRV_THRU_PHARM_IND", "DST_TZ_CD", "DST_TZ_NM", "EXPND_SIZE_QTY", "FEED_TYPE", "FILE_NAME", "FIN_RPT_CD", "FIPS_CNTY_CD", "GEO_REGION_CD", "MDSE_MAJ_ZONE_NBR", "MDSE_SUB_ZONE_NBR", "OP_CMPNY_CD", "PH_NBR", "PRMRY_LANG_CD", "PROTO_NBR", "REAL_ESTAT_PROTO_CD", "TZ_CD", "TZ_NM", "WEA_ZONE_CD", "BUO_AREA_NBR", "STATUS_DATE"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"BASE_DIV_NBR", Int64.Type}, {"MARKET_NBR", Int64.Type}, {"REGION_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"STORE_NBR", "STORE_NM", "BANNER_CD", "BANNER_DESC", "BASE_DIV_NBR", "CITY_NM", "CNTY_NM", "FIN_CLOSE_DT", "FIN_OPEN_DT", "LAT_DGR", "LONG_DGR", "MARKET_NBR", "MARKET_NM", "OPEN_24_HR_IND", "OPEN_STATUS_CD", "OPEN_STATUS_DESC", "OPEN_SUN_IND", "OP_CLOSE_DT", "REGION_NBR", "REGION_NM", "RELO_FLIP_DT", "SEG_NBR", "SEG_NM", "STATE_PROV_CD", "STORE_MGR_NM", "STORE_TYPE_CD", "STORE_TYPE_DESC", "ST_PROV_NM", "SUBDIVISION_NBR", "SUBDIVISION_NM"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns", "STORE_NBR", "STORE_NBR - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "REGION_NBR", "REGION_NBR - Copy"),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "MARKET_NBR", "MARKET_NBR - Copy"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column2",{{"STORE_NBR - Copy", type text}, {"REGION_NBR - Copy", type text}, {"MARKET_NBR - Copy", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"STORE_NBR - Copy", "STORE_NBR_TXT"}, {"REGION_NBR - Copy", "STORE_REGION_NBR_TXT"}, {"MARKET_NBR - Copy", "MARKET_NBR_TXT"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns", WM_STORES_S2H}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Appended Query", "STORE_NBR_NAME", each Text.Combine({Text.From([STORE_NBR], "en-US"), [STORE_NM]}, " "), type text),
				    #"Inserted Merged Column 2" = Table.AddColumn(#"Inserted Merged Column", "RB BU", each Text.Combine({Text.From([RB_BU], "en-US"), [RB_BU_DESC]}, " "), type text),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Inserted Merged Column 2",{{"STORE_NBR_TXT", Int64.Type}, {"MARKET_NBR_TXT", Int64.Type}, {"LS_POSTAL_CODE", Int64.Type}, {"STORE_REGION_NBR_TXT", Int64.Type}, {"OPEN_STATUS_CD", Int64.Type}, {"DSM", Int64.Type}, {"RAM", Int64.Type}})
				in
				    #"Changed Type2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

