/// Additional Calendar View used only to compare two different Time Frames.
/// Used for Pre Post Comparison analysis.
/// 
/// Source: WM_CALENDAR_WEEK_VIEW
table 'WM Master - Calendar Week Pre Relay'
	lineageTag: b24b777c-25ac-4f73-ac97-538096d4683a

	column WM_YR_WK_NBR
		dataType: int64
		formatString: 0
		lineageTag: 64898e75-8491-4c51-9716-2b4ac1da85be
		summarizeBy: none
		sourceColumn: WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Week Number
	column WM_WK_NBR
		dataType: double
		formatString: 0
		lineageTag: 1fa92c40-7b08-41a5-870f-93b768dd5708
		summarizeBy: none
		sourceColumn: WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Full Year Number
	column WM_FULL_YR_NBR
		dataType: double
		formatString: 0
		lineageTag: 487e6df1-c5ab-437f-8dad-810d9bf06028
		summarizeBy: none
		sourceColumn: WM_FULL_YR_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WM_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35c6a1cd-d4fd-4caf-ae1e-1f0d069c6271
		summarizeBy: none
		sourceColumn: WM_START_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WM_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: c44e5a75-4a08-4471-98d7-b51ea2808c99
		summarizeBy: none
		sourceColumn: WM_END_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FYTD_FLAG
		dataType: string
		lineageTag: 63137661-a888-4e4b-ba84-f1ba91ac1f91
		summarizeBy: none
		sourceColumn: FYTD_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LW_FLAG
		dataType: string
		lineageTag: da3de685-99e3-4b6e-817b-9264d0239838
		summarizeBy: none
		sourceColumn: LW_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column L13W_FLAG
		dataType: string
		lineageTag: 349bca55-1318-490a-b11a-6686cb505b6f
		summarizeBy: none
		sourceColumn: L13W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column L4W_FLAG
		dataType: string
		lineageTag: e539764b-7063-4fec-91bd-766dd926ace5
		summarizeBy: none
		sourceColumn: L4W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column L52W_FLAG
		dataType: string
		lineageTag: 09ad2639-33b6-448d-a748-0a193c0f0824
		summarizeBy: none
		sourceColumn: L52W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Year Week Number - Text Format.
	column WM_YR_WK_TXT
		dataType: string
		lineageTag: 1292e7a5-8c8f-4e5a-b3aa-a1f8115a7342
		summarizeBy: none
		sourceColumn: WM_YR_WK_TXT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'WM Master - Calendar Week Pre Relay' = m
		mode: import
		queryGroup: 'Reporting - Master Data'
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    SILVER_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WALMART_CALENDAR_VIEW = SILVER_Schema{[Name="WM_CALENDAR_WEEK_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WALMART_CALENDAR_VIEW,{{"WM_YR_WK_NBR", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "WM_YR_WK_NBR", "WM_YR_WK_TXT"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"WM_YR_WK_TXT", type text}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

