/// Provides information about all scheduled store fulfillment orders at Walmart item, store and week level.
/// All metrics are aggregated at Walmart Week Level.
/// 
/// Source: WM_STORE_FULFILMENT_WEEK_VIEW
table WM_STORE_FULFILLMENT_WEEKLY
	isHidden
	lineageTag: 2e769c4b-752d-455a-90b5-be2e92ae1fd5

	/// Universal Product Code Number
	column WM_UPC_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a0eee5a1-64f2-4be8-a5fa-8c00c8fcfa62
		summarizeBy: none
		sourceColumn: WM_UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Store Number
	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 55a707cc-314e-4f77-8d95-0e356be1d212
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Year Week Number.
	/// A number representing the full Walmart year and week.
	column WM_YR_WK_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 473e190d-8520-4449-9dad-84dbc927d8fc
		summarizeBy: none
		sourceColumn: WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// This Year Nil Pick Units.
	column TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: a6cdfe4d-1371-4706-b6a5-0850976e1cdc
		summarizeBy: sum
		sourceColumn: TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: d70e9c84-72eb-4085-81fe-e56be6d0b0a8
		summarizeBy: sum
		sourceColumn: LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate Numerator.
	column TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 0526a0a2-8a3b-4f53-93f1-8da56bd9ee23
		summarizeBy: sum
		sourceColumn: TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 014f8597-f99f-44c5-9bac-49147c3e2202
		summarizeBy: sum
		sourceColumn: LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate Denominator.
	column TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: b1b22a85-779e-4491-8ba2-2bc240b53656
		summarizeBy: sum
		sourceColumn: TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: cbfa3b81-56b8-4391-80c7-fba4ad6f252b
		summarizeBy: sum
		sourceColumn: LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year First Time Pick Rate Numerator.
	column TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 406f1fa5-43f1-4b9a-ba4a-92d0ac8f7d47
		summarizeBy: sum
		sourceColumn: TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// First Time Pick Rate Numerator.
	column LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 5761637b-dfb1-4ec8-9345-382ee3b8280b
		summarizeBy: sum
		sourceColumn: LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year First Time Pick Rate Denominator.
	column TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 689f5cef-5cd8-42b8-ae77-74c83cadc7e3
		summarizeBy: sum
		sourceColumn: TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	///  Last Year First Time Pick Rate Denominator.
	column LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 8a51942f-9b29-4568-ba21-fcaa9ee0c035
		summarizeBy: sum
		sourceColumn: LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total Capacity Quantity.
	/// This is the sum of the total capacity of a product on a specific MODULAR PLANOGRAM.
	column TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: dc7ef29c-0605-4cf0-8a33-d3e250fc07dd
		summarizeBy: sum
		sourceColumn: TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 7350d7c8-8896-4eed-961e-3f412bf5cc0b
		summarizeBy: sum
		sourceColumn: TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: f59577cc-caaa-4685-b41a-c8def015593e
		summarizeBy: sum
		sourceColumn: LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: d8c7078e-cf8c-4144-95fa-cf6db95e231f
		summarizeBy: sum
		sourceColumn: TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 2f41748b-f61e-4164-9807-333b76cde2ca
		summarizeBy: sum
		sourceColumn: LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 07a4290a-d40f-413a-9bcb-c1f4182b1831
		summarizeBy: sum
		sourceColumn: TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: b5eabe3c-8816-4181-927f-e78f2522f7ba
		summarizeBy: sum
		sourceColumn: LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: b79749d9-d994-4a7e-96fa-fa8dacd39989
		summarizeBy: sum
		sourceColumn: TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 3fb10439-4868-43ac-b541-1d569ce7323f
		summarizeBy: sum
		sourceColumn: LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: e0d92c96-b31f-4a61-a772-6e6ddb5649b6
		summarizeBy: sum
		sourceColumn: TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: a428f1e4-e139-4f05-8adc-1b75c44b9a25
		summarizeBy: sum
		sourceColumn: LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Walmart Week Number
	column CAL_WM_WK_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 60ceb1f2-0fc4-4080-ae90-7c429e7e1105
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// In Modular Flag indicating the UPC is included in the store planogram for the week
	column IN_MODULAR
		dataType: string
		isHidden
		lineageTag: 96dd5fb2-954f-4ab3-a52f-1a536eb569f1
		summarizeBy: none
		sourceColumn: IN_MODULAR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Trait Number: This is the Main Placement or Combo Mod Trait Number at the Store
	column TRAIT_NBR
		dataType: double
		isHidden
		lineageTag: edf518e9-ee63-4182-b787-22459cd602e2
		summarizeBy: none
		sourceColumn: TRAIT_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition WM_STORE_FULFILLMENT_WEEKLY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_SALES_V_TRIMMED_View = GOLD_Schema{[Name="WM_STORE_FULFILMENT_WEEK_104W_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WM_SALES_V_TRIMMED_View,{{"WM_UPC_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}, {"WM_YR_WK_NBR", Int64.Type}, {"CAL_WM_WK_NBR", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

