/// Provides information about all scheduled store fulfillment orders at Walmart UPC and store level.
/// 
/// This model provides the metrics aggregated at different Time Frames:
/// - LW Last Week
/// - L4W Last 4 Weeks
/// - L13W Last 13 Weeks
/// - L52W Last 52 Weeks
/// - FYTD Walmart Fiscal Year to Date
/// - CW Current Week
/// 
/// Source: WM_STORE_FULFILMENT_TRIMMED_VIEW
table WM_STORE_FULFILLMENT_TIMEFRAMES
	isHidden
	lineageTag: 41865303-4cae-4749-9d7c-aa4fb02e904e

	/// WM Store Number
	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0dcdb074-bd31-4669-a925-2f9d4c270e42
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last 4 Weeks - This Year Nil Pick Units.
	column L4W_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 4e3ee795-f3ca-43b1-b943-713930f5901c
		summarizeBy: sum
		sourceColumn: L4W_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Nil Pick Units.
	column L13W_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: f4086cb2-b0a7-428b-9d0a-b6e30039981c
		summarizeBy: sum
		sourceColumn: L13W_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Nil Pick Units.
	column LW_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: fd3b8b43-3f87-4f1e-82f0-8052e151e287
		summarizeBy: sum
		sourceColumn: LW_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Nil Pick Units.
	column L52W_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 0fd1548e-a511-45a2-a053-cc7e2ad9d25a
		summarizeBy: sum
		sourceColumn: L52W_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Nil Pick Units.
	column FYTD_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 6ffa82c7-0318-4618-a011-a8f767c85617
		summarizeBy: sum
		sourceColumn: FYTD_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year Nil Pick Units.
	column CW_TY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: a4cc3d23-19bb-4617-be7f-a550a7da48c4
		summarizeBy: sum
		sourceColumn: CW_TY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Nil Pick Units.
	column L4W_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 79455e01-c851-47b3-912d-63d45a81d18c
		summarizeBy: sum
		sourceColumn: L4W_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Nil Pick Units.
	column L13W_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 3b6651ec-03ca-473c-8f96-5fee756c3751
		summarizeBy: sum
		sourceColumn: L13W_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Nil Pick Units.
	column LW_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: f877aea9-943d-46e9-af75-8a83984fb55d
		summarizeBy: sum
		sourceColumn: LW_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Nil Pick Units.
	column L52W_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 13d007a7-9977-482d-9a15-23a6911d25a8
		summarizeBy: sum
		sourceColumn: L52W_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year To Date - Last Year Nil Pick Units.
	column FYTD_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 590ed1b0-0322-4285-a7f6-57610c2b3b2f
		summarizeBy: sum
		sourceColumn: FYTD_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Nil Pick Units.
	column CW_LY_NIL_PICK_QTY
		dataType: double
		isHidden
		lineageTag: 3f5be081-6f06-4399-95ed-3522d0bbc9b0
		summarizeBy: sum
		sourceColumn: CW_LY_NIL_PICK_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year Nil Pick Rate Numerator.
	column L4W_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: eaf7ae69-bf98-412d-8d95-d61b9819d644
		summarizeBy: sum
		sourceColumn: L4W_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Nil Pick Rate Numerator.
	column L13W_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 1785d394-2042-44de-b2b6-691bb6c828aa
		summarizeBy: sum
		sourceColumn: L13W_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Nil Pick Rate Numerator.
	column LW_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 18e0d63d-5226-490d-984d-00cc4cf1fe98
		summarizeBy: sum
		sourceColumn: LW_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Nil Pick Rate Numerator.
	column L52W_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 9724fda4-5376-4092-a9fc-febd4b094049
		summarizeBy: sum
		sourceColumn: L52W_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Nil Pick Rate Numerator.
	column FYTD_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: bdae0569-e6f5-4f9d-b242-e5e8d46dcc2c
		summarizeBy: sum
		sourceColumn: FYTD_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year Nil Pick Rate Numerator.
	column CW_TY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: ee974c78-323a-4d79-a891-596501fa5870
		summarizeBy: sum
		sourceColumn: CW_TY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Nil Pick Rate Numerator.
	column L4W_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: f3977f8f-ed3f-4972-a8b1-a0f81cb5c034
		summarizeBy: sum
		sourceColumn: L4W_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Nil Pick Rate Numerator.
	column L13W_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 8ac4d2eb-ac8b-4e53-8daf-a74d0e2b1f92
		summarizeBy: sum
		sourceColumn: L13W_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Nil Pick Rate Numerator.
	column LW_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 509ac88e-a91b-4966-b316-aec1525601bb
		summarizeBy: sum
		sourceColumn: LW_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Nil Pick Rate Numerator.
	column L52W_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 5c5c4997-6c57-434c-b1b6-e8f7ff710244
		summarizeBy: sum
		sourceColumn: L52W_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year Nil Pick Rate Numerator.
	column FYTD_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 3e28bec2-fb78-4d84-9a27-62bb6b6d7509
		summarizeBy: sum
		sourceColumn: FYTD_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Nil Pick Rate Numerator.
	column CW_LY_NIL_PICK_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 48938988-3b88-404d-ab5c-7a57e025d275
		summarizeBy: sum
		sourceColumn: CW_LY_NIL_PICK_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year Nil Pick Rate Denominator.
	column L4W_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 2b3463ff-6757-492c-9693-fd75694bb338
		summarizeBy: sum
		sourceColumn: L4W_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Nil Pick Rate Denominator.
	column L13W_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 044cae13-a526-478d-9555-d34275e93d7b
		summarizeBy: sum
		sourceColumn: L13W_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Nil Pick Rate Denominator.
	column LW_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: db97ff10-7e86-4936-aa1e-3b40a3a35cf7
		summarizeBy: sum
		sourceColumn: LW_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Nil Pick Rate Denominator.
	column L52W_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 30e44f63-f7de-4b4d-ba04-e0e17275d977
		summarizeBy: sum
		sourceColumn: L52W_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Nil Pick Rate Denominator.
	column FYTD_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: ec43a43d-5ab9-4ce2-8414-fc072ea13f14
		summarizeBy: sum
		sourceColumn: FYTD_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year Nil Pick Rate Denominator.
	column CW_TY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 3bbe32fc-70a6-4950-93f7-ee6c1482bde5
		summarizeBy: sum
		sourceColumn: CW_TY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Nil Pick Rate Denominator.
	column L4W_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: a369f57f-4f54-4530-842f-612f72964679
		summarizeBy: sum
		sourceColumn: L4W_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Nil Pick Rate Denominator.
	column L13W_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 0b2c98b4-4794-4483-b759-19e8ddfdc5de
		summarizeBy: sum
		sourceColumn: L13W_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Nil Pick Rate Denominator.
	column LW_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 4d3909ab-f47b-4183-90f4-e6c82f134cfc
		summarizeBy: sum
		sourceColumn: LW_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Nil Pick Rate Denominator.
	column L52W_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 1025845a-f9dc-4422-baa1-2d132b40c32f
		summarizeBy: sum
		sourceColumn: L52W_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year Nil Pick Rate Denominator.
	column FYTD_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 4a5b59a0-b4a9-4341-b99b-93aedb049279
		summarizeBy: sum
		sourceColumn: FYTD_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Nil Pick Rate Denominator.
	column CW_LY_NIL_PICK_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 9186820e-6dd2-45ea-a32b-15c2c6eded08
		summarizeBy: sum
		sourceColumn: CW_LY_NIL_PICK_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year First Time Pick Rate Numerator.
	column L4W_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 15763578-b7ab-487d-88a5-e9048d30eba6
		summarizeBy: sum
		sourceColumn: L4W_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year First Time Pick Rate Numerator.
	column L13W_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: eaeb987e-575a-4820-85cf-1434eb0309c6
		summarizeBy: sum
		sourceColumn: L13W_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year First Time Pick Rate Numerator.
	column LW_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 40c5d0bd-b821-4b7f-93c3-97756e3a63c1
		summarizeBy: sum
		sourceColumn: LW_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year First Time Pick Rate Numerator.
	column L52W_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 3f08f000-17cd-4147-bcad-52943629e6de
		summarizeBy: sum
		sourceColumn: L52W_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year To Date - This Year First Time Pick Rate Numerator.
	column FYTD_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: dff2e073-225b-4aa5-b814-cf37a9b41b3e
		summarizeBy: sum
		sourceColumn: FYTD_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year First Time Pick Rate Numerator.
	column CW_TY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 6a7f574c-a181-49e9-8138-e243a8796eba
		summarizeBy: sum
		sourceColumn: CW_TY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year First Time Pick Rate Numerator.
	column L4W_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: abd81999-118b-4a58-a991-c3e6a15e53cb
		summarizeBy: sum
		sourceColumn: L4W_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year First Time Pick Rate Numerator.
	column L13W_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 06b86c81-12ed-40e4-86d8-276d2bbce596
		summarizeBy: sum
		sourceColumn: L13W_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year First Time Pick Rate Numerator.
	column LW_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: bc771196-08d6-4143-93bb-943512382e4a
		summarizeBy: sum
		sourceColumn: LW_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year First Time Pick Rate Numerator.
	column L52W_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: e4eecffd-250c-4e13-89ef-f0d68542ba44
		summarizeBy: sum
		sourceColumn: L52W_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year First Time Pick Rate Numerator.
	column FYTD_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 513cb070-7d34-40b6-baa1-b360cf315039
		summarizeBy: sum
		sourceColumn: FYTD_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year First Time Pick Rate Numerator.
	column CW_LY_FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 02d46e02-0ce8-41c1-9737-884f3f0cc2a1
		summarizeBy: sum
		sourceColumn: CW_LY_FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year First Time Pick Rate Denominator.
	column L4W_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 0e9a3c78-4244-426f-9704-924777615292
		summarizeBy: sum
		sourceColumn: L4W_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year First Time Pick Rate Denominator.
	column L13W_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 94a455a1-192a-4e48-8904-c3c14848d65b
		summarizeBy: sum
		sourceColumn: L13W_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year First Time Pick Rate Denominator.
	column LW_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 28f83ac0-3201-4e0e-ac34-b108563a3b92
		summarizeBy: sum
		sourceColumn: LW_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year First Time Pick Rate Denominator.
	column L52W_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 406b3671-1d64-42b5-baba-b0edb36e5eb8
		summarizeBy: sum
		sourceColumn: L52W_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year To Date - This Year First Time Pick Rate Denominator.
	column FYTD_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: af0fb494-d410-4c1f-9921-3c260f85cb54
		summarizeBy: sum
		sourceColumn: FYTD_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year First Time Pick Rate Denominator.
	column CW_TY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: dc8798b8-fd86-45ac-a59a-e0dd9a4a5655
		summarizeBy: sum
		sourceColumn: CW_TY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year First Time Pick Rate Denominator.
	column L4W_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 54da7464-8bda-41ad-ad0b-97b252517202
		summarizeBy: sum
		sourceColumn: L4W_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year First Time Pick Rate Denominator.
	column L13W_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: f5950c00-c7fa-4cc2-b9e5-e3be061b3d7d
		summarizeBy: sum
		sourceColumn: L13W_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year First Time Pick Rate Denominator.
	column LW_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 06230413-d7cb-4d30-8148-336f46cc7963
		summarizeBy: sum
		sourceColumn: LW_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year First Time Pick Rate Denominator.
	column L52W_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 715ff2c6-9d4c-4871-b6df-aac5a43793e0
		summarizeBy: sum
		sourceColumn: L52W_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date Last Year First Time Pick Rate Denominator.
	column FYTD_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: fa7fa627-2569-4a85-bb5c-8f9dd8acd3df
		summarizeBy: sum
		sourceColumn: FYTD_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year First Time Pick Rate Denominator.
	column CW_LY_FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 5f4ee881-9047-4e5d-9032-8ce96fc1eb13
		summarizeBy: sum
		sourceColumn: CW_LY_FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column L4W_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: 04274ea8-18b2-4cc0-bc46-c123d4f485fa
		summarizeBy: sum
		sourceColumn: L4W_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column L13W_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: b836bf38-226e-426a-9454-b520dc7479d3
		summarizeBy: sum
		sourceColumn: L13W_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column LW_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: ee7e6066-23f0-4003-adfd-4bce97fbf136
		summarizeBy: sum
		sourceColumn: LW_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column L52W_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: f4016eea-f13d-41eb-8cae-d18ab24e8376
		summarizeBy: sum
		sourceColumn: L52W_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column FYTD_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: 15a60df6-f022-4629-86b5-ca7b94d0dbd3
		summarizeBy: sum
		sourceColumn: FYTD_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// DO NOT USE: TO BE DELETED.
	/// 
	column CW_TOT_CPCTY_QTY
		dataType: double
		isHidden
		lineageTag: 7fb7fe97-53e2-4290-8f85-acd76b30051b
		summarizeBy: sum
		sourceColumn: CW_TOT_CPCTY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 78106c68-8400-43b3-9176-6c3a29271f2b
		summarizeBy: sum
		sourceColumn: L4W_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 2acc29f5-e403-4fea-a207-d9f9816d1b9e
		summarizeBy: sum
		sourceColumn: L13W_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 704841a5-8333-40c4-9aaa-afd426f31943
		summarizeBy: sum
		sourceColumn: LW_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: dd8c03f6-aab3-4657-b3b7-da5629d60fce
		summarizeBy: sum
		sourceColumn: L52W_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 52cfaf7d-a831-4c21-bb9b-7b41b999c7d3
		summarizeBy: sum
		sourceColumn: FYTD_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CW_TY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 9d7b1472-4568-4fe0-945a-fca910199a51
		summarizeBy: sum
		sourceColumn: CW_TY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 2568aafa-90bf-40d3-94c5-83a4a549e2f5
		summarizeBy: sum
		sourceColumn: L4W_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: c6c58c48-f05d-466a-b2f4-49f76ab08d87
		summarizeBy: sum
		sourceColumn: L13W_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 4aadc9c4-e4da-406d-921a-8cc6d2ef29b5
		summarizeBy: sum
		sourceColumn: LW_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 14279d4a-642f-4782-aa21-9ff12a49f876
		summarizeBy: sum
		sourceColumn: L52W_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: ef044afc-ef4e-4e8c-aef0-7a1055d6ba7e
		summarizeBy: sum
		sourceColumn: FYTD_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Pre Sub Units.
	column CW_LY_PRESUB_QTY
		dataType: double
		isHidden
		lineageTag: 834a6fac-e8b1-48bf-9ae1-4c9251bc7369
		summarizeBy: sum
		sourceColumn: CW_LY_PRESUB_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 7e4921b1-4d45-4374-b810-6e5ccee6af11
		summarizeBy: sum
		sourceColumn: L4W_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 4f928780-51dc-452c-b558-33239cd05d4b
		summarizeBy: sum
		sourceColumn: L13W_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 7caa676b-cac4-43c2-b41c-93650523432d
		summarizeBy: sum
		sourceColumn: LW_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: cb3331d4-bb5f-40f6-a541-4ede3ce2e55f
		summarizeBy: sum
		sourceColumn: L52W_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 3525ec07-bf9d-49b0-b34d-3035220c3d00
		summarizeBy: sum
		sourceColumn: FYTD_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CW_TY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 40ef7beb-e8ad-4998-9dcd-21c808496077
		summarizeBy: sum
		sourceColumn: CW_TY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 6ea57a6d-093c-4730-8053-e7b9a6be609a
		summarizeBy: sum
		sourceColumn: L4W_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 10d7fe07-66d6-4170-b111-d81151ba45d6
		summarizeBy: sum
		sourceColumn: L13W_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 3144abed-cd2f-4b6b-b99b-07ba5f6b21d1
		summarizeBy: sum
		sourceColumn: LW_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 51bf3641-ee76-4217-bbc6-896a411a796f
		summarizeBy: sum
		sourceColumn: L52W_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: d959a634-445c-467d-90fe-9e2fa4697f73
		summarizeBy: sum
		sourceColumn: FYTD_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Pre Sub Rate Denominator.
	column CW_LY_PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 0a7ca99c-9b7f-4011-ad6f-37f04fc5732d
		summarizeBy: sum
		sourceColumn: CW_LY_PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 7f3410a6-46f9-461b-b3f6-dcfd01d7831a
		summarizeBy: sum
		sourceColumn: L4W_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: f42c5907-aa9c-4058-9331-996f6f364678
		summarizeBy: sum
		sourceColumn: L13W_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: ebe5febd-73d2-4a34-ab0f-52a0611ed8b5
		summarizeBy: sum
		sourceColumn: LW_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 608e332b-832b-4738-b085-02732dfbac07
		summarizeBy: sum
		sourceColumn: L52W_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: da98dfdf-3aa8-4c45-97d1-2de72df1052b
		summarizeBy: sum
		sourceColumn: FYTD_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CW_TY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: fad2ad5f-a7c0-443b-bb03-b51e983420ee
		summarizeBy: sum
		sourceColumn: CW_TY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: e9a60750-be0f-46d9-aeef-675629d1220d
		summarizeBy: sum
		sourceColumn: L4W_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 2a493e3d-eacb-46b5-ad04-4f4fd9f6aaf2
		summarizeBy: sum
		sourceColumn: L13W_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 550d918e-7ff8-4a8e-9a16-d14bdb57c38e
		summarizeBy: sum
		sourceColumn: LW_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: a782c028-72b9-4a25-8b07-7c0cb4972a75
		summarizeBy: sum
		sourceColumn: L52W_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 9f2ca279-d34e-4f14-8c63-f5492ca385f6
		summarizeBy: sum
		sourceColumn: FYTD_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Pre Sub Rate Numerator.
	column CW_LY_PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 2484475b-0cd5-4123-8910-7a533c482e89
		summarizeBy: sum
		sourceColumn: CW_LY_PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 43b31ac3-4e9b-47ea-8105-047625061bee
		summarizeBy: sum
		sourceColumn: L4W_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: a715aa32-236d-40dc-ba72-a08551fd0100
		summarizeBy: sum
		sourceColumn: L13W_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 82e86df0-7bfa-4cd0-a3df-5bb0437eab08
		summarizeBy: sum
		sourceColumn: LW_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 430d4b09-f8b1-4666-9f50-6729ca22d7f5
		summarizeBy: sum
		sourceColumn: L52W_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: c281e9d5-7f9b-4bb1-b097-4af32b477804
		summarizeBy: sum
		sourceColumn: FYTD_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CW_TY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 005ef4d5-a2ae-404d-a5fb-6789475366fd
		summarizeBy: sum
		sourceColumn: CW_TY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 5ad91e39-5aed-4e6f-a580-7b730b140a85
		summarizeBy: sum
		sourceColumn: L4W_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: fa7780ab-e671-47c5-b83d-0fef23b6b801
		summarizeBy: sum
		sourceColumn: L13W_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 92cab13a-9ccc-4daa-a0e1-b527265998df
		summarizeBy: sum
		sourceColumn: LW_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 2de33301-f1bf-4c53-8d4e-43a137246380
		summarizeBy: sum
		sourceColumn: L52W_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: b1e232fb-c109-434e-923f-29b01bcf0c37
		summarizeBy: sum
		sourceColumn: FYTD_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Post Sub Rate Denominator.
	column CW_LY_POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: 8b920756-bd15-4a79-9ba3-20bf32710be5
		summarizeBy: sum
		sourceColumn: CW_LY_POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 3a624be7-ea85-47da-afde-e84084023752
		summarizeBy: sum
		sourceColumn: L4W_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 1ef92d21-7b38-44e1-afd4-d3e1254feb88
		summarizeBy: sum
		sourceColumn: L13W_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 266cbd34-5e6a-4a6a-a9f2-ef47c31d5a71
		summarizeBy: sum
		sourceColumn: LW_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: cf9f08b0-bd7f-43bd-b8c2-8c5acd8efd11
		summarizeBy: sum
		sourceColumn: L52W_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 2f2e432f-af71-4303-a8ce-a941e1751dd6
		summarizeBy: sum
		sourceColumn: FYTD_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CW_TY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 3dfb2e6b-8c7b-42bc-ad6b-c15fa47feff6
		summarizeBy: sum
		sourceColumn: CW_TY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L4W_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: e5b2a071-97e9-4eab-9efe-aacea0d635ed
		summarizeBy: sum
		sourceColumn: L4W_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L13W_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 1d519a36-3a3e-456c-96ff-14b30a234f17
		summarizeBy: sum
		sourceColumn: L13W_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LW_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 577bb925-1fd9-4c59-8158-808a81ab7343
		summarizeBy: sum
		sourceColumn: LW_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 8003a2fc-c58b-40ec-8357-39c80048de52
		summarizeBy: sum
		sourceColumn: L52W_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYTD_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 1cf3088a-c408-41d1-bcb1-11500d190656
		summarizeBy: sum
		sourceColumn: FYTD_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Post Sub Rate Numerator.
	column CW_LY_POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: de2af721-4171-4b34-aea1-fdbafaff2bac
		summarizeBy: sum
		sourceColumn: CW_LY_POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year Nil Pick Amount.
	column L4W_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 4bd2a3ed-63ea-416c-a9d6-490b7b88f68d
		summarizeBy: sum
		sourceColumn: L4W_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Nil Pick Amount.
	column L13W_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: a82e8a2e-4d8b-41b1-9a32-825c458ad26e
		summarizeBy: sum
		sourceColumn: L13W_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Nil Pick Amount.
	column LW_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 8efa3212-8b10-4e48-9c58-7a6584ebebbf
		summarizeBy: sum
		sourceColumn: LW_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Nil Pick Amount.
	column L52W_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 79bd17d9-7619-46bb-927d-f24cd10c9fc7
		summarizeBy: sum
		sourceColumn: L52W_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Nil Pick Amount.
	column FYTD_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 61234475-84b6-496a-9549-d3e7b2097f93
		summarizeBy: sum
		sourceColumn: FYTD_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year Nil Pick Amount.
	column CW_TY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 2bc27857-e019-48fb-9d17-0fdb4ca64928
		summarizeBy: sum
		sourceColumn: CW_TY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Nil Pick Amount.
	column L4W_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: e9680457-6941-45bc-8755-d9b25c6da5b1
		summarizeBy: sum
		sourceColumn: L4W_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Nil Pick Amount.
	column L13W_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: fd0862b8-8f00-4f05-a09d-b48b7688ebc0
		summarizeBy: sum
		sourceColumn: L13W_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Nil Pick Amount.
	column LW_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 7ebf7d4b-8bd4-4900-9c8e-6136f59d3b95
		summarizeBy: sum
		sourceColumn: LW_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Nil Pick Amount.
	column L52W_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: e0345662-dd64-4fd2-a0b1-b3979bc5ea5b
		summarizeBy: sum
		sourceColumn: L52W_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year Nil Pick Amount.
	column FYTD_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 26bafe64-1bff-49f8-9c0a-1a9736ee3074
		summarizeBy: sum
		sourceColumn: FYTD_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week Last Year Nil Pick Amount.
	column CW_LY_NIL_PICK_AMOUNT
		dataType: double
		isHidden
		lineageTag: 599cae47-dfd0-4e1f-a550-607b55a72700
		summarizeBy: sum
		sourceColumn: CW_LY_NIL_PICK_AMOUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last updated date.
	column BUS_DT
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 943509c3-30a4-4955-b934-75d80e789ed3
		summarizeBy: none
		sourceColumn: BUS_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Walmart Week Number
	column CAL_WM_WK_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a4e4750a-32a0-4beb-8674-b286ca4e848b
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CAL_WM_WK_DAY_NBR
		dataType: double
		isHidden
		lineageTag: 288c825b-efbf-4ecc-bfc2-0dda3dddbe9e
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_DAY_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Universal Product Code Number
	column WM_UPC_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6df13c6a-706c-4a7c-af3d-ae29ff8e786e
		summarizeBy: none
		sourceColumn: WM_UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition WM_STORE_FULFILLMENT_TIMEFRAMES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_SALES_V_TRIMMED_View = GOLD_Schema{[Name="WM_STORE_FULFILMENT_TRIMMED_VIEW",Kind="View"]}[Data],
				    #"RowsToReturn" = if #"pLoadAllRecords" then WM_SALES_V_TRIMMED_View else WM_SALES_V_TRIMMED_View,
				    #"Changed Type" = Table.TransformColumnTypes(RowsToReturn,{{"WM_UPC_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"CAL_WM_FULL_YR_NBR", "CAL_WM_MTH_NBR", "CAL_WM_MTH_NM", "CAL_WM_WK_NM", "CAL_WM_YR_WK_NBR"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"CAL_WM_WK_NBR", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

