/// The Store Item UPC Measures view provides information about Inventory at the store level; several types of metrics across in-stock inventory; and markup, markdown, and margins on an item, store, and day grain.
/// This model provides the metrics aggregated at different Time Frames:
/// - LW Last Week
/// - L4W Last 4 Weeks
/// - L13W Last 13 Weeks
/// - L52W Last 52 Weeks
/// - FYTD Walmart Fiscal Year to Date
/// - CW Current Week
/// 
/// Source: WM_STORE_ITEM_UPC_TRIMMED_VIEW
table WM_STORE_ITEM_UPC_TIMEFRAMES
	isHidden
	lineageTag: e98a1af9-4572-423d-8018-15806638b02e

	/// WM Store Number
	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d623d961-8c12-43ea-820f-6c7c824ff52d
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Average on hand Qty for this Time Period.
	column L4W_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: dd985a85-5c0d-4a56-bbaa-9e672a57a945
		summarizeBy: sum
		sourceColumn: L4W_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average on hand Qty for this Time Period.
	column L13W_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 2abb1923-e413-47b3-9fba-2052fee48210
		summarizeBy: sum
		sourceColumn: L13W_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average on hand Qty for this Time Period.
	column LW_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 43d56f9b-2eed-4c83-89cd-cc35246e03bd
		summarizeBy: sum
		sourceColumn: LW_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average on hand Qty for this Time Period.
	column L52W_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 3fbebb23-b383-49ad-8c4c-8b2254046261
		summarizeBy: sum
		sourceColumn: L52W_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average on hand Qty for this Time Period.
	column FYTD_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 38bea50b-af59-49b2-8671-ad8fe56aa8b1
		summarizeBy: sum
		sourceColumn: FYTD_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average on hand Qty for this Time Period.
	column CW_TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: d081775b-0354-455b-a736-4b97cb721068
		summarizeBy: sum
		sourceColumn: CW_TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column L4W_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: b92b428a-4629-4cd0-9076-a5f72671830c
		summarizeBy: sum
		sourceColumn: L4W_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column L13W_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: 3b1268de-eb80-4ecf-bb38-12a1ab2906c3
		summarizeBy: sum
		sourceColumn: L13W_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column LW_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: fc146ca2-d7ed-4ed0-991e-aeddc8f8a29a
		summarizeBy: sum
		sourceColumn: LW_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column L52W_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: 4107518e-bbcc-49d8-80ed-63aeef816cb6
		summarizeBy: sum
		sourceColumn: L52W_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column FYTD_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: ad3428b9-4b3f-4cdc-a6e1-1c5d19144335
		summarizeBy: sum
		sourceColumn: FYTD_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of days UPC was Out of Stock in that Store/TimeFrame.
	column CW_OUT_OF_STOCK
		dataType: double
		isHidden
		lineageTag: 65734ef1-0a22-48ac-b6d0-5cd897767606
		summarizeBy: sum
		sourceColumn: CW_OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column L4W_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: 107891bd-88a6-493a-a4dc-b200710f6e7c
		summarizeBy: sum
		sourceColumn: L4W_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column L13W_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: bf696d06-f9ad-4a0f-936c-9241bc3453f7
		summarizeBy: sum
		sourceColumn: L13W_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column L52W_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: 1634018d-49d4-462f-a418-91a0abb53d4a
		summarizeBy: sum
		sourceColumn: L52W_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column LW_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: a745e012-8f46-4205-a378-5617ed371fac
		summarizeBy: sum
		sourceColumn: LW_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column FYTD_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: 0cedda26-5ab0-4758-bfdb-c4b815bafbac
		summarizeBy: sum
		sourceColumn: FYTD_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Store UPC combination on the period. 
	/// Count of Store UPC combination on the period, used for Average calculation metrics.
	column CW_STORE_ITEM_COUNT
		dataType: double
		isHidden
		lineageTag: 8a98590c-5f5b-48f4-896e-e386bb6b08f7
		summarizeBy: sum
		sourceColumn: CW_STORE_ITEM_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last updated date.
	column BUS_DT
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 3b8d624c-ce33-4bcd-b6c6-f71e93de3f74
		summarizeBy: none
		sourceColumn: BUS_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Walmart Week Number
	column CAL_WM_WK_NBR
		dataType: double
		isHidden
		lineageTag: 3fc83f16-be84-4216-b711-3d00fd2dda4a
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAL_WM_WK_DAY_NBR
		dataType: double
		isHidden
		lineageTag: 3acf410a-1789-49a6-a0d8-c6b426d3462a
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_DAY_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Universal Product Code Number
	column WM_UPC_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d29d31ba-4fd6-4678-b046-dec41b700a38
		summarizeBy: none
		sourceColumn: WM_UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// On Hand Qty on the Start of the Time Period.
	column L4W_TY_START_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 857a48af-4280-4070-9cee-b51721dcbb31
		summarizeBy: sum
		sourceColumn: L4W_TY_START_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the Start of the Time Period.
	column L13W_TY_START_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: c8d32b2b-8ab6-4aa0-b33e-9d8f5d41ed65
		summarizeBy: sum
		sourceColumn: L13W_TY_START_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the Start of the Time Period.
	column LW_TY_START_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 1521ff76-7035-4225-81a7-7ab842d1f4f3
		summarizeBy: sum
		sourceColumn: LW_TY_START_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the Start of the Time Period.
	column L52W_TY_START_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: b780d17f-e8eb-486f-b96d-168d98648953
		summarizeBy: sum
		sourceColumn: L52W_TY_START_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the Start of the Time Period.
	column FYTD_TY_START_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 9de80cab-bf9d-4a86-a806-fe5ba6c65e3a
		summarizeBy: sum
		sourceColumn: FYTD_TY_START_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the end of Time Period.
	column L4W_TY_END_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: a68faafd-cd70-45e8-9f17-b5bd849ef180
		summarizeBy: sum
		sourceColumn: L4W_TY_END_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the end of Time Period.
	column L13W_TY_END_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 34399515-b1b6-4f15-852e-a56b572e4ad0
		summarizeBy: sum
		sourceColumn: L13W_TY_END_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the end of Time Period.
	column LW_TY_END_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 08d795a2-9acb-4ebc-bd7f-9c41780516e5
		summarizeBy: sum
		sourceColumn: LW_TY_END_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column L52W_TY_END_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: ae5eeb95-fd6c-4401-a069-fd43a0045187
		summarizeBy: sum
		sourceColumn: L52W_TY_END_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// On Hand Qty on the end of Time Period.
	column FYTD_TY_END_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: e3fd5b64-7d26-44de-a58b-c25f11c2ec04
		summarizeBy: sum
		sourceColumn: FYTD_TY_END_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column L4W_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: 649d6036-e322-4b75-95e0-6596f2bdb02c
		summarizeBy: sum
		sourceColumn: L4W_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column L13W_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: 1aa78282-eb12-417a-a091-290cc82d96d6
		summarizeBy: sum
		sourceColumn: L13W_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column LW_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: ec599ef2-c2e0-478e-9d86-7af6fcca65f2
		summarizeBy: sum
		sourceColumn: LW_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column L52W_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: 1187ea13-a3d0-4c37-8207-65c8379b8c1d
		summarizeBy: sum
		sourceColumn: L52W_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column FYTD_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: da293ba0-2c44-4fed-bada-d935d9b14c18
		summarizeBy: sum
		sourceColumn: FYTD_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Net Receipt Quantity - This Year.
	column CW_TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: f3d8e250-4e26-4f79-a280-b999a652df99
		summarizeBy: sum
		sourceColumn: CW_TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition WM_STORE_ITEM_UPC_TIMEFRAMES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_SALES_V_TRIMMED_View = GOLD_Schema{[Name="WM_STORE_ITEM_UPC_TRIMMED_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WM_SALES_V_TRIMMED_View,{ {"STORE_NBR", Int64.Type}, {"CAL_WM_FULL_YR_NBR", Int64.Type}, {"CAL_WM_MTH_NBR", Int64.Type}, {"WM_UPC_NBR", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"CAL_WM_WK_NM", "CAL_WM_YR_WK_NBR", "CAL_WM_MTH_NM", "CAL_WM_FULL_YR_NBR", "CAL_WM_MTH_NBR"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

