/// Latest Store UPC Stock measures.
/// This model only returns the latest available date (Day - 2).
/// This will consider In Modular (Store Planogram) only records. 
/// 
/// Source: WM_STORE_ITEM_UPC_LATEST_VIEW
table WM_STORE_ITEM_UPC_LATEST
	isHidden
	lineageTag: 9d1b3dd6-4b90-48fd-b9c2-929a4ed118d8

	/// WM Store Number
	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ecbc4c83-2332-44c2-b5a1-ee38f24a207b
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Trait Number: This is the Main Placement or Combo Mod Trait Number at the Store
	column TRAIT
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8cbdaf68-44f5-4835-9666-bcaa2c91534d
		summarizeBy: sum
		sourceColumn: TRAIT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Universal Product Code Number
	column UPC_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a57593a4-cd34-4b9c-a9dc-b96b6211a7a1
		summarizeBy: none
		sourceColumn: UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Current on hand Qty for this week
	column TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 919d3c43-1824-4eef-b283-1dd6cf0f53bc
		summarizeBy: sum
		sourceColumn: TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Out of Stock Flag for Store UPC combination:
	/// 1 - Out of Stock
	/// 0 - No, there is stock
	column OUT_OF_STOCK
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aee9875c-f88a-41fb-92f6-53f0904bf983
		summarizeBy: sum
		sourceColumn: OUT_OF_STOCK

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Flag indicating this Store UPC exists also in WM StoreItem API data feed. 
	column STORE_ITEM_EXISTS
		dataType: string
		isHidden
		lineageTag: d62fdc91-60bc-4cdd-a119-2aaa04ff2a88
		summarizeBy: none
		sourceColumn: STORE_ITEM_EXISTS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition WM_STORE_ITEM_UPC_LATEST = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_SALES_V_TRIMMED_View = GOLD_Schema{[Name="WM_STORE_ITEM_UPC_LATEST_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WM_SALES_V_TRIMMED_View,{{"STORE_NBR", Int64.Type}, {"TRAIT", Int64.Type}, {"UPC_NBR", Int64.Type}, {"OUT_OF_STOCK", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

