/// Additional Time Frame View used only to compare two different periods.
/// Used for Pre Post Comparison analysis.
table 'WM Master - Pre Post Time Frame'
	lineageTag: 48cbab9d-6115-44b5-b264-539a3c56456e

	column 'Time Frame ID'
		dataType: string
		lineageTag: e2bccbf0-eab7-4b02-9606-cb1bf64b12f8
		summarizeBy: none
		sourceColumn: Time Frame ID
		sortByColumn: Order

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Time Frame'
		dataType: string
		lineageTag: 6df70000-cfe6-4f45-a4f7-45f3fed189e7
		summarizeBy: none
		sourceColumn: Time Frame
		sortByColumn: Order

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: string
		lineageTag: ddc0c225-63b1-4264-afac-462b3e56b4b4
		summarizeBy: none
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'WM Master - Pre Post Time Frame' = m
		mode: import
		queryGroup: 'Reporting - Master Data'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCjFU0lFyLi0qSs0rUQhKzUmsBPINlWJ1gFJGQGZAUWpZZn5pMVzOCCJnDGQ6JhUrOGekA1nGEEETIFMVKmSiFBsLAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Time Frame ID" = _t, #"Time Frame" = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Time Frame ID", type text}, {"Time Frame", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

