/// Walmart Category Sales model. 
/// UPC Sales (Shopper Behavior) view provides information about store and eComm sales at UPC and store level.
/// The UPC Store Sales endpoint will contain Store & Ecomm sales, aggregated weekly. Ecomm sales are reported under the store number “-999”. 
/// The sales number under the UPC Store Sales endpoint may not match with the sales number under our Store Sales endpoint.
/// This model is refreshed weekly on Mondays, resulting in a 9 to 15-day delay.
/// 
/// SOURCE: WM_UPC_SALES_VIEW
table WM_STORE_ITEM_DAILY
	isHidden
	lineageTag: b9344e60-26de-42e2-9fd4-6933b88d9dc8

	column WM_UPC_NBR
		dataType: double
		isHidden
		lineageTag: 314ecfcd-0669-40d9-a74b-d9e405d0edf9
		summarizeBy: none
		sourceColumn: WM_UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 108ce31a-3753-4d03-83de-370a736cba7c
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BUS_DT
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: fea9e26d-b916-459f-b1d9-16284abdf275
		summarizeBy: none
		sourceColumn: BUS_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VENDOR_NBR
		dataType: double
		isHidden
		lineageTag: 18df9a71-273d-4074-8351-aa4327ba9a23
		summarizeBy: sum
		sourceColumn: VENDOR_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VENDOR_NM
		dataType: string
		isHidden
		lineageTag: 752c058d-4d3d-4ee1-9ed5-bb79f05d9e49
		summarizeBy: none
		sourceColumn: VENDOR_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OP_CMPNY_CD
		dataType: string
		isHidden
		lineageTag: f2012ef9-5d28-4f72-af3e-b75ab99139fb
		summarizeBy: none
		sourceColumn: OP_CMPNY_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WM_YR_WK_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a5510c4f-224e-4e42-9e36-fb3bbdbbd447
		summarizeBy: sum
		sourceColumn: WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GEO_REGION_CD
		dataType: string
		isHidden
		lineageTag: 3dc90807-5f47-49dd-9c8c-b5a6e6b9a349
		summarizeBy: none
		sourceColumn: GEO_REGION_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CRNCY_CD
		dataType: string
		isHidden
		lineageTag: 1a7da83a-f8e1-4222-9647-5e7781973dfd
		summarizeBy: none
		sourceColumn: CRNCY_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OUT_OF_STOCK_FLAG
		dataType: string
		isHidden
		lineageTag: 2debeac7-66a7-4d51-967f-4953aa146df8
		summarizeBy: none
		sourceColumn: OUT_OF_STOCK_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TY_IN_TRNST_QTY
		dataType: double
		isHidden
		lineageTag: 19a6d45c-8458-4df5-9c46-b6c93a7e3f1d
		summarizeBy: sum
		sourceColumn: TY_IN_TRNST_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_IN_TRNST_RTL_AMT
		dataType: double
		isHidden
		lineageTag: df888561-1429-4429-9b70-4cd8a4d86409
		summarizeBy: sum
		sourceColumn: TY_IN_TRNST_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_IN_WHSE_QTY
		dataType: double
		isHidden
		lineageTag: 840e3324-49f3-424d-aff1-b60bc6e57d71
		summarizeBy: sum
		sourceColumn: TY_IN_WHSE_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_IN_WHSE_RTL_AMT
		dataType: double
		isHidden
		lineageTag: 1016a52c-eb45-4b62-84a7-8f38e3be304e
		summarizeBy: sum
		sourceColumn: TY_IN_WHSE_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_ON_HAND_QTY
		dataType: double
		isHidden
		lineageTag: 818c6f61-9956-40af-a9d5-c5432beee8c9
		summarizeBy: sum
		sourceColumn: TY_ON_HAND_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_ON_HAND_RTL_AMT
		dataType: double
		isHidden
		lineageTag: b368b3d9-afb6-4f75-9e01-1e9f0cc5d633
		summarizeBy: sum
		sourceColumn: TY_ON_HAND_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_ON_ORDER_QTY
		dataType: double
		isHidden
		lineageTag: 4901287e-56ac-462d-b130-ccba0fd5e7d1
		summarizeBy: sum
		sourceColumn: TY_ON_ORDER_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_ON_ORDER_RTL_AMT
		dataType: double
		isHidden
		lineageTag: d63c87e9-97d3-4bef-80cf-31b3c7d15077
		summarizeBy: sum
		sourceColumn: TY_ON_ORDER_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_PIPELINE_QTY
		dataType: double
		isHidden
		lineageTag: 4d00220e-baf5-4d16-8369-013d8530ee9a
		summarizeBy: sum
		sourceColumn: TY_PIPELINE_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_MKDN_QTY
		dataType: double
		isHidden
		lineageTag: d677c76a-5b3e-4055-bb84-b28ae4340b2c
		summarizeBy: sum
		sourceColumn: TY_MKDN_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_MKDN_AMT
		dataType: double
		isHidden
		lineageTag: 6d8e47a1-ed7f-41a2-90d8-1d677e109cfc
		summarizeBy: sum
		sourceColumn: TY_MKDN_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_REPL_INSTOCK_NUMERATOR
		dataType: double
		isHidden
		lineageTag: 518962fa-828e-4322-98c2-fc833b82cd06
		summarizeBy: sum
		sourceColumn: TY_REPL_INSTOCK_NUMERATOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_REPL_INSTOCK_DENOMINATOR
		dataType: double
		isHidden
		lineageTag: 5a11c92f-a3cd-4c1b-8239-837bd0afc313
		summarizeBy: sum
		sourceColumn: TY_REPL_INSTOCK_DENOMINATOR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BKRM_ADJ_QTY
		dataType: double
		isHidden
		lineageTag: 02c29312-aa39-437e-9b80-dd1533371e7a
		summarizeBy: sum
		sourceColumn: BKRM_ADJ_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BKRM_ADJ_RTL_AMT
		dataType: double
		isHidden
		lineageTag: f7e712a1-ccff-4d9b-a852-0a999227245a
		summarizeBy: sum
		sourceColumn: BKRM_ADJ_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_TRAITED_CNT
		dataType: double
		isHidden
		lineageTag: 452dd853-11cb-4d9c-afa9-5f37548477e8
		summarizeBy: sum
		sourceColumn: TY_TRAITED_CNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_NET_RCPT_RTL_AMT
		dataType: double
		isHidden
		lineageTag: 24f46377-f9ed-489c-9a7a-6ae370e144fd
		summarizeBy: sum
		sourceColumn: TY_NET_RCPT_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_NET_RCPT_COST_AMT
		dataType: double
		isHidden
		lineageTag: ac08be05-4057-421f-a12c-1d33c6a046bf
		summarizeBy: sum
		sourceColumn: TY_NET_RCPT_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_GROSS_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: 543fb3fd-9c46-4384-a56d-d6249f6fbd31
		summarizeBy: sum
		sourceColumn: TY_GROSS_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_NET_RCPT_QTY
		dataType: double
		isHidden
		lineageTag: 717fa832-91bf-4336-ab33-a609d308cfe1
		summarizeBy: sum
		sourceColumn: TY_NET_RCPT_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TY_REPL_STORE_ITEM_CNT
		dataType: double
		isHidden
		lineageTag: b8d61d0b-db61-4587-a926-ef5ac37f2d9a
		summarizeBy: sum
		sourceColumn: TY_REPL_STORE_ITEM_CNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_SPECIFIC_COST_AMT
		dataType: double
		isHidden
		lineageTag: 492cbff4-d5e6-4429-a97e-f41673eece07
		summarizeBy: sum
		sourceColumn: STORE_SPECIFIC_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ON_ORDER_COST_AMT
		dataType: double
		isHidden
		lineageTag: 508b03b2-234f-4fa7-a3b9-5307da7da74b
		summarizeBy: sum
		sourceColumn: ON_ORDER_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ON_HAND_COST_AMT
		dataType: double
		isHidden
		lineageTag: 5d9d8904-9bdf-4ffd-8236-c77f3984e8b6
		summarizeBy: sum
		sourceColumn: ON_HAND_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IN_WHSE_COST_AMT
		dataType: double
		isHidden
		lineageTag: 8d628f03-c1fb-4fd7-bae4-43ab1e4554bd
		summarizeBy: sum
		sourceColumn: IN_WHSE_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IN_TRNST_COST_AMT
		dataType: double
		isHidden
		lineageTag: 23bbc1df-bdfb-4e7a-9909-bcd67d265cb5
		summarizeBy: sum
		sourceColumn: IN_TRNST_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TAB_RCV_QTY
		dataType: double
		isHidden
		lineageTag: 2f648fd2-0f14-46b3-a6e7-55ca044aa7ef
		summarizeBy: sum
		sourceColumn: TAB_RCV_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_SPECIFIC_RTL_AMT
		dataType: double
		isHidden
		lineageTag: 356af881-6e87-4b90-b21e-0dd9caecc404
		summarizeBy: sum
		sourceColumn: STORE_SPECIFIC_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_MKDN_QTY
		dataType: double
		isHidden
		lineageTag: bd0dfa6c-92d4-4d52-bae4-3fedd1ec2b3d
		summarizeBy: sum
		sourceColumn: STORE_MKDN_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STORE_MKDN_AMT
		dataType: double
		isHidden
		lineageTag: d6cf82ee-e0ec-4de5-9989-67fe4418d152
		summarizeBy: sum
		sourceColumn: STORE_MKDN_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MAX_SHELF_QTY
		dataType: double
		isHidden
		lineageTag: f66e473e-03ef-470b-8784-11a37090aaae
		summarizeBy: sum
		sourceColumn: MAX_SHELF_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HO_MKDN_QTY
		dataType: double
		isHidden
		lineageTag: ab024d67-96d5-484e-8c2d-d0f797bdc861
		summarizeBy: sum
		sourceColumn: HO_MKDN_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HO_MKDN_AMT
		dataType: double
		isHidden
		lineageTag: 5e3c042c-99a1-4cc3-b5bb-3ae763a957d9
		summarizeBy: sum
		sourceColumn: HO_MKDN_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GROSS_RCPT_COST_AMT
		dataType: double
		isHidden
		lineageTag: 761d94b0-9b29-4417-85e8-323acfef3008
		summarizeBy: sum
		sourceColumn: GROSS_RCPT_COST_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GROSS_RCPT_RTL_AMT
		dataType: double
		isHidden
		lineageTag: 9cb51670-0731-4398-b56b-f6f164e3a1ab
		summarizeBy: sum
		sourceColumn: GROSS_RCPT_RTL_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TRGT_SHELF_QTY
		dataType: double
		isHidden
		lineageTag: e4855734-7f8f-433c-b05c-d52581dd654f
		summarizeBy: sum
		sourceColumn: TRGT_SHELF_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HO_RECOMD_RTL_PRICE_AMT
		dataType: double
		isHidden
		lineageTag: 3d772682-2e60-4da5-992a-a7a72d875f31
		summarizeBy: sum
		sourceColumn: HO_RECOMD_RTL_PRICE_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition WM_STORE_ITEM_DAILY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_STORE_ITEM_DAILY = GOLD_Schema{[Name="WM_STORE_ITEM_DAILY_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WM_STORE_ITEM_DAILY,{{"WM_YR_WK_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

