/// Provides information about all store sales at Store, UPC and Channel level; for different Time Frames.
/// This model provides the metrics aggregated at different Time Frames:
/// - LW Last Week
/// - L4W Last 4 Weeks
/// - L13W Last 13 Weeks
/// - L52W Last 52 Weeks
/// - FYTD Walmart Fiscal Year to Date
/// - CW Current Week
/// 
/// Source: WM_STORE_SALES_NEW_TRIMMED_VIEW
table WM_STORE_SALES_TIMEFRAMES
	isHidden
	lineageTag: 342cdcc2-aaff-4e85-98f0-d264490f7030

	/// WM Store Number
	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f6305d7-baef-4472-bc55-36e9b37bef5d
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Service Channel: The channel through which the order is fulfilled.
	column SVC_CHNL_NM
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ceffba04-171b-48e7-9889-e79591d5ee23
		summarizeBy: none
		sourceColumn: SVC_CHNL_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last 4 Weeks - This Year Sales Amount.
	column L4W_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: fddf7c4e-159f-4a8e-9da7-a24f35379e36
		summarizeBy: sum
		sourceColumn: L4W_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Sales Amount.
	column L13W_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: c38bc8a8-88ea-4bec-abc9-20f426a120c4
		summarizeBy: sum
		sourceColumn: L13W_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Sales Amount.
	column LW_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: df84d4f9-368b-44e2-b9b4-b20bc8199312
		summarizeBy: sum
		sourceColumn: LW_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Sales Amount.
	column L52W_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: 8540ff6b-0a3a-4e3e-b0f7-1db9bb6be55d
		summarizeBy: sum
		sourceColumn: L52W_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Sales Amount.
	column FYTD_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: fde1b000-92b5-47c2-962a-c0c12f7b3878
		summarizeBy: sum
		sourceColumn: FYTD_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year TY Sales Amount.
	column CW_TY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: d179786a-d38e-4b63-b4a6-94a489c1c0ca
		summarizeBy: sum
		sourceColumn: CW_TY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Sales Amount.
	column L4W_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: 1a5ef81c-ee2a-4401-84b5-7cdcfede7b50
		summarizeBy: sum
		sourceColumn: L4W_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Sales Amount.
	column L13W_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: b8b0010d-a937-47e4-8861-afa0e622b230
		summarizeBy: sum
		sourceColumn: L13W_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Sales Amount.
	column LW_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: f8650345-6aea-4002-9e3d-ee4e69a4e7f9
		summarizeBy: sum
		sourceColumn: LW_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Sales Amount.
	column L52W_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: ba2d767e-6b2d-4148-93f6-72f22d937775
		summarizeBy: sum
		sourceColumn: L52W_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year Sales Amount.
	column FYTD_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: 0e0f4db2-5f5c-46a1-b307-de14636286e4
		summarizeBy: sum
		sourceColumn: FYTD_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - Last Year Sales Amount.
	column CW_LY_SALES_AMT
		dataType: double
		isHidden
		lineageTag: bcd1359a-5e23-44d3-852f-81a36a1e1d39
		summarizeBy: sum
		sourceColumn: CW_LY_SALES_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - This Year Sales Units.
	column L4W_TY_QTY
		dataType: double
		isHidden
		lineageTag: ac7fed67-dee4-4b06-a616-bcc81ee76785
		summarizeBy: sum
		sourceColumn: L4W_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - This Year Sales Units.
	column L13W_TY_QTY
		dataType: double
		isHidden
		lineageTag: c59394c1-cdc4-4d56-a4a9-aa7e3fd295cd
		summarizeBy: sum
		sourceColumn: L13W_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - This Year Sales Units.
	column LW_TY_QTY
		dataType: double
		isHidden
		lineageTag: 93aea101-3b58-4c3e-adb6-14ada0aacd84
		summarizeBy: sum
		sourceColumn: LW_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - This Year Sales Units.
	column L52W_TY_QTY
		dataType: double
		isHidden
		lineageTag: 33c4f92e-d0b0-486c-bb61-7bf28d6ab3eb
		summarizeBy: sum
		sourceColumn: L52W_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - This Year Sales Units.
	column FYTD_TY_QTY
		dataType: double
		isHidden
		lineageTag: 0b857d42-ccce-48a7-a7a2-1bf6622a9a96
		summarizeBy: sum
		sourceColumn: FYTD_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - This Year Sales Units.
	column CW_TY_QTY
		dataType: double
		isHidden
		lineageTag: 1e92bb83-35a2-4b7b-8cec-b4352ac85e23
		summarizeBy: sum
		sourceColumn: CW_TY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 4 Weeks - Last Year Sales Units.
	column L4W_LY_QTY
		dataType: double
		isHidden
		lineageTag: a345f7d1-4825-4b4a-a04d-68d23bc7aac3
		summarizeBy: sum
		sourceColumn: L4W_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 13 Weeks - Last Year Sales Units.
	column L13W_LY_QTY
		dataType: double
		isHidden
		lineageTag: 54077a28-261e-44a8-a9b1-434eb8611e94
		summarizeBy: sum
		sourceColumn: L13W_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Week - Last Year Sales Units.
	column LW_LY_QTY
		dataType: double
		isHidden
		lineageTag: b7489353-8327-46b4-b87a-af32326ceec5
		summarizeBy: sum
		sourceColumn: LW_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last 52 Weeks - Last Year Sales Units.
	column L52W_LY_QTY
		dataType: double
		isHidden
		lineageTag: fb6a11a9-9906-416c-92b5-3aacade408f1
		summarizeBy: sum
		sourceColumn: L52W_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Fiscal Year to Date - Last Year Sales Units.
	column FYTD_LY_QTY
		dataType: double
		isHidden
		lineageTag: ab2a3c6f-cd1b-4f08-9a34-433e1870a567
		summarizeBy: sum
		sourceColumn: FYTD_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Current Week - Last Year Sales Units.
	column CW_LY_QTY
		dataType: double
		isHidden
		lineageTag: 020b88e3-8d4b-4f70-a394-c823d61e76a4
		summarizeBy: sum
		sourceColumn: CW_LY_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last updated date.
	column BUS_DT
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 7bf1cb41-d0e3-4117-99d9-4196817bbdb1
		summarizeBy: none
		sourceColumn: BUS_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CAL_WM_MTH_NBR
		dataType: double
		isHidden
		lineageTag: 89e417c2-1fb7-4569-856f-8cdfa9c608ee
		summarizeBy: sum
		sourceColumn: CAL_WM_MTH_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAL_WM_MTH_NM
		dataType: string
		isHidden
		lineageTag: 1344e248-48a1-4c1f-947a-1a3782ce0a7a
		summarizeBy: none
		sourceColumn: CAL_WM_MTH_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Week Number
	column CAL_WM_WK_NBR
		dataType: double
		isHidden
		lineageTag: 637fc375-2dec-473f-bf95-bfcf1780b0fd
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAL_WM_WK_NM
		dataType: string
		isHidden
		lineageTag: a96f5c34-2444-4d6a-b924-d6eb6402aa78
		summarizeBy: none
		sourceColumn: CAL_WM_WK_NM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Year Week Number.
	/// A number representing the full Walmart year and week.
	column CAL_WM_YR_WK_NBR
		dataType: double
		isHidden
		lineageTag: 541973a1-55a9-433a-8f39-2fe75cea3e18
		summarizeBy: sum
		sourceColumn: CAL_WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAL_WM_WK_DAY_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 798f2b12-f419-4d70-9e6a-5e81637ed634
		summarizeBy: sum
		sourceColumn: CAL_WM_WK_DAY_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Universal Product Code Number
	column WM_UPC_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ae14471b-53da-49e6-a2a2-797277a329fb
		summarizeBy: none
		sourceColumn: WM_UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition WM_STORE_SALES_TIMEFRAMES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_STORE_SALES_TRIMMED_View = GOLD_Schema{[Name="WM_STORE_SALES_TRIMMED_VIEW",Kind="View"]}[Data],
				    #"RowsToReturn" = if pLoadAllRecords then WM_STORE_SALES_TRIMMED_View else WM_STORE_SALES_TRIMMED_View,
				    #"Removed Columns" = Table.RemoveColumns(RowsToReturn,{"CAL_WM_FULL_YR_NBR"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"WM_UPC_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","BIS","1",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","DELIVERY","2",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","PICKUP","3",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","SFS","4",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","S2H","5",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value4","S2S","6",Replacer.ReplaceText,{"SVC_CHNL_NM"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value6",{{"CAL_WM_WK_DAY_NBR", Int64.Type}, {"SVC_CHNL_NM", Int64.Type}, {"WM_UPC_NBR", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

