/// Model with metric to compare performance between two different Time Frames. 
/// Used for Walmart Category Pre Post Comparison analysis; based on Category Sales model.
/// This should be always used along with "WM Master - Pre Post Time Frame" model.
table '07 . Metrics - Category Pre Post Comparison'
	lineageTag: d62e8a25-8294-4250-a6a7-55cbc960aa27
	sourceLineageTag: 87775885-8e77-4732-bd90-2bf6b50e9a75

	/// This Year Sales Units.
	measure 'TY Unit Sales - WMCA Pre Relay' = EXTERNALMEASURE("TY Unit Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 0f519c2b-a5af-49d6-8709-039df49dfc27
		sourceLineageTag: 694c2b2c-1cee-4cb8-8c45-41af3bae434e
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY Unit Sales - WMCA Pre Relay FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'TY $ Sales - WMCA Pre Relay' = EXTERNALMEASURE("TY $ Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: c4cacbb9-2704-4959-9dfb-4e2635c0ed31
		sourceLineageTag: 7efd753d-c727-4d43-83e7-c4a07602dda7
		dataCategory: Uncategorized

	measure 'TY Basket Count - WMCA Pre Relay' = EXTERNALMEASURE("TY Basket Count - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: af40c1f2-705e-4a86-a5ae-4244120fea6d
		sourceLineageTag: 059abcc9-9840-4278-921c-c4974616a032
		dataCategory: Uncategorized

	measure 'LY $ Sales - WMCA Pre Relay' = EXTERNALMEASURE("LY $ Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 896711fb-bed4-42a4-a87f-bfdc59308358
		sourceLineageTag: fc9e1ced-e4bc-4d8a-aa3f-454f12a0de66
		dataCategory: Uncategorized

	measure 'LY Basket Count - WMCA Pre Relay' = EXTERNALMEASURE("LY Basket Count - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: c0f275b3-176d-4ab6-9f1a-1847c2264387
		sourceLineageTag: b62ee417-b954-4a3c-88f3-d17a85454431
		dataCategory: Uncategorized

	measure 'LY Unit Sales - WMCA Pre Relay' = EXTERNALMEASURE("LY Unit Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 82e37d1f-5172-4e03-9ff4-010f2e5928b5
		sourceLineageTag: db8bffd9-ab5c-45b4-a330-6db777851db6
		dataCategory: Uncategorized

	/// This Year Avg Week Price.
	measure 'TY Price - WMCA Pre Relay' = EXTERNALMEASURE("TY Price - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: aa972ae0-cc79-43ec-900f-72c86950b469
		sourceLineageTag: 43af9bdd-8678-434e-994a-4dae20850118
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $ Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg $ Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: b7ab7862-a0a7-4512-bcbe-b78da524bbe9
		sourceLineageTag: 0c41de4f-6d28-4b16-8be2-182d84592e96
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Unit Sales - WMCA Pre Relay' = EXTERNALMEASURE("% Chg Unit Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 83bb076a-62c8-4cd5-afef-0b2119bba05c
		sourceLineageTag: 3c004ef1-e089-4339-a5f6-76b0b6cc7f30
		dataCategory: Uncategorized

	/// Last Year Avg Week Price.
	measure 'LY Price - WMCA Pre Relay' = EXTERNALMEASURE("LY Price - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 6f8da3b3-1dc9-4739-85a1-91a642f293fc
		sourceLineageTag: 3bc2c4a7-7bd7-4604-a88b-bd5238155db2
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Price YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg Price YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 7ba6a246-c442-4102-9882-f3db112754f4
		sourceLineageTag: 49812645-e63b-45a4-b1f8-68a4f3cbb985
		dataCategory: Uncategorized

	measure 'Week Count - WMCA Pre Relay' = EXTERNALMEASURE("Week Count - WMCA Pre Relay", INTEGER, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: 0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 4f6c61e2-d44c-4c9f-9034-c9b57494df0c
		sourceLineageTag: b4c50538-9a17-43bd-b315-6a286df1f25e
		dataCategory: Uncategorized

	measure 'Store Count - WMCA Pre Relay' = EXTERNALMEASURE("Store Count - WMCA Pre Relay", INTEGER, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 2264c133-9723-4e29-a7e0-6475449c332b
		sourceLineageTag: 3de727de-5e5e-42bd-a6ef-feac0f8c58fc
		dataCategory: Uncategorized

	measure 'Stores/Week - WMCA Pre Relay' = EXTERNALMEASURE("Stores/Week - WMCA Pre Relay", INTEGER, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: 0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: aa097102-e7ce-4092-acb0-e09b816e0b3c
		sourceLineageTag: 0869bf39-9a57-404a-aafe-4b3e90678110
		dataCategory: Uncategorized

	/// This Year Average Weekly Sales Amount.
	measure 'TY Avg Wkly $ Sales - WMCA Pre Relay' = EXTERNALMEASURE("TY Avg Wkly $ Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: c0c70ca0-a5c9-4484-9418-a53b58e7a517
		sourceLineageTag: 285671e3-1ede-4c7b-a61d-337fa1034bc2
		dataCategory: Uncategorized

	/// Last Year Average Weekly Sales Amount.
	measure 'LY Avg Wkly $ Sales - WMCA Pre Relay' = EXTERNALMEASURE("LY Avg Wkly $ Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 1752e993-094e-40bb-be0c-211a8f3166d8
		sourceLineageTag: 04b22a50-8667-4aa1-9c30-5166854b4d19
		dataCategory: Uncategorized

	/// This Year Average Weekly Sales Units.
	measure 'TY Avg Wkly Unit Sales - WMCA Pre Relay' = EXTERNALMEASURE("TY Avg Wkly Unit Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 08a589c7-d735-43bb-b53d-1f4a66826e61
		sourceLineageTag: 7f60b8bf-ff61-44b9-a647-0fad21b7f4c0
		dataCategory: Uncategorized

	/// Last Year Average Weekly Sales Units.
	measure 'LY Avg Wkly Unit Sales - WMCA Pre Relay' = EXTERNALMEASURE("LY Avg Wkly Unit Sales - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: a4e9d0ce-d199-4337-ae16-478ac190dbf9
		sourceLineageTag: caead6a4-3ef7-42f9-a2ca-e61bf8989f80
		dataCategory: Uncategorized

	/// This Year $ Sales Velocity: $ per Store per Week.
	measure 'TY $/S/W - WMCA Pre Relay' = EXTERNALMEASURE("TY $/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 518f19d8-21e5-4d9b-bfa6-9124cfc3ccf8
		sourceLineageTag: 8ff402e6-bf92-447f-a6b7-22bb75e69499
		dataCategory: Uncategorized

	/// Last Year $ Sales Velocity: $ per Store per Week.
	measure 'LY $/S/W - WMCA Pre Relay' = EXTERNALMEASURE("LY $/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 22b9ad92-0430-4db4-96fb-c12d186b5c0c
		sourceLineageTag: 927e247e-8d51-4fe3-94fd-1036fab6bb6d
		dataCategory: Uncategorized

	/// This Year Unit Sales Velocity: Units per Store per Week.
	measure 'TY U/S/W - WMCA Pre Relay' = EXTERNALMEASURE("TY U/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: f9c60244-0a18-4e5d-a970-f06099eca658
		sourceLineageTag: 565e3319-5276-480b-ab8b-8916a03bc233
		dataCategory: Uncategorized

	/// Last Year Unit Sales Velocity: Units per Store per Week.
	measure 'LY U/S/W - WMCA Pre Relay' = EXTERNALMEASURE("LY U/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 005ee36b-5be8-4041-9456-aafdf8f10a17
		sourceLineageTag: 242cd744-9f29-46f5-9ade-91dfffe623b3
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff $ Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff $ Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: d4d42aa4-97a7-402e-ae36-1cab6120c09c
		sourceLineageTag: 8a606621-32ec-460a-b99c-d3076eefbdbe
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Unit Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff Unit Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: ddc54e16-215d-4ecd-aa4b-1828dc675b37
		sourceLineageTag: 1ab0bfc2-9ee5-4b78-84f8-7b78c43afaec
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff $/S/W YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff $/S/W YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: d68acfc0-8587-46cd-bf31-8dfe8ecad9b2
		sourceLineageTag: a6de7af3-2d09-433d-ac0a-cc028b844de8
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff U/S/W YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff U/S/W YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 6848bdf4-e02e-4579-a35a-14df1ba92bbc
		sourceLineageTag: 511c798e-1386-4bf9-9804-cf8dba8d479a
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Avg Wkly $ Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff Avg Wkly $ Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: $#,##0;$(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 7958f930-5691-45cf-ab01-74750ccef914
		sourceLineageTag: 4cd71544-c6bf-4eb9-87c7-fedc4c87b1a5
		dataCategory: Uncategorized

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff Avg Wkly Unit Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("# Diff Avg Wkly Unit Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 156f663b-ab6f-4565-ad06-ca08be1860c4
		sourceLineageTag: 8a7c6a0e-d253-4666-a01e-b2b7e0898936
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly $ Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg Avg Wkly $ Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 0c7bbe16-d5c9-4b9a-b570-f213f43c92d5
		sourceLineageTag: 383098de-ff15-4e03-a1e2-08e9c47bd18b
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly Unit Sales YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg Avg Wkly Unit Sales YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: c8a55677-ba35-4685-b3a8-073c56c9d10b
		sourceLineageTag: 705a0c17-ff8e-4a3d-befd-5c56767a82df
		dataCategory: Uncategorized

	measure 'TY $ Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY $ Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 014d1bc5-d28a-446d-aa62-b6db432bd097
		sourceLineageTag: 250e3556-d4aa-49ce-a085-966a3edc0cb7
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY $ Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// This Year Weekly Unit Sales.
	measure 'TY Unit Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY Unit Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 35b63b32-a0bc-424e-aadd-c70bb0855bfe
		sourceLineageTag: 7d6d76c3-c90a-41bd-84a8-d22aa3498712
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY Unit Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'Store Count - WMCA Pre Post Comparison' = EXTERNALMEASURE("Store Count - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 743f302d-2156-4f94-a992-43bc82e301bd
		sourceLineageTag: 71c52696-1040-42f4-be48-725e30f5294f
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Store Count - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'Weeks Count - WMCA Pre Post Comparison' = EXTERNALMEASURE("Weeks Count - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 2a416b36-491b-4b4a-883f-f2dc822b30bb
		sourceLineageTag: 85572969-b111-4849-9de2-ae05816040f1
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Weeks Count - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// This Year $ Sales Velocity: $ per Store per Week.
	measure 'TY $/S/W - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY $/S/W - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: ec3d2180-e0ed-4b0c-9081-725fff43f763
		sourceLineageTag: d1bce08e-49d5-4cbb-8c3e-78398ff4e913
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY $/S/W - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// This Year Unit Sales Velocity: Units per Store per Week.
	measure 'TY U/S/W - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY U/S/W - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 11b71931-5fbc-42b1-837d-a630d179265b
		sourceLineageTag: c74c612c-1230-49bb-8722-3367d00ba8a3
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY U/S/W - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'Store/Weeks - WMCA Pre Post Comparison' = EXTERNALMEASURE("Store/Weeks - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 71b360dc-0285-4c78-8355-f6cf390a0ff3
		sourceLineageTag: e363822d-73bf-483d-989d-cf3ade6f6734
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Store/Weeks - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'LY Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: f3e870c4-10e6-44f1-90ee-6e92bf41ad38
		sourceLineageTag: e66c2dd8-8a68-41a5-999f-6341d780e9a8
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'LY Unit Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY Unit Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: c8f298b2-7685-4ed5-9cd5-4ef66b560809
		sourceLineageTag: 1f62ae61-7a6c-493f-998d-a63977f5dc7d
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY Unit Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Last Year $ Sales Velocity: $ per Store per Week.
	measure 'LY $/S/W - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY $/S/W - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: c7adea03-ea8e-4191-b7a1-886b76831426
		sourceLineageTag: 83e2ab34-374e-4a85-97e2-0a81bbca75e8
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY $/S/W - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Last Year Unit Sales Velocity: Units per Store per Week.
	measure 'LY U/S/W - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY U/S/W - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 982073bf-532b-4229-84ef-0704cbb41229
		sourceLineageTag: 1e701c62-1e6b-47ce-8be6-85918269cad2
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY U/S/W - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff $/S/W YoY - WMCA Pre Post Comparison' = EXTERNALMEASURE("# Diff $/S/W YoY - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 439dc640-bf08-4a7f-b419-bef369443fcb
		sourceLineageTag: ce176568-9211-436d-a4c2-9ce48df7cf63
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_# Diff $/S/W YoY - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year absolute difference: 
	/// Absolute difference between This Year and Last Year metric.
	measure '# Diff U/S/W YoY - WMCA Pre Post Comparison' = EXTERNALMEASURE("# Diff U/S/W YoY - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 0b2f183c-9d7b-4424-a232-8068f3563bc9
		sourceLineageTag: e0c6bc01-6288-4f45-9839-bcf3cd805a66
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_# Diff U/S/W YoY - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $/S/W YoY - WMCA Pre Post Comparison' = EXTERNALMEASURE("% Chg $/S/W YoY - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: df341538-4d3c-4a80-a41a-67ec0d08f337
		sourceLineageTag: 72432e54-cb9e-4051-8220-27e52e2e04da
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_% Chg $/S/W YoY - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// This Year Average Weekly Sales Amount.
	measure 'TY Avg Wkly $ Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY Avg Wkly $ Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 3838f624-e37e-4bd2-8c34-5c5da4dfd557
		sourceLineageTag: f91cd97b-58ec-44eb-b38e-7dbcbec0f8c8
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY Avg Wkly $ Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Last Year Average Weekly Sales Amount.
	measure 'LY Avg Wkly $ Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY Avg Wkly $ Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 2b1506d6-8aa6-4156-92be-356673411d50
		sourceLineageTag: 7d9da2ca-0944-4fd6-ba03-4f5acc78c3f6
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY Avg Wkly $ Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// This Year Average Weekly Sales Units.
	measure 'TY Avg Wkly Unit Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY Avg Wkly Unit Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 2af7700c-d539-4efc-bb09-4d537067c2e2
		sourceLineageTag: 54ef70e7-4e7a-43d8-a3aa-bab86984d56c
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY Avg Wkly Unit Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Last Year Average Weekly Sales Units.
	measure 'LY Avg Wkly Unit Sales - WMCA Pre Post Comparison' = EXTERNALMEASURE("LY Avg Wkly Unit Sales - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: ccdb834b-5423-4168-a7db-fbb4e939a1f2
		sourceLineageTag: a2cf3cb3-3dfa-49cd-b96b-3df40d3d6838
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_LY Avg Wkly Unit Sales - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure '$ Share - WMCA Pre Post Comparison' = EXTERNALMEASURE("$ Share - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 9fb8f4d3-1c6b-4680-b1f9-a0f66b9c6981
		sourceLineageTag: f51a2abb-b92c-49e8-8f1f-261280cb8093
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_$ Share - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'Unit Share - WMCA Pre Post Comparison' = EXTERNALMEASURE("Unit Share - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: d30b52c2-9fa9-4e28-b879-9f77be426430
		sourceLineageTag: c817451a-a594-4fa0-8311-52a1831e47e6
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_Unit Share - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'TY C/S/W - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY C/S/W - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 187e3930-8865-467f-9ad8-c55444ab687b
		sourceLineageTag: 108e5f1c-90df-4447-b74f-ff65bea6273f
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY C/S/W - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	measure 'TY AUR - WMCA Pre Post Comparison' = EXTERNALMEASURE("TY AUR - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 3928cf00-f109-4a81-8a78-82bc921a068b
		sourceLineageTag: 33919f2d-6851-4ed5-af05-68509aa4ebf9
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_TY AUR - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly $ Sales vs LY - WMCA Pre Post Comparison' = EXTERNALMEASURE("% Chg Avg Wkly $ Sales vs LY - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: 891d0228-66a6-4bfc-aedc-50188ed54924
		sourceLineageTag: de31cfbe-66d0-4cc0-828b-094aa7fbd934
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_% Chg Avg Wkly $ Sales vs LY - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Avg Wkly Unit Sales YoY - WMCA Pre Post Comparison' = EXTERNALMEASURE("% Chg Avg Wkly Unit Sales YoY - WMCA Pre Post Comparison", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		displayFolder: WMCA Pre Post Comparison
		lineageTag: ed437943-ee0b-458a-a504-e745feae7d89
		sourceLineageTag: 6ef96419-ada7-49e8-b799-c1f9040ab95e
		dataCategory: Uncategorized

		formatStringDefinition = EXTERNALMEASURE("_% Chg Avg Wkly Unit Sales YoY - WMCA Pre Post Comparison FormatString", STRING, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $/S/W YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg $/S/W YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 6baee44d-b37b-47a0-a84d-6b615a7bec03
		sourceLineageTag: 360d6b3b-888e-43ee-8227-995d40d1b6be
		dataCategory: Uncategorized

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg U/S/W YoY - WMCA Pre Relay' = EXTERNALMEASURE("% Chg U/S/W YoY - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 531b7671-6a56-4db6-a48d-77bd2d3c19d9
		sourceLineageTag: fb169643-761b-4a66-ba3f-0b70691ddcd8
		dataCategory: Uncategorized

	measure '$ Share - WMCA Pre Relay' = EXTERNALMEASURE("$ Share - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: 0.0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 23d1d632-f4ed-4f88-a2a8-00f1735c0e23
		sourceLineageTag: ae0c016f-76fb-4212-b97f-a048ae40a3ba
		dataCategory: Uncategorized

	measure 'Unit Share - WMCA Pre Relay' = EXTERNALMEASURE("Unit Share - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: 0.0
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: beb00190-dce1-44cb-8dd3-c983ce4c88e4
		sourceLineageTag: 1d9c06e8-0542-43bb-9c25-8cceff5d6339
		dataCategory: Uncategorized

	measure 'TY C/S/W - WMCA Pre Relay' = EXTERNALMEASURE("TY C/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: 739ed0b6-fd61-44d9-b4b7-7528af8edc47
		sourceLineageTag: 09b5bcbb-104b-4675-80b6-03fb431f432d
		dataCategory: Uncategorized

	measure 'LY C/S/W - WMCA Pre Relay' = EXTERNALMEASURE("LY C/S/W - WMCA Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: d93355be-412f-4eda-af64-591d5dca9525
		sourceLineageTag: 19d6e936-43c7-4f5a-887c-9b0df7f0d32a
		dataCategory: Uncategorized

	measure 'TY In Stock Rate - Weekly Pre Relay' = EXTERNALMEASURE("TY In Stock Rate - Weekly Pre Relay", DOUBLE, "DirectQuery to AS - WM Luminate - Red Bull - Semantic Model")
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: WMCA Pre Relay
		lineageTag: cc6692c1-1250-4ac7-9169-aeeb7b9d267d
		sourceLineageTag: 47520f29-1ee8-4461-8b86-65b1430240e5
		dataCategory: Uncategorized

	partition '07 . Metrics - Category Pre Post Comparison' = entity
		mode: directQuery
		source
			entityName: 07 . Metrics - Category Pre Post Comparison
			expressionSource: 'DirectQuery to AS - WM Luminate - Red Bull - Semantic Model'

