table 'Measure Selection'
	isHidden
	lineageTag: c7f5b396-24c2-4393-a470-604a4ae38213

	column Selection
		dataType: string
		isHidden
		lineageTag: d20aaec1-434f-49c0-90b1-a6d6f76eb84f
		summarizeBy: none
		sourceColumn: Selection
		sortByColumn: 'Selection ID'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Selection ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2b630a8a-55a2-451e-a545-5f488e48f9bf
		summarizeBy: none
		sourceColumn: Selection ID

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Measure Selection' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WColUCEvMKU1V0lEyUIrViVbyQQgYggUcnYIVnDPSgXwjMF8VyjMG85zz80r0FNyL8stLMoCCJkqxsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Ordinal = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Ordinal", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Ordinal", "Selection ID"}, {"Metric", "Selection"}})
				in
				    #"Renamed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

