/// Latest Store UPC Inventory measures.
/// This model only returns the latest available date (Day - 2).
/// This will consider In Modular (Store Planogram) only records. 
/// 
/// Recommend usage along with:
/// - WM Master: Store
/// - WM Master: UPC
/// - WM Master: Mod Trait
/// 
/// Source: WM_STORE_ITEM_UPC_LATEST_VIEW
table '04. Metrics - Store Inventory Latest'
	lineageTag: dc8883d7-7617-429b-a743-28e24150860d

	/// Out of Stock Flag for Store UPC combination:
	/// 1 - Out of Stock
	/// 0 - No, there is stock
	measure '# Out of Stock - Current' = CALCULATE(SUM(WM_STORE_ITEM_UPC_LATEST[OUT_OF_STOCK]))
		formatString: #,0
		lineageTag: 313709da-9cc8-4474-bcec-5f8f4f14e98e

		changedProperty = IsHidden

	/// Total Points of Distribution  count: Store and UPC combination
	measure 'TY Total PODs - Current' =
			
			VAR UniqueStoreUPC =
			    DISTINCT(
			        SELECTCOLUMNS(
			            WM_STORE_ITEM_UPC_LATEST,
			            "Store", WM_STORE_ITEM_UPC_LATEST[STORE_NBR],
			            "UPC", WM_STORE_ITEM_UPC_LATEST[UPC_NBR]
			        )
			    )
			RETURN
			    COUNTROWS(UniqueStoreUPC)
		formatString: #,0
		lineageTag: fd1cbd03-94c7-40c9-bc91-2a5c8f54dbe3

		changedProperty = IsHidden

	/// This Year In Stock Rate: 
	/// Latest percentage of UPCs with stock on a store. 
	/// This metric considers only In Modular (Store Planogram) UPCs. 
	measure 'TY In Stock Rate - Current' =
			
			VAR TotalOutOfStock =
			    CALCULATE(
			        SUM(WM_STORE_ITEM_UPC_LATEST[OUT_OF_STOCK])
			    )
			VAR UniqueStoreUPC =
			    DISTINCT(
			        SELECTCOLUMNS(
			            WM_STORE_ITEM_UPC_LATEST,
			            "Store", WM_STORE_ITEM_UPC_LATEST[STORE_NBR],
			            "UPC", WM_STORE_ITEM_UPC_LATEST[UPC_NBR]
			        )
			    )
			RETURN
			DIVIDE( COUNTROWS(UniqueStoreUPC) - TotalOutOfStock, COUNTROWS(UniqueStoreUPC), BLANK() )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9a47181c-226c-4bdb-9dab-925d15989901

		changedProperty = IsHidden

	/// Total Points of Distribution  count (Store and UPC combination) which are Out of Stock
	measure 'TY Total PODs Out of Stock - Current' =
			
			VAR OutOfStockRows =
			    FILTER(
			        WM_STORE_ITEM_UPC_LATEST,
			        WM_STORE_ITEM_UPC_LATEST[OUT_OF_STOCK] > 0
			    )
			VAR UniqueStoreUPC =
			    DISTINCT(
			        SELECTCOLUMNS(
			            OutOfStockRows,
			            "Store", WM_STORE_ITEM_UPC_LATEST[STORE_NBR],
			            "UPC", WM_STORE_ITEM_UPC_LATEST[UPC_NBR]
			        )
			    )
			RETURN
			    COUNTROWS(UniqueStoreUPC)
		formatString: 0
		lineageTag: b7a31202-7e7d-45ab-a33d-c05da1fee8fa

		changedProperty = IsHidden

	partition '04. Metrics - Store Inventory Latest' = m
		mode: import
		queryGroup: 'Reporting - Metrics'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

