table '11. Metrics - Sales Tender Weekly'
	lineageTag: 46f12a69-93e0-4081-b5f7-aed89198cace

	measure 'Visits by Tender' = SUM(WM_SALES_TENDER_WEEKLY[VISITS_BY_TENDER])
		formatString: #,0
		lineageTag: 3e4c4614-f53a-4a90-98fd-e818fd35074e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Units by Tender' = SUM(WM_SALES_TENDER_WEEKLY[UNITS_BY_TENDER])
		formatString: #,0
		lineageTag: 6fa5e7a5-03ba-4555-b441-b342a1ba75bc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '$ Sales by Tender' = SUM(WM_SALES_TENDER_WEEKLY[SALES_BY_TENDER])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 39262cef-f712-4339-b03e-b8b0755dc952

	partition '11. Metrics - Sales Tender Weekly' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

