/// Combination of Store Sales and Store Fulfillment metrics.
/// 
/// This model provides the metrics aggregated at different Time Frames:
/// - LW Last Week
/// - L4W Last 4 Weeks
/// - L13W Last 13 Weeks
/// - L52W Last 52 Weeks
/// - FYTD Walmart Fiscal Year to Date
/// - CW Current Week
/// 
/// Recommend usage along with:
/// - WM Master: Time Frame
/// - WM Master: Store
/// - WM Master: UPC
/// - WM Master: Mod Trait
/// 
/// Source: WM_STORE_FULFILMENT_WEEK_VIEW
/// WM_STORE_SALES_WEEK_VIEW
/// 
table '03. Metrics - Store Sales and Fulfillment Time Frames'
	lineageTag: 77a7e025-40b3-4e31-aa9c-9b42a1b070dc

	measure 'FYTD TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[FYTD_TY_SALES_AMT])
		formatString: #,0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 4c148097-30ff-44a3-94ec-8eaeae6cd7a6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FYTD LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[FYTD_LY_SALES_AMT])
		formatString: #,0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 339a2533-beb6-4faf-892f-001d953518a8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'L13W LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L13W_LY_SALES_AMT])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 3809dbfe-9187-49f1-8f7d-deb31ef24111

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L13W_TY_SALES_AMT])
		formatString: #,0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 495fef33-957d-444f-a0dc-220fdad9c38f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'L4W LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L4W_LY_SALES_AMT])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 4f1bec3e-d6b5-4a8f-9936-319260422bd0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L4W_TY_SALES_AMT])
		formatString: #,0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: e20c2a18-1c73-47cb-a5de-17ffdfe965b2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'LW LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[LW_LY_SALES_AMT])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 80115c12-3cc7-458f-bc05-842facb7e94e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[LW_TY_SALES_AMT])
		formatString: #,0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 29334768-78a9-453d-8f7d-cd5e97a475d4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FYTD LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[FYTD_LY_QTY])
		formatString: #,0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 853ae28f-b899-425a-ba25-522661530cf8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FYTD TY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[FYTD_TY_QTY])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 483f4c7d-4656-45a9-b10e-9ac1fa3dadc2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[L13W_TY_QTY])
		formatString: #,0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: f5b5422d-f085-48cf-ab7b-ed12e03c1bd8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'L13W LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[L13W_LY_QTY])
		formatString: #,0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 86ebe83a-78ba-4595-a787-822b3af9eac4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'L4W LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[L4W_LY_QTY])
		formatString: #,0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 099747bf-260e-4a44-8079-d64e343666a9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'LW LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[LW_LY_QTY])
		formatString: #,0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 96ee38ba-1f8f-4692-b544-c54e733da34b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// This Year Unit Sales.
	measure 'L4W TY Units' = SUM(WM_STORE_SALES_TIMEFRAMES[L4W_TY_QTY])
		formatString: #,0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 298ece13-e114-4250-a2f5-09dcd4d78d8d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// This Year Unit Sales.
	measure 'LW TY Units' = SUM(WM_STORE_SALES_TIMEFRAMES[LW_TY_QTY])
		formatString: #,0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 203a1454-0533-4720-83a8-fee1a1f70fe6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Last Year Avg Period Price.
	measure 'FYTD LY Price' = DIVIDE([FYTD LY Sales], [FYTD LY Qty])
		formatString: 0.0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: f03b9afb-0a52-4cb6-bf02-3387ecb6fcef

		changedProperty = IsHidden

	/// This Year Avg Period Price.
	measure 'FYTD TY Price' = DIVIDE([FYTD TY Sales], [FYTD TY Qty])
		formatString: 0.0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 835892f2-c216-4819-baa8-ed3ba468fbb7

		changedProperty = IsHidden

	/// This Year Avg Period Price.
	measure 'L13W TY Price' = DIVIDE([L13W TY Sales], [L13W TY Qty])
		formatString: 0.0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: bc6e40ef-91b6-4cf9-9842-157916b203e4

		changedProperty = IsHidden

	/// This Year Avg Period Price.
	measure 'L4W TY Price' = DIVIDE([L4W TY Sales], [L4W TY Units])
		formatString: 0.0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: d307f1e7-cdd2-4ce0-a2b3-6cefa3724721

		changedProperty = IsHidden

	/// Last Year Avg Period Price.
	measure 'L13W LY Price' = DIVIDE([L13W LY Sales], [L13W LY Qty])
		formatString: 0.0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 1b642439-cc14-412e-b4d3-cf207845bd8b

		changedProperty = IsHidden

	/// This Year Avg Period Price.
	measure 'LW TY Price' = DIVIDE([LW TY Sales], [LW TY Units])
		formatString: 0.0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 9293dbba-28ef-4366-94c2-28cf0787661c

		changedProperty = IsHidden

	/// Last Year Avg Period Price.
	measure 'LW LY Price' = DIVIDE([LW LY Sales], [LW LY Qty])
		formatString: 0.0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 53f9a9ca-7344-4307-ab1f-3e7bac198bbf

		changedProperty = IsHidden

	/// Last Year Avg Period Price.
	measure 'L4W LY Price' = DIVIDE([L4W LY Sales], [L4W LY Qty])
		formatString: 0.0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: f77bd013-286c-46e3-a692-c30c48bd5263

		changedProperty = IsHidden

	/// This Year Sales Amount.
	measure 'TY $ Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $#,##0;$(#,##0)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 2ce5285d-0236-4f78-ac7d-50d4cea706a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Unit Sales.
	measure 'TY Unit Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Unit Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Unit Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Unit Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Unit Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Unit Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Unit Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: #,0
		displayFolder: TY Metrics - Time Frames
		lineageTag: 02260d89-c9c6-4f4b-9b6d-3ddd2bfe62d1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// This Year Avg Period Price.
	measure 'TY Price' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Price - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Price - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Price - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Price - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Price - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Price - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $0.00;$(0.00)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 405b4a12-855b-4876-a8ec-f1ee5bab183f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Sales YoY' = DIVIDE(([TY $ Sales]-[LY $ Sales]),[LY $ Sales], BLANK())
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 8182040d-c26c-46a6-ab3d-5f24d2e011c5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Unit Sales YoY' = DIVIDE(([TY Unit Sales]-[LY Unit Sales]),[LY Unit Sales], BLANK())
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 5346f4db-164f-4bb3-9003-32f6093371a5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Price YoY' = DIVIDE(([TY Price]-[LY Price]),[LY Price], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 6a49d377-18c5-49c3-9972-0b5aeedf4b05

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Sales YoY' = [TY $ Sales]-[LY $ Sales]
		formatString: $#,##0;$(#,##0)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 989607b6-4bfe-434c-a6bb-2284b614abe0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Price YoY' = [TY Price]-[LY Price]
		formatString: ,##0.00;(##0.00)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: b88eb78f-8bf9-438b-a02e-62d15bff65bf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Unit Sales YoY' = [TY Unit Sales]-[LY Unit Sales]
		formatString: #,##0;(#,##0)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 30829d86-f3b8-4316-a607-4fc5d5de48c9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Last Year Sales Amount.
	measure 'LY $ Sales' = ```
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
			
			```
		formatString: $#,##0;$(#,##0)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 2e483dcc-cde4-4ded-a46e-d110aee65eec

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Last Year Avg Period Price.
	measure 'LY Price' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Price - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Price - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Price - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Price - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Price - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY Price - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $0.00;$(0.00)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 07206a67-30c3-49d8-b1b2-ffc0abbea054

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY Unit Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Unit Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Unit Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Unit Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Unit Sales - Weekly],	'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Unit Sales - Weekly], 	'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 3dbd171b-8455-45f0-9739-2175e2b8bec8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cont. Growth Sales' = ```
			
			var _TotalABSSales = 
			    CALCULATE([ABS Chg Sales YoY], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([ABS Chg Sales YoY] , _TotalABSSales)*100
			```
		formatString: 0.0;(0.0)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 7c5a2c8e-bdcb-4855-b705-d32e38228852

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Cont. Growth Unit Sales' = ```
			
			var _TotalABSUnits = 
			    CALCULATE([ABS Chg Unit Sales YoY], ALL(WM_STORE_SALES_TIMEFRAMES) )
			return
			    DIVIDE([ABS Chg Unit Sales YoY] , _TotalABSUnits) * 100
			```
		formatString: 0.0;(0.0)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 31f717bb-1026-4dd6-8bd8-b5f0c97755f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Cont. Growth Price' = ```
			
			var _TotalABSPrice = 
			    CALCULATE([ABS Chg Price YoY], ALL(WM_STORE_SALES_TIMEFRAMES) )
			return
			    DIVIDE([ABS Chg Price YoY] , _TotalABSPrice)*100
			```
		formatString: 0.0;(0.0)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: ac4492d2-db74-4286-995f-9f6f4256e9b9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FYTD LY Sales (FYTD)' = ```
			[FYTD LY Sales]
			-- VAR LAST_WK = [WM Week Num]
			-- RETURN 
			-- CALCULATE(
			-- [FYTD LY Sales], 
			--    VALUES(WM_SALES_IMPORT[CAL_WM_WK_NBR]), 
			--    WM_SALES_IMPORT[CAL_WM_WK_NBR] <= 13
			--)
			
			```
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: c4d17cbb-1a15-4816-810e-20478f843f9c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Qty (FYTD)' = ```
			[FYTD LY Qty]
			-- VAR LAST_WK = [WM Week Num]
			-- RETURN 
			-- CALCULATE(
			--    [FYTD LY Qty], 
			--    VALUES(WM_SALES_IMPORT[CAL_WM_WK_NBR]),
			--    WM_SALES_IMPORT[CAL_WM_WK_NBR]<= LAST_WK
			--)
			```
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 0ddb080d-6ccf-4d83-bf6b-98827e30b4bb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Year Avg Period Price.
	measure 'FYTD LY Price (FYTD)' = DIVIDE([FYTD LY Sales (FYTD)], [FYTD LY Qty (FYTD)])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 08ebe966-3546-4ee2-bb27-df2864e6b565

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WM Week Num' = MAX('WM_CATEGORY_INFO'[CAL_WM_WK_NBR])
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 7efc24d6-cbff-4e7f-be67-4954ae5376be

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[FYTD_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 64b23701-59e7-43b3-b349-9b3ca3809c1a

		changedProperty = IsHidden

	measure 'LW TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[LW_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 1d890b3b-2c83-48f0-8568-df059324545e

		changedProperty = IsHidden

	measure 'L4W LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L4W_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: e9760924-bbba-421a-a3fe-6df032964de9

		changedProperty = IsHidden

	measure 'L13W TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L13W_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 07cea5d1-166c-4cdc-badc-88186a6518ff

		changedProperty = IsHidden

	measure 'L52W TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L52W_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: b2b34abb-39f5-4571-9a69-fd34bbd13668

		changedProperty = IsHidden

	measure 'FYTD Weeks Count' = MAX('WM_CATEGORY_INFO'[CAL_WM_WK_NBR])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 4189b7b6-1837-4976-b0c8-66856af4ce76

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Store Selling Count' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Stores Selling - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Stores Selling - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Stores Selling - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Stores Selling - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Stores Selling - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Stores Selling - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0
		displayFolder: TY Metrics - Time Frames
		lineageTag: 8c349365-a7b8-44aa-9a9c-8036e093206f

		changedProperty = IsHidden

	/// This Year $ Sales Velocity: $ per Store per Week.
	measure 'TY $/S/W' = DIVIDE([TY $ Sales], [Total Stores-Week], BLANK())
		formatString: $#,##0.00;$(#,##0.00)
		displayFolder: TY Metrics - Time Frames
		lineageTag: cc5db0d2-a0d3-49e4-a209-590c83198c68

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Unit Sales Velocity: Units per Store per Week.
	measure 'TY U/S/W' = DIVIDE([TY Unit Sales], [Total Stores-Week], BLANK())
		formatString: #,0.00
		displayFolder: TY Metrics - Time Frames
		lineageTag: d0f5bbe7-1cd2-4e1e-b49a-5c869d280c21

		changedProperty = IsHidden

	measure 'FYTD LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[FYTD_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: cdbf1524-0cb3-4ead-8ffb-1befbfddd06c

		changedProperty = IsHidden

	measure 'L13W LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L13W_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 4f0b0922-4ac6-4e9d-9540-d92277da3f64

		changedProperty = IsHidden

	measure 'LW LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[LW_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 21a086c4-77c3-46bf-a1ee-562631ca4ad7

		changedProperty = IsHidden

	measure 'LY Stores Selling' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Stores Selling - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Stores Selling - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Stores Selling - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Stores Selling - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Stores Selling - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY Stores Selling - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: #,0
		displayFolder: LY Metrics - Time Frames
		lineageTag: fd026d2e-da93-412a-8425-0b7d624afbd4

		changedProperty = IsHidden

	measure 'L4W TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L4W_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 7ca00679-ce3a-4ff6-812e-cca832ab0592

		changedProperty = IsHidden

	/// Last Year $ Sales Velocity: $ per Store per Week.
	measure 'LY $/S/W' = DIVIDE([LY $ Sales], [Total Stores-Week], BLANK())
		formatString: $#,##0.00;$(#,##0.00)
		displayFolder: LY Metrics - Time Frames
		lineageTag: f527abb2-b567-4914-956e-468584260d6b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg $/S/W YoY' = [TY $/S/W] - [LY $/S/W]
		formatString: $#,##0.00;$(#,##0.00)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: bc88a7e2-ff44-40c0-af4e-a41e603213f2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Stores Selling YoY' = [TY Store Selling Count] - [LY Stores Selling]
		formatString: #,##0;(#,##0)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 8ba83d0b-5b2c-4fb7-b2af-9433bbd139c3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Stores Selling YoY' = DIVIDE(([TY Store Selling Count]-[LY Stores Selling]),[LY Stores Selling], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 72cdc7c1-239f-452d-883f-a97ed54782cb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg $/S/W YoY' = DIVIDE(([TY $/S/W]-[LY $/S/W]),[LY $/S/W], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: a150e63f-00b8-4daf-ad23-576a6cd96486

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Last Year Unit Sales Velocity: Units per Store per Week.
	measure 'LY U/S/W' = DIVIDE([LY Unit Sales], [Total Stores-Week], BLANK())
		displayFolder: LY Metrics - Time Frames
		lineageTag: 46db39d7-4018-496f-9c63-24781d9f969f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg U/S/W YoY' = [TY U/S/W] - [LY U/S/W]
		formatString: #,##0.00;(#,##0.00)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 7c015152-bf9a-41fe-8fdc-21c0e5ceb8ee

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg U/S/W YoY' = DIVIDE(([TY U/S/W]-[LY U/S/W]),[LY U/S/W], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 6049c9cb-befb-4132-bf4a-74e8eebc96fc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Cont. Growth $/S/W' = ```
			
			var _TotalABSSales = 
			    CALCULATE([ABS Chg $/S/W YoY], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([ABS Chg $/S/W YoY] , _TotalABSSales)*100
			```
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 7f690aee-6c2f-4648-bbc2-76b36d4ab409

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: cc0eca9b-e11f-46c4-a4f8-1c55ca4a9c62

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 2b8e8b85-f3ab-40c7-90c2-118436b35042

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 0f8b0e43-fc10-4334-942b-fc0856fe43c8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: d444b2d5-755f-4420-8b12-b0dd6fae781b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 48d912b1-79c4-42da-9138-0e782b2666b9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 1cfef6eb-037f-43e5-b6ef-3c9fd4f6458a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: fe6f18ad-3053-41e1-8a07-c230b776f532

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 8f733bf2-3b62-4e85-90bb-5139401e2148

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_FTPR_DNMNTR]))
		formatString: 0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 019dfac9-6dbf-4a82-b7c8-b9b67e10a611

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'L4W TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 0d928e35-bfdf-4f5e-8d68-de00654cde61

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: d16e9158-a57c-45b3-972f-417729476dae

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_FTPR_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 3aa05c35-3a01-44a3-bcd0-770c19fcd8ee

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY FTPR' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY FTPR - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY FTPR - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY FTPR - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY FTPR - Weekly],	'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY FTPR - Weekly], 	'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: e3911e3a-0c6f-418a-b100-743847282e3c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LW LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 8dd0d20f-38ee-4244-8dae-46abfa9eefe8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 20ca26f1-57d7-477c-b365-827e7da475e2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 24ebb133-0558-4732-9bd7-29a904c265bf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: acbe0093-9928-43a1-87c0-01275dafe2e0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Year First Time Pick Rate:
	/// The percentage of items that were picked in the first pick-walk for store fulfilled orders.
	measure 'LY FTPR' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY FTPR - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY FTPR - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY FTPR - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY FTPR - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY FTPR - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY FTPR - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 8e1c9a45-fe1f-45c6-b2cd-b281ca671192

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg FTPR YoY' = [TY FTPR]-[LY FTPR]
		formatString: ##0.00;(##0.00)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: ac91d2b8-0f6f-4ced-96c8-afb22b8b5d0f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg FTPR YoY' = DIVIDE([ABS Chg FTPR YoY], [LY FTPR], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 33cf279f-1fd2-4b7b-b98c-2eb5e7b704f7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Cont. Growth First Time Pick Rate' = ```
			
			var _TotalABSFTPR = 
			    CALCULATE([ABS Chg FTPR YoY], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([ABS Chg FTPR YoY] , _TotalABSFTPR)*100
			```
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 9bc71d6e-9fb3-4a4c-82b5-1420e4d7c737

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW StoresSelling 2' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[LW_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 9e1b5ea8-ccb7-4028-bcf5-2a17da13eccc

		changedProperty = IsHidden

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'FYTD Sales % Chg' = DIVIDE(([FYTD TY Sales]-[FYTD LY Sales (FYTD)]),[FYTD LY Sales (FYTD)])
		formatString: 0.0%;(0.0%)
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: bca072cc-36ad-4dab-961b-8a4d6b16058d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'FYTD Qty % Chg' = DIVIDE(([FYTD TY Qty]-[FYTD LY Qty (FYTD)]),[FYTD LY Qty (FYTD)])
		formatString: 0.0%;(0.0%)
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 7020edac-6514-4af0-8686-f665c3424065

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'FYTD Price % Chg' = DIVIDE([FYTD TY Price]-[FYTD LY Price (FYTD)], [FYTD LY Price (FYTD)], 0)
		formatString: 0.0%;(0.0%)
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 4713dc80-dd57-41d4-ad40-3aa05190f06d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Avg Inventory U''s - TODO' =
			SWITCH(
			    TRUE(),
			    MAX('WM Master - Time Frame'[Period ID])="FYTD", [FYTD TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="L52W",[L52W TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="L13W",[L13W TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="L4W",[L4W TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="LW",[LW TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="CW",[CW TY Avg Inventory],
			    MAX('WM Master - Time Frame'[Period ID])="FYTD2", [FYTD TY Avg Inventory]
			)
		formatString: #,0
		displayFolder: TY Metrics - Time Frames
		lineageTag: 64407db1-761f-43ae-8ecc-42b52475b76c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Cont. Growth U/S/W' = ```
			
			var _TotalABSSales = 
			    CALCULATE([ABS Chg U/S/W YoY], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([ABS Chg U/S/W YoY] , _TotalABSSales)*100
			```
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 1de26716-bd6a-4920-99fe-413948cbb0bf

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cont. Growth Stores Selling' = ```
			
			var _TotalABSStoresSelling = 
			    CALCULATE([ABS Chg Stores Selling YoY], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([ABS Chg Stores Selling YoY] , _TotalABSStoresSelling)*100
			```
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 2156114b-d141-4a4a-a488-56bd5e2b5859

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[LW_TY_ON_HAND_QTY]), 7, 0 )
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: b22ab1a2-9bcc-4600-b41c-6c143ecab229

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[L4W_TY_ON_HAND_QTY]), 28, 0 )
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 0e4e7d29-8746-401d-ac4e-7b6fd84eb665

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[L13W_TY_ON_HAND_QTY]), 91, 0 )
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: efcb6d7c-00ea-481a-ba44-65c355f2eeaa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[FYTD_TY_ON_HAND_QTY]), [FYTD Days Count], 0 )
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: f516d961-6699-4a4b-9763-e1fc6b3e98e5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WM Yr Week Num' = MAX('WM_CATEGORY_INFO'[LAST_UPDATED_DATE])
		formatString: General Date
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 6aaede0b-6f19-45ba-ba9c-f20cb43ccac1

		changedProperty = IsHidden

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'L13W Sales % Chg' = DIVIDE(([L13W TY Sales]-[L13W LY Sales]),[L13W LY Sales])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 551bf153-a4fa-4195-afa9-ed7951bd6e11

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'L4W Sales % Chg' = DIVIDE(([L4W TY Sales]-[L4W LY Sales]),[L4W LY Sales])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: d5c845b9-1b59-469b-8529-257b3e6b52ac

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'LW Sales % Chg' = DIVIDE(([LW TY Sales]-[LW LY Sales]),[LW LY Sales])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: b22da1e5-7826-44e1-9085-ff0d1e37c84d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Out Of Stock' = SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[LW_OUT_OF_STOCK])
		formatString: #,0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 70788eaa-4c4b-488a-ba36-481368843945

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'LW In Stock' = [Count Store-UPCs] * 7
		formatString: #,0
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: e35a3a38-2521-49fe-9e36-47e890ed514e

		changedProperty = IsHidden

	measure 'Weeks Count' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", MAX('WM_CATEGORY_INFO'[CAL_WM_WK_NBR]),
				Period = "L52W", 52,
				Period = "L13W", 13,
				Period = "L4W", 4,
				Period = "LW", 1,
				// Period = "CW", CALCULATE([Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 55ae87a4-1d6b-4c6b-a8c6-b787ed9e9740

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD Days Count' = ((MAX('WM_CATEGORY_INFO'[CAL_WM_WK_NBR])-1)*7)+MAX('WM_CATEGORY_INFO'[CAL_WM_WK_DAY_NBR])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: fb114109-9df0-4bfb-a73b-1f5354061c28

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Inventory' = SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[FYTD_TY_ON_HAND_QTY])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 4a457424-bd7b-4522-96b5-1553a8914a93

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Count Store-UPCs' =
			COUNTROWS (
			    DISTINCT (
			        ADDCOLUMNS (
			            WM_STORE_ITEM_UPC_TIMEFRAMES,  // Replace with your actual table name
			            "Store-UPC", CONCATENATE(WM_STORE_ITEM_UPC_TIMEFRAMES[STORE_NBR], WM_STORE_ITEM_UPC_TIMEFRAMES[WM_UPC_NBR])
			        )
			    )
			)
		formatString: 0
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 41f8198c-6ca7-4a30-ad46-9449dd84d013

		changedProperty = IsHidden

	measure 'LY % of Total $ Sales' = ```
			
			var _TotalSales = 
			    CALCULATE([LY $ Sales], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([LY $ Sales] , _TotalSales, 0)
			```
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 853bd603-4710-4885-be10-0f1e9fa79fb5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY % of Total Units' = ```
			
			var _TotalSales = 
			    CALCULATE([LY Unit Sales], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([LY Unit Sales] , _TotalSales, 0)
			```
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: c979dca0-5161-4937-a4dd-3a54e8646498

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'L52W TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L52W_TY_SALES_AMT])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 4bb5eace-a533-4979-bb77-71dab11e2a74

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[CW_TY_SALES_AMT])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 7657a55d-8ac5-4ccc-ae8a-0384737f1fc6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Unit Sales.
	measure 'L52W TY Units' = SUM(WM_STORE_SALES_TIMEFRAMES[L52W_TY_QTY])
		formatString: #,##0;(#,##0)
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 2399a627-6dc4-402d-9569-896c9f8e9ac7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Unit Sales.
	measure 'CW TY Units' = SUM(WM_STORE_SALES_TIMEFRAMES[CW_TY_QTY])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 1df2fa4b-7bd4-478d-959b-0e58bc92fe74

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Avg Period Price.
	measure 'L52W TY Price' = DIVIDE([L52W TY Sales], [L52W TY Units])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: d6be1791-0872-4435-9cbf-72d1c72ebfdc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Avg Period Price.
	measure 'CW TY Price' = DIVIDE([CW TY Sales], [CW TY Units])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: d1aeb04f-b92e-49f3-9aab-cca713adf942

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 5b77fb83-08cd-4573-9fd2-fa7d88a751a5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 122bf80a-1a7c-4da8-9566-284425fa2e63

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 64e31abe-60ea-4df8-a69e-46d1a8412387

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_FTPR_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 2682ae3b-42cd-400a-a750-9bd348b8740c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[L52W_TY_ON_HAND_QTY]), 364, 0 )
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: e2c2ca5b-70a2-4419-8007-e9d074faf3bb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Avg Inventory' = DIVIDE ( SUM(WM_STORE_ITEM_UPC_TIMEFRAMES[CW_TY_ON_HAND_QTY]), [CW Days Count], 0 )
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: af312f68-b1a7-466b-9b54-e1be710bb856

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW Days Count' = MAX('WM_CATEGORY_INFO'[CAL_WM_WK_DAY_NBR])
		formatString: 0
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: bc821144-7d04-4cea-be1a-2c445cff8eec

		changedProperty = IsHidden

	measure 'CW TY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[CW_TY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 7f7fa006-0354-4249-95cb-455617632b67

		changedProperty = IsHidden

	measure 'L52W LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[L52W_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: d12ba30d-29e1-4d33-b229-23782182cb47

		changedProperty = IsHidden

	measure 'CW LY Stores Selling' = ```
			CALCULATE(
			    DISTINCTCOUNT(WM_STORE_SALES_TIMEFRAMES[STORE_NBR]), 
			    WM_STORE_SALES_TIMEFRAMES[CW_LY_SALES_AMT] > 0
			)
			```
		formatString: 0
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 845b27e6-e6a6-43b7-98d8-b38bbcdbd0a9

		changedProperty = IsHidden

	measure 'L52W LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[L52W_LY_QTY])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: ea138608-1901-48ee-bc5e-08445a83ed78

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Qty' = SUM(WM_STORE_SALES_TIMEFRAMES[CW_LY_QTY])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: ef820585-3c7f-4853-afe7-80b73ba7f22b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Year Avg Period Price.
	measure 'L52W LY Price' = DIVIDE([L52W LY Sales], [L52W LY Qty])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 89425340-e476-4605-9faf-e13f90069291

		changedProperty = IsHidden

	measure 'L52W LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[L52W_LY_SALES_AMT])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 325503f1-0c55-4814-ae50-2fa83fb36c42

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Sales' = SUM(WM_STORE_SALES_TIMEFRAMES[CW_LY_SALES_AMT])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: ce6c2496-95b2-4c07-b20c-da3efca39aba

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 45a3772d-6ab6-4879-9b36-b97b803770a5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Nil Picks' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_NIL_PICK_RATE_NMRTR])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: ca924232-3876-4760-984b-82892d535e95

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: cff20634-3792-4dc0-bdb9-c5bea34bc4ca

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY First Time Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_FTPR_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_FTPR_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 5cb5a727-183e-477b-a286-29a1af6a4280

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Year Avg Period Price.
	measure 'CW LY Price' = DIVIDE([CW LY Sales], [CW LY Qty])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 3b72873c-fac5-4858-b9e1-6eca67b55430

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'LW TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 3911f97c-bcb6-4a28-b476-7b6be7d4ad21

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'CW TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 9726f902-07e9-4369-bf57-1ebadf594f95

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'L4W TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 75be4bf0-c7cb-4062-a862-d9e007b0d34a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'L13W TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: ab92df56-a4ae-47c4-92dc-76c37a965736

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'L52W TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 95cfc3f2-99ad-4c0e-bee5-c56e2d481a95

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: e4717b65-6850-4c20-a071-5db8111507da

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 8c87a4d0-bf17-4963-ab90-4dccd8a402d5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 7bb2cbda-6b5d-4de6-a567-fb0745d9cfe9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 327ee5b2-c0e5-402b-8a06-9397c1574b4b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 323cbfd1-7a03-440c-806e-744c9a9d6447

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Nil Pick Rate' = ```
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Nil Pick Rate - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Nil Pick Rate - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Nil Pick Rate - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
			
			```
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: a4c1d355-6982-4644-b641-c6c862124329

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'FYTD TY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 50b31880-b975-443f-b75a-875189a3a484

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Nil Pick Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_NIL_PICK_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_NIL_PICK_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: a9344df1-8e50-440e-a592-27564fdbf71d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Nil Pick Rate' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Nil Pick Rate - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Nil Pick Rate - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Nil Pick Rate - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY Nil Pick Rate - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: be77172c-3b6f-4e51-8f65-0d9349973d66

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Nil Pick Rate YoY' = [TY Nil Pick Rate]-[LY Nil Pick Rate]
		formatString: ##0.00;(##0.00)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 4f9a91d2-e6e4-4e2d-bae8-b477c09a1cff

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Nil Pick Rate YoY' = DIVIDE([ABS Chg Nil Pick Rate YoY], [LY Nil Pick Rate], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 9f2fc9b4-1b93-461c-9ca7-436fec7218b3

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Pre Sub Rate' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY PreSub Rate - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY PreSub Rate - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY PreSub Rate - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY PreSub Rate - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY PreSub Rate - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Pre Sub Rate - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 532f3541-9ed9-4654-b96f-d1a3ff7f6eac

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Post Sub Rate' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY PostSub Rate - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY PostSub Rate - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY PostSub Rate - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY PostSub Rate - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY PostSub Rate - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY PostSub Rate - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: fd2b9f9e-b850-4cee-864f-f3497fd97b1d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Delayed Pick' = [TY Pre Sub Rate]-[TY FTPR]
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 952a7e78-5d79-4a36-8778-e6a645cbf717

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Digital $ Penetration' = DIVIDE([TY Digital $ Sales], [TY $ Sales], BLANK())
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: fee0d5b1-3ec1-4f80-87bd-6388d5bd098f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Digital $ Sales' =
			CALCULATE([TY $ Sales],
			'WM Master - Service Channel'[KEY] <> 1)
		formatString: $#,##0;$(#,##0)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 03750609-e9ac-459b-81a3-c4617807070a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY Digital $ Sales' =
			CALCULATE([LY $ Sales],
			'WM Master - Service Channel'[KEY] <> 1)
		formatString: $#,##0;$(#,##0)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 413ad252-218a-4a76-ab9f-b4f6f2587b66

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Digital $ Sales YoY' = [TY Digital $ Sales] - [LY Digital $ Sales]
		formatString: $#,##0;$(#,##0)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 5274401e-3e35-4aef-a701-95ffab5c2f4d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Digital $ Sales  YoY' = DIVIDE([ABS Chg Digital $ Sales YoY],[LY Digital $ Sales], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 496001ed-3d97-4a3b-93ee-7b473259316d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY Digital Penetration' = DIVIDE([LY Digital $ Sales], [LY $ Sales])
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 0b1bb3cc-f718-4c06-ab89-584fbffdcc7e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Digital Penetration YoY' = [TY Digital $ Penetration] - [LY Digital Penetration]
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: fd5e5f28-4a64-48b3-86bd-b6b070097c8e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Digital Penetration YoY' = DIVIDE([ABS Chg Digital Penetration YoY],[LY Digital Penetration], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: d567f326-36b0-4a3d-816b-a2ca716d2dbe

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'FYTD LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 6a2d89f9-8db6-45da-b28b-037cffbfa07b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 5a9f685e-f73c-4068-abb3-b84675257430

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: e7d47cba-04c6-4a83-96c8-ee16a34db2b1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 2c578344-5356-4132-bbbe-54a599a2335b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 44acd5e8-341a-417c-826d-f15e5cf77897

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 8ba4f3fd-7e3b-49d0-bab1-42be1ca14000

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: b276e469-0cf3-4aba-ae74-b34e3413f46a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 2b8fcfd7-a1f3-4bfd-9de0-20aeedbaa0a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 839226e8-4340-4dd8-b0cd-6cdb05319148

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: b804cf66-7d4e-456d-8f8e-c836a3a7da05

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: d9e1636a-c87f-494c-9007-bfe19939e9f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Pre Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_PRESUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_PRESUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 7875b05a-b9ec-454d-b784-db8a0896398c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 21ad89cf-f1b9-44bc-8451-84a638e7188f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: bc36860f-83b5-4452-b07e-547c4d5ef39f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 21dc37d1-1e1b-47c0-99ac-2d89826d7fb7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 903a6744-cf39-4380-9e05-e4a5a0175147

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 6a24f625-e95d-41c3-8d96-320c053ebfe5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 936f712e-1f3d-4b1a-bd22-2465a9db118b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 2a0d22c3-ceec-41bc-a991-3537feb2d066

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 625b3455-4064-46c1-a23f-f29b4480e38b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 23f3185e-3f3b-432f-976f-142d50351f92

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: f10fa915-b15f-4033-a17e-f8b7380b1f16

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: c4eadbe7-3a82-448e-ae1b-392cf27def01

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY Post Sub Rate' = DIVIDE(SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_POSTSUB_RATE_NMRTR]), SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_POSTSUB_RATE_DNMNTR]))
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: de8c8906-86a2-45cc-9774-8bcaa91facb1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Digital $ Growth YoY' = ```
			
			var _TotalSales = 
			    CALCULATE([TY $ Sales], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([TY Digital $ Sales] , _TotalSales, 0)
			```
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: c6eaa499-4ec1-460d-96a8-3e5314306c98

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of Digital Sales YoY' = ```
			
			var _TotalOPDSales = 
			    CALCULATE([TY Digital $ Sales], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([TY Digital $ Sales] , _TotalOPDSales)
			```
		formatString: 0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 7f50ee0d-b773-46aa-bb51-804784ada110

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'FYTD TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: e70a795c-87ff-47de-b1e9-5ff511180d43

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'LW TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 85fa3592-9fb8-489f-b79d-f82b548b9fec

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'L4W TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 73fccf1c-32ec-4205-897d-d812ddd8974b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'L13W TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 724a3f08-15e3-4a8d-90ab-1ae7f7850b4d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'L52W TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 761072bc-7fee-4589-9fe0-8824c2130a73

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'CW TY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_NIL_PICK_QTY])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: d521f3d3-d113-4310-8417-a4bf7e3d14fa

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: 703f242e-6cf1-42d9-987c-57ed56611960

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: a3c04fc8-0a70-44cd-a627-4765070f55b8

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 8a24a307-c6ef-42ec-9c05-8060f479d0cc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: a2abf76d-f32e-4dc4-889f-ecc5d5e22e97

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 0b46444d-49fc-489e-a1de-d008b78aa200

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Nil Pick Qty' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_NIL_PICK_QTY])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 8a1d7cab-69ca-4c7e-b40c-74efc9ee48a0

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Nil Pick Qty' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Nil Pick Qty - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Nil Pick Qty - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Nil Pick Qty - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: #,0
		displayFolder: TY Metrics - Time Frames
		lineageTag: 4be1a661-0e59-4c3d-88f4-b1bee274e43c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'LY Nil Pick Qty' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Nil Pick Qty - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Nil Pick Qty - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Nil Pick Qty - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY Nil Pick Qty - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: #,0
		displayFolder: LY Metrics - Time Frames
		lineageTag: 02a6bed4-49b9-4ab0-85cc-93ef7f20081f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg Nil Pick Qty YoY' = [TY Nil Pick Qty]-[LY Nil Pick Qty]
		formatString: 0.0;(0.0)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: e96f493f-3a64-4b25-ac9a-13ba73221e99

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Nil Pick Qty YoY' = DIVIDE([ABS Chg Nil Pick Qty YoY], [LY Nil Pick Qty], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 75b308d9-aec5-487f-84c1-796b96da6fee

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY Nil Pick Lost $ Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY Nil Pick Lost $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY Nil Pick Lost $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY Nil Pick Lost $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $#,##0;$(#,##0)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 198b89d2-8fb7-40ee-8365-9ac053b8c3cc

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'L13W Avg Weekly Nil Pick Lost $ Sales' = DIVIDE ( [TY Nil Pick Lost $ Sales], 91, 0 )
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: 92e32862-06f2-4f55-9f9a-4e8d3d614a76

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Weekly Nil Pick Lost $ Sales' =
			SWITCH(
			    TRUE(),
			    MAX('WM Master - Time Frame'[Period ID])="FYTD", DIVIDE([FYTD TY Nil Pick Lost Sales], [Weeks Count], 0),
			    MAX('WM Master - Time Frame'[Period ID])="L52W", DIVIDE([L52W TY Nil Pick Lost Sales], 52, 0),
			    MAX('WM Master - Time Frame'[Period ID])="L13W", DIVIDE([L13W TY Nil Pick Lost Sales], 13, 0),
			    MAX('WM Master - Time Frame'[Period ID])="L4W", DIVIDE([L4W TY Nil Pick Lost Sales], 4, 0),
			    MAX('WM Master - Time Frame'[Period ID])="LW", DIVIDE([LW TY Nil Pick Lost Sales], 1, 0),
			    MAX('WM Master - Time Frame'[Period ID])="CW", DIVIDE([CW TY Nil Pick Lost Sales], 1, 0)
			)
		formatString: $#,##0;$(#,##0)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: f376f60f-4e7f-4f9a-a9ad-96fde20ebc78

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'TY OPD $ Sales' =
			CALCULATE([TY $ Sales],
			'WM Master - Service Channel'[ID] = 2 || 'WM Master - Service Channel'[ID] = 3)
		formatString: $#,##0;$(#,##0)
		displayFolder: TY Metrics - Time Frames
		lineageTag: 9e6ee395-112d-4c43-a338-ddc4f6be571e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY OPD $ Sales' = CALCULATE([LY $ Sales], 'WM Master - Service Channel'[KEY] <> 1 )
		displayFolder: LY Metrics - Time Frames
		lineageTag: 5899f226-5d56-4c6a-9e4d-839786467809

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY OPD $ Penetration' = DIVIDE([TY OPD $ Sales], [TY $ Sales])
		formatString: 0.0%;(0.0%)
		displayFolder: TY Metrics - Time Frames
		lineageTag: ff0d9fa9-4cb5-4c4f-b16c-881532f73e1a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY % OPD Penetration' = DIVIDE([LY OPD $ Sales], [LY $ Sales], BLANK())
		formatString: 0.0%;(0.0%)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 726cb419-66a1-4b66-b549-636bd768fa1a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg OPD Penetration YoY' = [TY OPD $ Penetration] - [LY % OPD Penetration]
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 2c1c6b8f-7910-463f-be7a-5d52108f2604

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure '% of OPD Sales YoY' = ```
			
			var _TotalOPDSales = 
			    CALCULATE([TY OPD $ Sales], ALL(WM_STORE_SALES_TIMEFRAMES))
			return
			    DIVIDE([TY OPD $ Sales] , _TotalOPDSales)
			```
		formatString: 0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 9c2fecc2-6b36-4e0b-bbfd-a44a970b0f0e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg OPD $ Sales YoY' = DIVIDE([ABS Chg Digital $ Sales YoY],[LY OPD $ Sales], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 1a605339-4569-4c15-ac62-0caa725dbdc5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Year-over-year absolute difference:
	/// Absolute difference between This Year and Last Year metric.
	measure 'ABS Chg OPD $ Sales YoY' = [TY OPD $ Sales] - [LY OPD $ Sales]
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: 06f7a77b-2025-4105-96ad-9e952a07a917

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales % by Pack Type' =
			DIVIDE(
			    [TY $ Sales],
			    CALCULATE(
			        [TY $ Sales],
			        ALLEXCEPT('WM Master - Item', 'WM Master - Item'[CA_PACK_TYPE])
			    )
			)
		formatString: 0.0%;(0.0%)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: dc28323b-06da-4eee-ac77-347b4bfd728a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LW TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: fa8974aa-9328-40d9-afec-c590576e9f7f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: a93c3465-58ec-4408-ae69-7e7de7098cd6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: afdb907e-e748-4773-8e3a-0d8aaa37b9d2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: b18f102d-d614-4290-ab62-158a57cb4066

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: d4d13096-34c6-4a31-84c0-7a415fcb9a2e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD TY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_TY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: e6122bf1-a3db-4101-a5cb-7294ac2e58cb

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LW LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[LW_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: LW - Store Sales and Fulfillment
		lineageTag: f3261a0a-d204-400d-b395-5d75fb65304b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L4W LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L4W_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L4W - Store Sales and Fulfillment
		lineageTag: 3823f25b-011e-43b4-b6ae-c569ab38d7f4

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L13W LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L13W_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L13W - Store Sales and Fulfillment
		lineageTag: a7ea7dfa-2f6c-4b43-a011-4391f23540e2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'L52W LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[L52W_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: be5a55ed-e61d-43c1-a5ac-11eac86e9be5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CW LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[CW_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: CW - Store Sales and Fulfillment
		lineageTag: 9f2c309a-2fe3-4103-a1ed-064a6599f019

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FYTD LY Nil Pick Lost Sales' = SUM(WM_STORE_FULFILLMENT_TIMEFRAMES[FYTD_LY_NIL_PICK_AMOUNT])
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: fb43561b-7d6f-42e9-96f5-98c38e807dd2

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Nil Pick Lost $ Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([LY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([LY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([LY Nil Pick Lost $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([LY Nil Pick Lost $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([LY Nil Pick Lost $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([LY Nil Pick Lost $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		displayFolder: LY Metrics - Time Frames
		lineageTag: ad3d3581-00f0-499b-a862-78cfd48bf59d

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Stores Selling (All)' = CALCULATE([TY Store Selling Count], ALL('WM Master - Store'[STORE_NBR_TXT]))
		formatString: 0
		displayFolder: TY Metrics - Time Frames
		lineageTag: 1309cc32-bcbf-4d4c-9fa6-3a862f9572a5

		changedProperty = IsHidden

	measure 'FYTD Weeks Filter' = IF(SELECTEDVALUE(WM_STORE_SALES_WEEKLY[CAL_WM_WK_NBR]) < SELECTEDVALUE(WM_CATEGORY_INFO[CAL_WM_WK_NBR]), "1", BLANK())
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 8b79a3f4-2b3e-450a-8d97-5600aeb48a33

		changedProperty = IsHidden

	measure 'Total Open Stores' =
			CALCULATE(
			    DISTINCTCOUNT('WM Master - Store'[STORE_NBR]),
			     'WM Master - Store'[OPEN_STATUS_CD] IN {"1", "2", "3", "4", "5", "6"}
			)
		formatString: 0
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: d2a4425f-b0fe-4b01-adc4-17699a216364

		changedProperty = IsHidden

	measure 'TY Distribution %' = DIVIDE([TY Store Selling Count], [Total Open Stores], 0)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: TY Metrics - Time Frames
		lineageTag: 8d28b797-2039-481f-838e-06b997c15607

		changedProperty = IsHidden

	measure 'LY Distribution %' = DIVIDE([LY Stores Selling], [Total Open Stores], 0)
		displayFolder: LY Metrics - Time Frames
		lineageTag: 6d93960b-b3fd-4b22-9b1d-8713ae435cab

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure '% Chg Distribution YoY' = DIVIDE([TY Store Selling Count]-[LY Stores Selling], [LY Stores Selling], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: Year of Year Metrics - Time Frames
		lineageTag: b93559e8-ca5b-48b6-accd-22b080ed22c6

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year $ Sales Velocity: $ per Store per Week.
	measure 'L52W TY $/S/W' = DIVIDE(DIVIDE([L52W TY Sales], [L52W TY Stores Selling], 0), 52, 0)
		formatString: $#,##0.00;$(#,##0.00)
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 398746a9-ad0b-4949-ace7-58ceed72711f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Unit Sales Velocity: Units per Store per Week.
	measure 'L52W TY U/S/W' = DIVIDE(DIVIDE([L52W TY Units], [L52W TY Stores Selling], 0), 52, 0)
		isHidden
		displayFolder: L52W - Store Sales and Fulfillment
		lineageTag: 8d21b6f5-14dc-4ebd-81be-22ba0b85a52f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Year-over-year percentage change: the percentage difference between This Year and Last Year's metric.
	measure 'FYTD % Chg Distribution' = DIVIDE([FYTD TY Stores Selling]-[FYTD LY Stores Selling], [FYTD LY Stores Selling], 0)
		formatString: +0.0%;(0.0%)
		isHidden
		displayFolder: FYTD - Store Sales and Fulfillment
		lineageTag: 381355e1-fb53-446a-97ab-d8d98ee964e5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Stores-Week' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Total Stores-Week - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Total Stores-Week - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Total Stores-Week - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Total Stores-Week - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Total Stores-Week - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Total Stores-Week - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 042c3693-42de-44be-893d-925945ce75ca

	measure 'In Stock Rate %' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([TY In Stock Rate - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([TY In Stock Rate - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([TY In Stock Rate - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([TY In Stock Rate - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([TY In Stock Rate - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([TY In Stock Rate - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 43511736-5a01-4446-86f4-acebd3261ac9

	/// Days of Supply (DOS):
	/// Store UPC Capacity / (Avg Weekly Units / 7)
	measure DOS =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([DOS - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([DOS - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([DOS - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([DOS - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([DOS - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([DOS - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		displayFolder: Time Frames - Store Sales and Fulfillment
		lineageTag: 250aa7a9-31f8-496b-8ed4-52dea5688dc2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Weekend Days of Supply (DOS):
	/// Store UPC Capacity / (Weekend Avg Weekly Units / 3)
	/// Weekend days: Friday - Sunday
	measure 'Weekend DOS' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Weekend DOS - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Weekend DOS - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Weekend DOS - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Weekend DOS - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Weekend DOS - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Weekend DOS - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: dfd396b8-62da-4512-8635-e9be487528a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Weekend Sales Amount.
	/// Weekends only sales: Friday - Sunday.
	measure 'Weekend TY $ Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Weekend TY $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Weekend TY $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Weekend TY $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Weekend TY $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Weekend TY $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Weekend TY $ Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $#,##0
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 30d7de5d-1938-4291-a3f5-70df9da5dc23

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year Weekend Sales Units.
	/// Weekends only sales: Friday - Sunday.
	measure 'Weekend TY Unit Sales' = SUM(WM_STORE_SALES_WEEKLY[WEEKEND_TY_QTY])
		formatString: #,0.0
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 695974fb-762a-41f3-911b-fa0459ba6469

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	/// This Year Weekend $ Sales Velocity: $ per Store per Week.
	/// Weekends only sales: Friday - Sunday.
	measure 'Weekend TY $/S/W' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Weekend TY $/S/W - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Weekend TY $/S/W - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Weekend TY $/S/W - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Weekend TY $/S/W - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Weekend TY $/S/W - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Weekend TY $/S/W - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $#,##0.0;$(#,##0.0)
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 748dff9c-bfb7-41cb-a1b6-ff77460de630

		changedProperty = IsHidden

	/// This Year Weekend Unit Sales Velocity: Units per Store per Week.
	/// Weekends only sales: Friday - Sunday.
	measure 'Weekend TY U/S/W' = DIVIDE([Weekend TY Unit Sales - Weekly], [Total Stores-Week - Weekly], 0)
		formatString: #,0.0
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 3f505abe-91f9-4bc1-b410-2a5d3b3cc190

		changedProperty = IsHidden

	/// This Year Weekend Average Weekly Sales Units.
	/// Weekends only sales: Friday - Sunday.
	measure 'Weekend TY Avg Wkly Unit Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Weekend TY Avg Wkly Unit Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Weekend TY Avg Wkly Unit Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Weekend TY Avg Wkly Unit Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Weekend TY Avg Wkly Unit Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Weekend TY Avg Wkly Unit Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: #,0
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 65377e34-1767-4c29-a471-23ad7b84295c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Weekend TY Avg Wkly $ Sales' =
			
			VAR Period = SELECTEDVALUE('WM Master - Time Frame'[Period ID] )
			
			RETURN SWITCH(
			    TRUE(),
			    Period = "FYTD", CALCULATE([Weekend TY Avg Wkly $ Sales - Weekly], 	'WM Master - Calendar Week'[FYTD_FLAG] = "X"),
				Period = "L52W", CALCULATE([Weekend TY Avg Wkly $ Sales - Weekly], 	'WM Master - Calendar Week'[L52W_FLAG] = "X"),
				Period = "L13W", CALCULATE([Weekend TY Avg Wkly $ Sales - Weekly], 	'WM Master - Calendar Week'[L13W_FLAG] = "X"),
				Period = "L4W", CALCULATE([Weekend TY Avg Wkly $ Sales - Weekly],		'WM Master - Calendar Week'[L4W_FLAG] = "X"),
				Period = "LW", CALCULATE([Weekend TY Avg Wkly $ Sales - Weekly], 		'WM Master - Calendar Week'[LW_FLAG] = "X"),
				// Period = "CW", CALCULATE([Sales - Weekly],	 	'WM Master - Calendar Week'[CW_FLAG] = "X"),
				BLANK()
			)
		formatString: $#,##0
		displayFolder: Weekend Metrics - Time Frames
		lineageTag: 89a1e071-94f1-4060-b4d4-38868972a783

		annotation PBI_FormatHint = {"isCustom":true}

	partition '03. Metrics - Store Sales and Fulfillment Time Frames' = m
		mode: import
		queryGroup: 'Reporting - Metrics'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measures", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Measures"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

