/// Calendar view provides Walmart calendar date, month, and week details. It also has specific flags for TimePeriods: LW Last Week, L4W Last 4 Weeks, L13W Last 13 Weeks, L52W Last 52 Weeks, FYTD Walmart Fiscal Year to Date.
/// 
/// Source: WM_CALENDAR_WEEK_VIEW
table 'WM Master - Calendar Week'
	lineageTag: 64ec53b6-f54f-4698-8371-4b3436237491

	/// Walmart Year Week Number.
	/// A number representing the full Walmart year and week.
	column WM_YR_WK_NBR
		dataType: int64
		formatString: 0
		lineageTag: 858b8a3d-d28e-44d7-b1a0-87326862eaa5
		summarizeBy: none
		sourceColumn: WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Week Number
	column WM_WK_NBR
		dataType: double
		formatString: 0
		lineageTag: 926c6f5b-668c-461e-95c3-2bfcc204c4fb
		summarizeBy: sum
		sourceColumn: WM_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Full Year Number
	column WM_FULL_YR_NBR
		dataType: double
		formatString: 0
		lineageTag: 11f9ca1c-04cc-449e-b742-933bc175053d
		summarizeBy: sum
		sourceColumn: WM_FULL_YR_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Walmart Year Week Number - Text Format
	column WM_YR_WK_TXT
		dataType: string
		lineageTag: 585dae5f-df24-46fd-ba27-c2dcc1da04d0
		summarizeBy: none
		sourceColumn: WM_YR_WK_TXT
		sortByColumn: WM_YR_WK_NBR

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Start Date for Walmart Year Week
	column WM_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1c8904fd-06fd-4584-8511-f9ad900c5f33
		summarizeBy: none
		sourceColumn: WM_START_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// End Date for Walmart Year Week
	column WM_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 405d515c-b5e9-4800-ab06-292d5c7b3429
		summarizeBy: none
		sourceColumn: WM_END_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Fiscal Year to Date Flag: indicates weeks which are part of the FYTD Time Frame
	column FYTD_FLAG
		dataType: string
		lineageTag: 231e8a49-665e-4e8e-a917-950a25b0dd3a
		summarizeBy: none
		sourceColumn: FYTD_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last Week Flag: indicates weeks which are part of the LW Time Frame
	column LW_FLAG
		dataType: string
		lineageTag: 549b608c-366c-4282-b693-e3d4ca197fce
		summarizeBy: none
		sourceColumn: LW_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last 13 Weeks Flag: indicates weeks which are part of the L13W Time Frame
	column L13W_FLAG
		dataType: string
		lineageTag: d45a7f21-72fa-4d01-8cc2-27fcb619e8cb
		summarizeBy: none
		sourceColumn: L13W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last 4 Weeks Flag: indicates weeks which are part of the L4W Time Frame
	column L4W_FLAG
		dataType: string
		lineageTag: 945d6740-d121-4596-bcab-326fd1a3172e
		summarizeBy: none
		sourceColumn: L4W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Last 52 Weeks Flag: indicates weeks which are part of the L52W Time Frame
	column L52W_FLAG
		dataType: string
		lineageTag: 54ed7a02-4463-4425-8c77-cd77d642dba6
		summarizeBy: none
		sourceColumn: L52W_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'WM Master - Calendar Week' = m
		mode: import
		queryGroup: 'Reporting - Master Data'
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    SILVER_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WALMART_CALENDAR_VIEW = SILVER_Schema{[Name="WM_CALENDAR_WEEK_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WALMART_CALENDAR_VIEW,{{"WM_YR_WK_NBR", Int64.Type}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "WM_YR_WK_NBR", "WM_YR_WK_TXT"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Duplicated Column",{{"WM_YR_WK_TXT", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

