DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('WM_SALES_IMPORT'[SVC_CHNL_NM])),
			NOT('WM_SALES_IMPORT'[SVC_CHNL_NM] IN {BLANK()})
		)

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('Periods'[Periods])),
			NOT('Periods'[Periods] IN {"FYTD 2"})
		)

	VAR __DS0FilterTable3 = 
		TREATAS({"Sales",
			"Units",
			"Price"}, 'Metric 1'[Measure])

	VAR __DS0FilterTable4 = 
		FILTER(
			KEEPFILTERS(VALUES('Measure Selection'[Selection])),
			NOT('Measure Selection'[Selection] IN {"ABS Chg",
				"Cont. Growth",
				"LY Value"})
		)

	VAR __DS0FilterTable5 = 
		TREATAS({"storesales"}, 'WM_SALES_IMPORT'[FEED_NAME])

	VAR __DS0FilterTable6 = 
		FILTER(
			KEEPFILTERS(VALUES('ITEM_ATTRIBUTES_VIEW'[ITEM_RB_PACK_TYPE])),
			NOT('ITEM_ATTRIBUTES_VIEW'[ITEM_RB_PACK_TYPE] IN {"Not Applicable",
				BLANK()})
		)

	VAR __DS0FilterTable7 = 
		FILTER(
			KEEPFILTERS(VALUES('STORE_DIMENSIONS_VIEW'[STORE_STATE_PROV_CD])),
			NOT('STORE_DIMENSIONS_VIEW'[STORE_STATE_PROV_CD] IN {"PR"})
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('STORE_DIMENSIONS_VIEW'[STORE_BANNER_DESC], "IsGrandTotalRowTotal"),
			'Periods'[Periods],
			__DS0FilterTable,
			__DS0FilterTable2,
			__DS0FilterTable3,
			__DS0FilterTable4,
			__DS0FilterTable5,
			__DS0FilterTable6,
			__DS0FilterTable7,
			"Dummy", 'Measures Table'[Dummy],
			"v__Chg_Sales", 'Measures Table'[% Chg Sales],
			"v__Chg_Units", 'Measures Table'[% Chg Units],
			"v__Chg_Price", 'Measures Table'[% Chg Price],
			"Chg_Sales", 'Measures Table'[Chg Sales],
			"TY___Sales", 'Measures Table'[TY $ Sales],
			"TY_Units", 'Measures Table'[TY Units],
			"TY_Price", 'Measures Table'[TY Price]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			102,
			SUMMARIZE(__DS0Core, 'STORE_DIMENSIONS_VIEW'[STORE_BANNER_DESC], [IsGrandTotalRowTotal]),
			[IsGrandTotalRowTotal],
			0,
			'STORE_DIMENSIONS_VIEW'[STORE_BANNER_DESC],
			1
		)

	VAR __DS0SecondaryBase = 
		SUMMARIZE(__DS0Core, 'Periods'[Periods])

	VAR __DS0Secondary = 
		TOPN(102, __DS0SecondaryBase, 'Periods'[Periods], 1)

	VAR __DS0BodyLimited = 
		NATURALLEFTOUTERJOIN(
			__DS0PrimaryWindowed,
			SUBSTITUTEWITHINDEX(
				__DS0Core,
				"ColumnIndex",
				__DS0Secondary,
				'Periods'[Periods],
				ASC
			)
		)

EVALUATE
	__DS0Secondary

ORDER BY
	'Periods'[Periods]

EVALUATE
	__DS0BodyLimited

ORDER BY
	[IsGrandTotalRowTotal] DESC,
	'STORE_DIMENSIONS_VIEW'[STORE_BANNER_DESC],
	[ColumnIndex]