/// Provides information about all scheduled store fulfillment orders at Walmart item, store and week level.
/// All metrics are aggregated at Walmart Week Level.
/// 
/// Recommend usage along with:
/// - WM Master: Calendar Week
/// - WM Master: Store
/// - WM Master: UPC
/// - WM Master: Mod Trait
/// 
/// Source: WM_STORE_FULFILMENT_WEEK_VIEW.
table '02. Metrics - Store Fulfillment Weekly'
	lineageTag: ea04111c-aacf-469a-9cb9-effc275f241f

	measure 'TY Nil Pick Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_NIL_PICK_RATE_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: ee3e496d-ca2f-4965-812f-0c05af245ae5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year First Time Pick Rate Numerator
	measure 'TY FTPR Numerator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_FTPR_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 37a11989-dafe-496f-88e8-cefb200d1bee

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year First Time Pick Rate Denominator
	measure 'TY FTPR Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_FTPR_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 64b93aff-55b3-4cce-a7d1-3b6f26533614

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Nil Pick Qty - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[LY_NIL_PICK_RATE_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: LY Metrics
		lineageTag: 24d0006b-689e-4276-bc1a-d57946c9f4ea

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Nil Pick Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[LY_NIL_PICK_RATE_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: LY Metrics
		lineageTag: c67be453-5cb7-467e-854c-7f9f07c779db

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY Nil Pick Rate - Weekly' = DIVIDE([LY Nil Pick Qty - Weekly], [LY Nil Pick Denominator - Weekly], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: LY Metrics
		lineageTag: 2a17fadc-f0e6-404b-a148-726c8269ec08

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'LY FTPR Numerator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[LY_FTPR_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: LY Metrics
		lineageTag: a1ff1d3c-f2e0-4ff8-9d48-db47418efd22

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LY FTPR Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[LY_FTPR_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: LY Metrics
		lineageTag: 2e654044-5102-4c57-bcb1-2c4c099daa26

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Last Year First Time Pick Rate:
	/// The percentage of items that were picked in the first pick-walk for store fulfilled orders.
	measure 'LY FTPR - Weekly' = DIVIDE([LY FTPR Numerator - Weekly], [LY FTPR Denominator - Weekly], 0)
		formatString: +0.0%;(0.0%)
		displayFolder: LY Metrics
		lineageTag: 5f882ccb-6464-4841-9e50-20a1d6fd3f6f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// This Year Nil Pick Rate: The percentage of items that were not fulfilled for fulfilled orders.
	measure 'TY Nil Pick Rate - Weekly' = DIVIDE([TY Nil Pick Numerator - Weekly], [TY Nil Pick Denominator - Weekly], BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: This Year Metrics
		lineageTag: fc3f9ede-10f1-4d37-adc5-a7cfcfa872ed

		changedProperty = IsHidden

	/// This Year First Time Pick Rate:
	/// The percentage of items that were picked in the first pick-walk for store fulfilled orders.
	measure 'TY FTPR - Weekly' = DIVIDE([TY FTPR Numerator - Weekly], [TY FTPR Denominator - Weekly], BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: This Year Metrics
		lineageTag: 6550791f-229e-4e8c-817f-7e1c51ff6593

		changedProperty = IsHidden

	/// This Year Nil Pick Quantity: The number of units not picked or substituted by a store for  store fulfilled orders.
	measure 'TY Nil Pick Qty - Weekly' = ```
			CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_NIL_PICK_QTY]), ALL('WM Master - Calendar Week Pre Relay'))
			
			```
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: d006678b-c50f-4966-b672-a879bd50a12c

		changedProperty = IsHidden

	measure 'TY Nil Pick Numerator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_NIL_PICK_RATE_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 990331a6-80aa-4ab7-a2c4-046e5c60c862

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY PreSub Numerator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_PRESUB_RATE_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 536c7b43-0f95-4e84-8658-64bbee63cac9

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY PreSub Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_PRESUB_RATE_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: d8b3d66a-4e25-4d78-bfe0-0a49c85041c1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY PreSub Rate - Weekly' = DIVIDE([TY PreSub Numerator - Weekly], [TY PreSub Denominator - Weekly], BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: This Year Metrics
		lineageTag: 7f8d1be5-6974-4ae3-9daf-519d43515433

		changedProperty = IsHidden

	measure 'TY PostSub Numerator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_POSTSUB_RATE_NMRTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: 46848270-2e35-460b-9f63-31cd252e4a42

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY PostSub Denominator - Weekly' = CALCULATE(SUM(WM_STORE_FULFILLMENT_WEEKLY[TY_POSTSUB_RATE_DNMNTR]), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,##0;(#,##0)
		displayFolder: This Year Metrics
		lineageTag: db11f48b-83ab-4081-854c-215a5ca0d632

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY PostSub Rate - Weekly' = DIVIDE([TY PostSub Numerator - Weekly], [TY PostSub Denominator - Weekly], BLANK())
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: This Year Metrics
		lineageTag: 6f962849-ee09-4f5f-aff8-d4a5260fd705

		changedProperty = IsHidden

	/// Total UPC Capacity considering all Main Placements and Mod Racks assigned to the Store.
	measure 'Total Capacity - Weekly' = ```
			
			VAR MAX_WEEK = MAX(WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR])
			
			RETURN CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                WM_STORE_MODULAR_UPC_WEEK[TRAIT_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[STORE_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[UPC_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR],
			                "UPCCapacity", MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY])
			//                CALCULATE(
			//                        MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY]),
			//                        WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR] = MAX_WEEK 
			//                        )
			            ), [UPCCapacity]
			        ),
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			
			
			```
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: 2759bedb-bc2d-4cbf-96c5-ce670aa7df95

		changedProperty = IsHidden

	/// Days of Supply (DOS):
	/// Store UPC Capacity / (Avg Weekly Units / 7)
	measure 'DOS - Weekly' = ```
			
			    CALCULATE(
			        DIVIDE([Total Capacity - Weekly], DIVIDE([TY Avg Wkly Unit Sales - Weekly], 7, 0), 0),
			        WM_STORE_SALES_WEEKLY[IN_MODULAR] = "Yes"
			        )
			```
		displayFolder: This Year Metrics
		lineageTag: 7d763953-2e1a-4c5b-b27d-f0d2008d66ac

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// This Year In Stock Rate:
	/// Average weekly percentage of UPCs with stock on a store.
	/// This metric considers only In Modular (Store Planogram) UPCs.
	measure 'TY In Stock Rate - Weekly' =
			
			VAR TotalOutOfStock =
			    CALCULATE(
			        SUM(WM_STORE_ITEM_UPC_WEEKLY[OUT_OF_STOCK]),
			        WM_STORE_ITEM_UPC_WEEKLY[IN_MODULAR] = "Yes",
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			VAR RowCount =
			    CALCULATE(
			        COUNTROWS(WM_STORE_ITEM_UPC_WEEKLY),
			        WM_STORE_ITEM_UPC_WEEKLY[IN_MODULAR] = "Yes",
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			VAR TotalDays =
			    RowCount * 7
			RETURN
			DIVIDE( TotalDays - TotalOutOfStock, TotalDays, BLANK() )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: This Year Metrics
		lineageTag: 6ac57b9d-671d-4041-a9f5-54fe1bf680c7

		changedProperty = IsHidden

	measure 'TY Total PODs - Weekly' =
			
			VAR UniqueStoreUPC =
			    DISTINCT(
			        SELECTCOLUMNS(
			            FILTER(WM_STORE_ITEM_UPC_WEEKLY, WM_STORE_ITEM_UPC_WEEKLY[IN_MODULAR] = "Yes"),
			            "Store", WM_STORE_ITEM_UPC_WEEKLY[STORE_NBR],
			            "UPC", WM_STORE_ITEM_UPC_WEEKLY[WM_UPC_NBR]
			        )
			    )
			RETURN
			    CALCULATE(COUNTROWS(UniqueStoreUPC), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: e12cf453-8796-47ef-8e91-97ad7505dba0

		changedProperty = IsHidden

	/// Sum of # Out of Stock Store UPC combination:
	/// 1 - Out of Stock
	/// 0 - No, there is stock
	measure '# Out of Stock - Store UPC Weekly' = CALCULATE(SUM(WM_STORE_ITEM_UPC_LATEST[OUT_OF_STOCK]))
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: c0ce2e97-317d-4f52-a3be-c6ef592e948a

		changedProperty = IsHidden

	measure 'TY Total PODs - Store UPC Weekly' =
			
			VAR UniqueStoreUPC =
			    DISTINCT(
			        SELECTCOLUMNS(
			            FILTER(WM_STORE_ITEM_UPC_WEEKLY, WM_STORE_ITEM_UPC_WEEKLY[IN_MODULAR] = "Yes"),
			            "Store", WM_STORE_ITEM_UPC_WEEKLY[STORE_NBR],
			            "UPC", WM_STORE_ITEM_UPC_WEEKLY[WM_UPC_NBR]
			        )
			    )
			RETURN
			    CALCULATE(COUNTROWS(UniqueStoreUPC), ALL('WM Master - Calendar Week Pre Relay'))
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: f55fcdf4-7a24-42f5-87a3-9da33402b8ab

		changedProperty = IsHidden

	/// UPC Capacity on a Store Main Placement.
	/// Calculated at Store, Trait and UPC level.
	measure 'Main Placement Capacity - Weekly' = ```
			
			VAR MAX_WEEK = MAX(WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR])
			
			RETURN CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                WM_STORE_MODULAR_UPC_WEEK[TRAIT_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[STORE_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[UPC_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR],
			                "UPCCapacity", MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY])
			//                CALCULATE(
			//                        MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY]),
			//                        WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR] = MAX_WEEK 
			//                        )
			            ), [UPCCapacity]
			        ),
			        WM_STORE_MODULAR_UPC_WEEK[MOD_REF_CATEGORY] = "Main Placement",
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			
			
			```
		displayFolder: This Year Metrics
		lineageTag: 3f92323c-a40a-4c24-bb73-210553d5762e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// UPC Capacity on a Store Mod Rack.
	/// Calculated at Store, Trait and UPC level.
	measure 'Mod Rack Capacity - Weekly' = ```
			
			VAR MAX_WEEK = MAX(WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR])
			
			RETURN CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                WM_STORE_MODULAR_UPC_WEEK[TRAIT_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[STORE_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[UPC_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR],
			                "UPCCapacity", 
			                MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY])
			//                CALCULATE(
			//                        MAX(WM_STORE_MOD_RACK_UPC_WEEK[TOT_CPCTY_QTY]),
			//                        WM_STORE_MOD_RACK_UPC_WEEK[WM_YR_WK_NBR] = MAX_WEEK 
			//                        )
			            ), [UPCCapacity]
			        ),
			        WM_STORE_MODULAR_UPC_WEEK[MOD_REF_CATEGORY] = "Mod Rack",
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			
			
			
			
			
			```
		displayFolder: This Year Metrics
		lineageTag: 79465cde-db30-4a36-ad05-fc9daa1bb811

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Weekend Days of Supply (DOS):
	/// Store UPC Capacity / (Weekend Avg Weekly Units / 3)
	/// Weekend days: Friday - Sunday
	measure 'Weekend DOS - Weekly' = ```
			
			    CALCULATE(
			        DIVIDE([Total Capacity - Weekly], DIVIDE([Weekend TY Avg Wkly Unit Sales - Weekly], 3, 0), 0),
			        WM_STORE_SALES_WEEKLY[IN_MODULAR] = "Yes"
			    )
			
			```
		formatString: #,0.0
		displayFolder: This Year Metrics
		lineageTag: 82f09d63-e17d-413b-9713-2f7ca68393c7

		changedProperty = IsHidden

	measure 'LY Nil Pick Lost $ Sales - Weekly' = [LY Nil Pick Qty - Weekly] * [LY Price - Weekly]
		displayFolder: LY Metrics
		lineageTag: 247900fd-bad6-4468-bdab-d21a690ee261

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Nil Pick Lost $ Sales - Weekly' = [TY Nil Pick Qty - Weekly] * [TY Price - Weekly]
		displayFolder: This Year Metrics
		lineageTag: 93f39090-6c4d-4325-8f32-d2cbfad16d50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Avg Inventory' = AVERAGE(WM_STORE_ITEM_UPC_WEEKLY[TY_ON_HAND_QTY])
		displayFolder: This Year Metrics
		lineageTag: 8bc712f8-582c-4eab-99d2-dfa8727f3a50

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY Inventory Start of Week' = SUM(WM_STORE_ITEM_UPC_WEEKLY[TY_START_ON_HAND_QTY])
		displayFolder: This Year Metrics
		lineageTag: 3d16b8a6-bdc6-480b-80cb-5fc9e0a56b8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Count of Stores with DOS less than 3.5
	measure '# Stores with DOS <3.5' = ```
			
			COUNTROWS(
			    FILTER(
			        ADDCOLUMNS(
			            VALUES( 'WM Master - Store'[STORE_NBR] ),
			            "DOS_AT_STORE", CALCULATE( [DOS - Weekly] )
			        ),
			        [DOS_AT_STORE] > 0
			            && [DOS_AT_STORE] < 3.5
			    )
			)
			
			```
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: c50dc64a-622d-46c4-8801-1f0b1c06205d

	measure 'Weekend # Stores with DOS < 3.5' = ```
			
			COUNTROWS(
			    FILTER(
			        ADDCOLUMNS(
			            VALUES( 'WM Master - Store'[STORE_NBR] ),
			            "WEEKEND_DOS_AT_STORE", CALCULATE( [Weekend DOS - Weekly] )
			        ),
			        [WEEKEND_DOS_AT_STORE] > 0
			            && [WEEKEND_DOS_AT_STORE] < 3.5
			    )
			)
			
			```
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: d9ba0f4b-177d-4b53-a6dd-de2d8fb9757f

	measure 'Horizontal Facings Qty - Weekly' = ```
			
			VAR MAX_WEEK = MAX(WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR])
			
			RETURN CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                WM_STORE_MODULAR_UPC_WEEK[TRAIT_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[STORE_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[UPC_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR],
			                "Facings", MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_HRZNL_FACING_QTY])
			//                CALCULATE(
			//                        MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY]),
			//                        WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR] = MAX_WEEK 
			//                        )
			            ), [Facings]
			        ),
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			
			
			```
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: 7fa70a41-fdbb-45a2-bc53-e4c1f119aa9a

	measure 'Vertical Facings Qty - Weekly' = ```
			
			VAR MAX_WEEK = MAX(WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR])
			
			RETURN CALCULATE(
			        SUMX(
			            SUMMARIZECOLUMNS(
			                WM_STORE_MODULAR_UPC_WEEK[TRAIT_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[STORE_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[UPC_NBR],
			                WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR],
			                "Facings", MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_VERTICAL_FACING_QTY])
			//                CALCULATE(
			//                        MAX(WM_STORE_MODULAR_UPC_WEEK[TOT_CPCTY_QTY]),
			//                        WM_STORE_MODULAR_UPC_WEEK[WM_YR_WK_NBR] = MAX_WEEK 
			//                        )
			            ), [Facings]
			        ),
			        ALL('WM Master - Calendar Week Pre Relay')
			    )
			
			
			```
		formatString: 0
		displayFolder: This Year Metrics
		lineageTag: e23bc359-3484-411c-92eb-596dc81d3331

	measure 'TY Missed First Time Picks' = [TY FTPR Denominator - Weekly] - [TY FTPR Numerator - Weekly]
		formatString: #,0
		displayFolder: This Year Metrics
		lineageTag: a8ab2385-970b-401f-80f7-62a5916f6a20

	partition '02. Metrics - Store Fulfillment Weekly' = m
		mode: import
		queryGroup: 'Reporting - Metrics'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

