/// Time Frame master view.
table 'WM Master - Time Frame'
	lineageTag: 72d11ce7-be5a-466e-a509-6da972a44468

	column 'Period ID'
		dataType: string
		lineageTag: 5b911756-e98b-4ee8-904e-8cd2d0c91fcf
		summarizeBy: none
		sourceColumn: Period ID
		sortByColumn: Order

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Time Frame
	column 'Time Frame'
		dataType: string
		lineageTag: c0f40c30-8104-47b8-8120-6149fc152ab7
		summarizeBy: none
		sourceColumn: Time Frame
		sortByColumn: Order

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: int64
		formatString: 0
		lineageTag: bf11a2b1-1e0a-43c0-bd0b-6235a5d0c06a
		summarizeBy: sum
		sourceColumn: Order

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'WM Master - Time Frame' = m
		mode: import
		queryGroup: 'Reporting - Master Data'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcosMcVHSgVGGSrE60Uo+pkbhQI5PYnGJgqmRQnhqanYxkG8EkTQ0hksaGsMljSGSJnA5E7iUCUQKLgMSB7JNwcLOIGHn0qKi1Dy4jBlYBuQkI6jTFEAMc6XYWAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, Column1 = _t, Order = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Column1", type text}, {"Order", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Time Frame"}, {"Period", "Period ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

