/// Walmart Category Sales model.
/// UPC Sales (Shopper Behavior) view provides information about store and eComm sales at UPC and store level.
/// The UPC Store Sales endpoint will contain Store & Ecomm sales, aggregated weekly. Ecomm sales are reported under the store number “-999”.
/// The sales number under the UPC Store Sales endpoint may not match with the sales number under our Store Sales endpoint.
/// This model is refreshed weekly on Mondays, resulting in a 9 to 15-day delay.
/// 
/// SOURCE: WM_UPC_SALES_VIEW
table WM_STORE_FULFILMENT_HOURLY
	isHidden
	lineageTag: ddc4168e-af28-4df2-9492-0cb5f825d2fe

	column STORE_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 790a2e40-c14e-4f8e-854f-e8720cfc26d8
		summarizeBy: none
		sourceColumn: STORE_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WM_ITEM_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 21e4c92b-8ea4-4e24-a27f-0f4f6e43360d
		summarizeBy: sum
		sourceColumn: WM_ITEM_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BUS_DT
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 79544084-1d30-4c78-8d9e-abd7da11f9fa
		summarizeBy: none
		sourceColumn: BUS_DT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RPT_HR_NBR
		dataType: double
		isHidden
		lineageTag: 4ac5ca1d-f5b4-46aa-a069-8324faa0f524
		summarizeBy: none
		sourceColumn: RPT_HR_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OP_CMPNY_CD
		dataType: string
		isHidden
		lineageTag: 81a645ab-6ed5-403c-af9e-551868a7f742
		summarizeBy: none
		sourceColumn: OP_CMPNY_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GEO_REGION_CD
		dataType: string
		isHidden
		lineageTag: ede8621c-e6e8-4701-8d81-4bed698a5704
		summarizeBy: none
		sourceColumn: GEO_REGION_CD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FULFMT_TYPE_DESC
		dataType: string
		isHidden
		lineageTag: e90dd24e-bbeb-4834-845c-f5a633fa207e
		summarizeBy: none
		sourceColumn: FULFMT_TYPE_DESC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CATLG_ITEM_ID
		dataType: double
		isHidden
		lineageTag: e8dd168f-a390-41c5-8f1d-c2f238b7e18d
		summarizeBy: count
		sourceColumn: CATLG_ITEM_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FTPR_NMRTR
		dataType: double
		isHidden
		lineageTag: 5c3757e4-8e13-4ac9-8bea-b4bde76a10f6
		summarizeBy: sum
		sourceColumn: FTPR_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FTPR_DNMNTR
		dataType: double
		isHidden
		lineageTag: 75c27206-93ab-4270-b322-02c26f113c60
		summarizeBy: sum
		sourceColumn: FTPR_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRESUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: abee2d55-a71a-4131-a8e0-1cf32fa9d070
		summarizeBy: sum
		sourceColumn: PRESUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PRESUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: fa313df0-b16a-419f-9333-384aecf4cff1
		summarizeBy: sum
		sourceColumn: PRESUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POSTSUB_RATE_NMRTR
		dataType: double
		isHidden
		lineageTag: 8999ae1d-cf32-48c8-a985-38bd2b77cfa9
		summarizeBy: sum
		sourceColumn: POSTSUB_RATE_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column POSTSUB_RATE_DNMNTR
		dataType: double
		isHidden
		lineageTag: fe726fff-d049-4583-94c9-c35948945e11
		summarizeBy: sum
		sourceColumn: POSTSUB_RATE_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NIL_PICK_NMRTR
		dataType: double
		isHidden
		lineageTag: 147c9a75-1ebe-4405-8847-aee4793abcf4
		summarizeBy: sum
		sourceColumn: NIL_PICK_NMRTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NIL_PICK_DNMNTR
		dataType: double
		isHidden
		lineageTag: ecfa5cf4-db4d-4698-aa74-e2e6c5592a1d
		summarizeBy: sum
		sourceColumn: NIL_PICK_DNMNTR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CUST_ORDER_QTY
		dataType: double
		isHidden
		lineageTag: a3bc11c3-df6c-4357-9b17-03360c17878d
		summarizeBy: sum
		sourceColumn: CUST_ORDER_QTY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CUST_ORDER_AMT
		dataType: double
		isHidden
		lineageTag: 1133d3bc-e714-4221-9dcf-7cbd36c976b0
		summarizeBy: sum
		sourceColumn: CUST_ORDER_AMT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DELTA_FLAG
		dataType: string
		isHidden
		lineageTag: 656f2e39-3eab-4916-ad9c-1103cecbb1a5
		summarizeBy: none
		sourceColumn: DELTA_FLAG

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FILE_MODIFIED_TIMESTAMP
		dataType: string
		isHidden
		lineageTag: 117adbac-4524-4e72-80c4-1cbebfe8e827
		summarizeBy: none
		sourceColumn: FILE_MODIFIED_TIMESTAMP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HOUR
		dataType: string
		isHidden
		lineageTag: 784f1c77-87c5-43fa-9e9a-1a73db19bbfe
		summarizeBy: none
		sourceColumn: HOUR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REPL_GROUP_NBR
		dataType: double
		isHidden
		lineageTag: 1cd0154e-6892-4de8-9295-0898c89cb2a0
		summarizeBy: sum
		sourceColumn: REPL_GROUP_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GTIN
		dataType: string
		isHidden
		lineageTag: fd2032d3-c6ae-4f8b-a864-8ae39f558dc1
		summarizeBy: none
		sourceColumn: GTIN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LOCATION_AREA
		dataType: string
		isHidden
		lineageTag: 02762137-1463-4826-8910-953888c77736
		summarizeBy: none
		sourceColumn: LOCATION_AREA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QUANTITY
		dataType: double
		isHidden
		lineageTag: a45f19e2-36be-4974-ba0e-bf8e9857d973
		summarizeBy: sum
		sourceColumn: QUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LAST_UPDATED_TS
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 2bcff833-c453-4adb-969f-a93428346e17
		summarizeBy: none
		sourceColumn: LAST_UPDATED_TS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STATUS_DATE
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 1f1bb1e5-2efb-43a8-9eb0-e5dc837d06be
		summarizeBy: none
		sourceColumn: STATUS_DATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FEED_TYPE
		dataType: string
		isHidden
		lineageTag: 5d749c42-f0f2-4231-b3d5-8d5cae6c6dd0
		summarizeBy: none
		sourceColumn: FEED_TYPE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FILE_NAME
		dataType: string
		isHidden
		lineageTag: c59e1c78-8cc5-440f-ba54-53fc9fb6e288
		summarizeBy: none
		sourceColumn: FILE_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UPC_NBR
		dataType: string
		isHidden
		lineageTag: 1d608257-4db2-4796-99bd-be5014040095
		summarizeBy: none
		sourceColumn: UPC_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column WM_YR_WK_NBR
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5d1e603c-3489-4425-940e-9843e4f22a39
		summarizeBy: none
		sourceColumn: WM_YR_WK_NBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CAL_WK_DAY_ABBR
		dataType: string
		isHidden
		lineageTag: 4ad85883-1032-47f5-9b6a-4740dfdff7a6
		summarizeBy: none
		sourceColumn: CAL_WK_DAY_ABBR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition WM_STORE_FULFILMENT_HOURLY = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("fe65796.west-europe.azure.snowflakecomputing.com","RBNA_IT_BI_ANALYTICS_WH"),
				    WMCA_Database = Source{[Name="RBNA_IT_BI_ANALYTICS_DB",Kind="Database"]}[Data],
				    GOLD_Schema = WMCA_Database{[Name="LUMINATE_GOLD",Kind="Schema"]}[Data],
				    WM_STORE_FULFILMENT_HOURLY = GOLD_Schema{[Name="WM_STORE_FULFILMENT_HOURLY_VIEW",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(WM_STORE_FULFILMENT_HOURLY,{{"WM_YR_WK_NBR", Int64.Type}, {"STORE_NBR", Int64.Type}, {"WM_ITEM_NBR", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

