table '00.  Local Metrics'
	lineageTag: 1583e6e9-a8aa-4745-954b-abaa06deaf50

	measure 'Years $ Sales' =
			SWITCH(
			    TRUE(),
			    MAX('99. Year Master'[Year])="TY", [TY $ Sales],
			    MAX('99. Year Master'[Year])="LY", [LY $ Sales]
			)
		lineageTag: 105878e9-ae02-4b40-99ac-567aef443b5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Year - % of Total $ Sales' =
			SWITCH(
			    TRUE(),
			    MAX('99. Year Master'[Year])="TY", [TY % of Total $ Sales],
			    MAX('99. Year Master'[Year])="LY", [LY % of Total $ Sales]
			)
		lineageTag: bc4d680d-d9d0-4852-81df-74686703e583

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '00.  Local Metrics' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

