table 'Metric 3'
	isHidden
	lineageTag: 27b6bfe0-81e0-471e-a816-855ba5d657af

	column Measure
		dataType: string
		isHidden
		lineageTag: 7a5dc9a3-b48a-4e5d-846a-8db55ae9581c
		summarizeBy: none
		sourceColumn: Measure
		sortByColumn: ID

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3c280af3-65f7-4898-8548-bf7e6aeaf380
		summarizeBy: none
		sourceColumn: ID

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Format
		dataType: string
		isHidden
		lineageTag: 6b0257b0-7985-4d06-bc73-19198de4230e
		summarizeBy: none
		sourceColumn: Format

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Metric 3' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("hZBPC4JAEMW/yrApFAj+qbTwKkGXkjQ6qAeRTYa2FXQL+vatqbUV1GEYZt9v9j0mSYgGUc5oQwxiyUpTbWRY/rjrE7/rJDMSsucoWsyWNbyFNRZUzs7vVc2MzINEpn8cemymOESUMeQlRKKqHyldRVzzK+VSuME+vViW47WApwArrBsBMZ4phFicYJeLNq49VRgdqiPElcgZvG5h9xn0T+R5hbkKBFhi90FIORV1LrDiLeWq1DYMvglPJTbI3oMulKCD+LBfDkJ2Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measure = _t, ID = _t, Format = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measure", type text}, {"ID", Int64.Type}, {"Format", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

